-- The level-17 backfill, applied to a scratch database and checked.
--
-- Generated by scripts/build-level17-migration.mjs --fixture. Regenerate
-- rather than editing, or it stops describing the migration it tests.
--
-- Eight categories advertised fewer than 17 levels. In six of them that
-- was never a content shortage: Georgian held roughly twice what every
-- other language did, because translate-questions only ever fans the
-- ENGLISH bank out and a question authored in Georgian is invisible to
-- it. The migration translates that tail. This seeds a database with
-- the same shape and proves the tail lands where it is needed.

\set ON_ERROR_STOP on
\pset pager off

CREATE OR REPLACE FUNCTION pg_temp.must_equal(got bigint, want bigint, label text)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
  IF got IS DISTINCT FROM want THEN
    RAISE EXCEPTION 'FAILED: % -- got %, want %', label, got, want;
  END IF;
END $$;

-- A clean slate for exactly the eight slugs this touches; anything else
-- in the database belongs to another test file.
DELETE FROM questions WHERE category_id IN (SELECT id FROM categories WHERE category_id IN ('anime_manga', 'ecology', 'fun_facts', 'myths_reality', 'psychology', 'science', 'spanish_literature', 'portuguese_literature'));
DELETE FROM categories WHERE category_id IN ('anime_manga', 'ecology', 'fun_facts', 'myths_reality', 'psychology', 'science', 'spanish_literature', 'portuguese_literature');

-- anime_manga: short by 14 in each of en/de/es/fr/it/pt, with 14 untranslated
-- Georgian rows sitting there unused.
INSERT INTO categories (category_id, name, total_levels, language, is_language_specific, is_active)
VALUES ('anime_manga', 'anime_manga', 1, 'ka', false, true);
INSERT INTO questions (category_id, question_text, correct_answer, incorrect_answers, language, difficulty, level_number, is_active, in_production)
SELECT c.id, 'anime_manga'||'-'||l.lang||'-'||g, 'a', '["b","c","d"]'::jsonb, l.lang, 'easy', 1, true, true
  FROM categories c, unnest(ARRAY['ka']) AS l(lang), generate_series(1, 170) g
 WHERE c.category_id = 'anime_manga';
INSERT INTO questions (category_id, question_text, correct_answer, incorrect_answers, language, difficulty, level_number, is_active, in_production)
SELECT c.id, 'anime_manga'||'-'||l.lang||'-'||g, 'a', '["b","c","d"]'::jsonb, l.lang, 'easy', 1, true, true
  FROM categories c, unnest(ARRAY['en', 'de', 'es', 'fr', 'it', 'pt']) AS l(lang), generate_series(1, 156) g
 WHERE c.category_id = 'anime_manga';
-- The Georgian tail, at the ids the migration names.
INSERT INTO questions (id, category_id, question_text, correct_answer, incorrect_answers, language, difficulty, level_number, icon_slug, is_active, in_production)
SELECT s.id::uuid, c.id, 'anime_manga'||'-source-'||s.id, 'a', '["b","c","d"]'::jsonb, 'ka', 'medium', 7, 'brain', true, true
  FROM categories c, unnest(ARRAY[
    '15c5059f-face-4ff4-811f-10f63fa6ff37',
    '252c771b-1eea-4422-8707-aafa159a42bc',
    '8190c651-61ba-430b-9ccc-98e6646e54ec',
    'f38b86f3-2851-4407-a9eb-ae7b4d9fb9d0',
    'c762f08f-0e4d-4f7f-99d0-c4c1a8d448be',
    'debc7662-3759-4f2d-82d4-4fbfa4b1f68d',
    '3ca4b0f3-b834-4174-a4cd-b80d1222bfed',
    'd703a7d2-3888-4282-9f9c-6bc5216bb043',
    'e96eade2-ddf6-41ee-a72f-ea0caedd1a12',
    '37e70f6b-0d94-44ef-82e3-64dc80f9570a',
    '916e8a61-1f82-46e6-aacd-050beff738a3',
    '0067e0af-f660-4cf4-a4de-891c11e7bc59',
    '21b6f97d-d3e8-49d6-8b67-f33b40628f64',
    'ee4aaef7-5d75-4486-9c47-c12d796c16b0'
  ]) AS s(id)
 WHERE c.category_id = 'anime_manga';

-- ecology: short by 1 in each of en/de/es/fr/it/pt, with 1 untranslated
-- Georgian rows sitting there unused.
INSERT INTO categories (category_id, name, total_levels, language, is_language_specific, is_active)
VALUES ('ecology', 'ecology', 1, 'ka', false, true);
INSERT INTO questions (category_id, question_text, correct_answer, incorrect_answers, language, difficulty, level_number, is_active, in_production)
SELECT c.id, 'ecology'||'-'||l.lang||'-'||g, 'a', '["b","c","d"]'::jsonb, l.lang, 'easy', 1, true, true
  FROM categories c, unnest(ARRAY['ka']) AS l(lang), generate_series(1, 170) g
 WHERE c.category_id = 'ecology';
INSERT INTO questions (category_id, question_text, correct_answer, incorrect_answers, language, difficulty, level_number, is_active, in_production)
SELECT c.id, 'ecology'||'-'||l.lang||'-'||g, 'a', '["b","c","d"]'::jsonb, l.lang, 'easy', 1, true, true
  FROM categories c, unnest(ARRAY['en', 'de', 'es', 'fr', 'it', 'pt']) AS l(lang), generate_series(1, 169) g
 WHERE c.category_id = 'ecology';
-- The Georgian tail, at the ids the migration names.
INSERT INTO questions (id, category_id, question_text, correct_answer, incorrect_answers, language, difficulty, level_number, icon_slug, is_active, in_production)
SELECT s.id::uuid, c.id, 'ecology'||'-source-'||s.id, 'a', '["b","c","d"]'::jsonb, 'ka', 'medium', 7, 'brain', true, true
  FROM categories c, unnest(ARRAY[
    'e771ef54-aefe-4ce1-9aeb-79bce6057c26'
  ]) AS s(id)
 WHERE c.category_id = 'ecology';

-- fun_facts: short by 7 in each of en/de/es/fr/it/pt, with 7 untranslated
-- Georgian rows sitting there unused.
INSERT INTO categories (category_id, name, total_levels, language, is_language_specific, is_active)
VALUES ('fun_facts', 'fun_facts', 1, 'ka', false, true);
INSERT INTO questions (category_id, question_text, correct_answer, incorrect_answers, language, difficulty, level_number, is_active, in_production)
SELECT c.id, 'fun_facts'||'-'||l.lang||'-'||g, 'a', '["b","c","d"]'::jsonb, l.lang, 'easy', 1, true, true
  FROM categories c, unnest(ARRAY['ka']) AS l(lang), generate_series(1, 170) g
 WHERE c.category_id = 'fun_facts';
INSERT INTO questions (category_id, question_text, correct_answer, incorrect_answers, language, difficulty, level_number, is_active, in_production)
SELECT c.id, 'fun_facts'||'-'||l.lang||'-'||g, 'a', '["b","c","d"]'::jsonb, l.lang, 'easy', 1, true, true
  FROM categories c, unnest(ARRAY['en', 'de', 'es', 'fr', 'it', 'pt']) AS l(lang), generate_series(1, 163) g
 WHERE c.category_id = 'fun_facts';
-- The Georgian tail, at the ids the migration names.
INSERT INTO questions (id, category_id, question_text, correct_answer, incorrect_answers, language, difficulty, level_number, icon_slug, is_active, in_production)
SELECT s.id::uuid, c.id, 'fun_facts'||'-source-'||s.id, 'a', '["b","c","d"]'::jsonb, 'ka', 'medium', 7, 'brain', true, true
  FROM categories c, unnest(ARRAY[
    'c0559c9e-d7bc-407c-9982-196c023b4e03',
    '082307c3-d6c1-4c25-b531-368b4b2832d0',
    '126d5b8b-06f0-42ee-9a59-1659237e9f1f',
    '14070322-f98e-4d2d-9298-c7445e7093c5',
    '20dc5feb-85a5-411b-aa74-605a6a403bfe',
    '83a541e8-a1f5-4fdf-9929-bfb4b392b079',
    '480aee21-7480-4507-bad5-87f4bff7c801'
  ]) AS s(id)
 WHERE c.category_id = 'fun_facts';

-- myths_reality: short by 33 in each of en/de/es/fr/it/pt, with 33 untranslated
-- Georgian rows sitting there unused.
INSERT INTO categories (category_id, name, total_levels, language, is_language_specific, is_active)
VALUES ('myths_reality', 'myths_reality', 1, 'ka', false, true);
INSERT INTO questions (category_id, question_text, correct_answer, incorrect_answers, language, difficulty, level_number, is_active, in_production)
SELECT c.id, 'myths_reality'||'-'||l.lang||'-'||g, 'a', '["b","c","d"]'::jsonb, l.lang, 'easy', 1, true, true
  FROM categories c, unnest(ARRAY['ka']) AS l(lang), generate_series(1, 170) g
 WHERE c.category_id = 'myths_reality';
INSERT INTO questions (category_id, question_text, correct_answer, incorrect_answers, language, difficulty, level_number, is_active, in_production)
SELECT c.id, 'myths_reality'||'-'||l.lang||'-'||g, 'a', '["b","c","d"]'::jsonb, l.lang, 'easy', 1, true, true
  FROM categories c, unnest(ARRAY['en', 'de', 'es', 'fr', 'it', 'pt']) AS l(lang), generate_series(1, 137) g
 WHERE c.category_id = 'myths_reality';
-- The Georgian tail, at the ids the migration names.
INSERT INTO questions (id, category_id, question_text, correct_answer, incorrect_answers, language, difficulty, level_number, icon_slug, is_active, in_production)
SELECT s.id::uuid, c.id, 'myths_reality'||'-source-'||s.id, 'a', '["b","c","d"]'::jsonb, 'ka', 'medium', 7, 'brain', true, true
  FROM categories c, unnest(ARRAY[
    'c991f535-8d58-4917-a34d-b87564fc4dc2',
    '232f0b5a-f72a-40fa-93ca-fbeb70c7efab',
    '8c20ab2f-93e3-4f3e-95e5-31bd803fc112',
    'fa34fe6c-eca9-4799-af3b-41394c8506a2',
    'b7d24308-8734-4579-8206-2db5102db0bc',
    '746ec440-9b10-469a-b5b1-12c9c98559e3',
    '133accc3-d4f2-4b88-9daf-cdfc412bdba7',
    '60cfd124-0c4f-45c8-8faa-51005b88872e',
    '17ac1daa-b816-416c-af14-ee350b23f23f',
    'cc666d3c-032a-4a75-8f45-3ef769286a69',
    '74ea2f47-fc11-4b0f-b7ff-53dac6379604',
    '0186835d-f2dd-4d2e-a773-20a058e79e5e',
    '01f01912-359c-48ea-953a-20a10443d2e3',
    '05e928d2-4cea-475f-943c-f04a7f340d1b',
    '0911b024-6997-4099-bba2-5418293daee1',
    '0b8c129b-b983-43df-b44d-cd7f4f42007f',
    '1205abb5-9fd4-427b-b57c-9939ec764257',
    '1620c2a0-d5c7-40a6-b202-6527c1451e5f',
    '16bc6a21-1108-4153-b949-166d7e161256',
    '1774f062-4847-4e75-bcf4-bce2a5f5e635',
    '1a2554de-029a-43e5-83ad-215ed210be2a',
    '1b2e77ac-ca46-4e44-b1c1-4aea1101796d',
    '1bb18826-6a46-4ac7-b894-b3cb270d5cbd',
    '1d969a7d-8495-41ad-8b25-bb1af6de04d4',
    '44041e7a-fa18-47a7-96ec-5a50ae9b1c99',
    '1eba7e86-780f-4a28-b915-c5479fd010cb',
    '1f5dd108-c885-4f22-9708-f4bfeab59e99',
    '21ebc355-0b07-4805-bd0d-27512d9c659a',
    '224e221a-7167-43db-a517-b90c997d7d26',
    '23f0c589-a31d-4ab9-afc1-471608d35092',
    '266ed68a-8b58-42be-8a38-33e05a74e2e7',
    '2925b78b-4e05-461f-b8b8-f6461ebeb0e6',
    '2c9c6c18-547e-4e19-86e9-714832969d18'
  ]) AS s(id)
 WHERE c.category_id = 'myths_reality';

-- psychology: short by 5 in each of en/de/es/fr/it/pt, with 5 untranslated
-- Georgian rows sitting there unused.
INSERT INTO categories (category_id, name, total_levels, language, is_language_specific, is_active)
VALUES ('psychology', 'psychology', 1, 'ka', false, true);
INSERT INTO questions (category_id, question_text, correct_answer, incorrect_answers, language, difficulty, level_number, is_active, in_production)
SELECT c.id, 'psychology'||'-'||l.lang||'-'||g, 'a', '["b","c","d"]'::jsonb, l.lang, 'easy', 1, true, true
  FROM categories c, unnest(ARRAY['ka']) AS l(lang), generate_series(1, 170) g
 WHERE c.category_id = 'psychology';
INSERT INTO questions (category_id, question_text, correct_answer, incorrect_answers, language, difficulty, level_number, is_active, in_production)
SELECT c.id, 'psychology'||'-'||l.lang||'-'||g, 'a', '["b","c","d"]'::jsonb, l.lang, 'easy', 1, true, true
  FROM categories c, unnest(ARRAY['en', 'de', 'es', 'fr', 'it', 'pt']) AS l(lang), generate_series(1, 165) g
 WHERE c.category_id = 'psychology';
-- The Georgian tail, at the ids the migration names.
INSERT INTO questions (id, category_id, question_text, correct_answer, incorrect_answers, language, difficulty, level_number, icon_slug, is_active, in_production)
SELECT s.id::uuid, c.id, 'psychology'||'-source-'||s.id, 'a', '["b","c","d"]'::jsonb, 'ka', 'medium', 7, 'brain', true, true
  FROM categories c, unnest(ARRAY[
    'b8d5607f-7c8a-4622-96d6-8e9bd619c1ac',
    '3081d2c3-804b-4852-a9b5-2c1953635957',
    'b5ebb38a-9e6f-47a3-933a-cf141282b6b0',
    'c29fd334-ca59-43ab-b0ae-ca27936fe4dd',
    '1cd2f491-fab1-4ded-9aef-d293f5fe17dc'
  ]) AS s(id)
 WHERE c.category_id = 'psychology';

-- science: short by 7 in each of en/de/es/fr/it/pt, with 7 untranslated
-- Georgian rows sitting there unused.
INSERT INTO categories (category_id, name, total_levels, language, is_language_specific, is_active)
VALUES ('science', 'science', 1, 'ka', false, true);
INSERT INTO questions (category_id, question_text, correct_answer, incorrect_answers, language, difficulty, level_number, is_active, in_production)
SELECT c.id, 'science'||'-'||l.lang||'-'||g, 'a', '["b","c","d"]'::jsonb, l.lang, 'easy', 1, true, true
  FROM categories c, unnest(ARRAY['ka']) AS l(lang), generate_series(1, 170) g
 WHERE c.category_id = 'science';
INSERT INTO questions (category_id, question_text, correct_answer, incorrect_answers, language, difficulty, level_number, is_active, in_production)
SELECT c.id, 'science'||'-'||l.lang||'-'||g, 'a', '["b","c","d"]'::jsonb, l.lang, 'easy', 1, true, true
  FROM categories c, unnest(ARRAY['en', 'de', 'es', 'fr', 'it', 'pt']) AS l(lang), generate_series(1, 163) g
 WHERE c.category_id = 'science';
-- The Georgian tail, at the ids the migration names.
INSERT INTO questions (id, category_id, question_text, correct_answer, incorrect_answers, language, difficulty, level_number, icon_slug, is_active, in_production)
SELECT s.id::uuid, c.id, 'science'||'-source-'||s.id, 'a', '["b","c","d"]'::jsonb, 'ka', 'medium', 7, 'brain', true, true
  FROM categories c, unnest(ARRAY[
    '6d3d48ce-a1eb-4635-8c2d-5bce7ce6b7bc',
    '98c81f0f-aabd-4a06-af51-8e58c4534d36',
    '0957fff1-8a25-41ca-b4c6-7c099e4fe566',
    '13ad9a6e-51d1-451a-a8a5-c88059032590',
    '6745f6e7-5571-44fa-a41d-e7a6ba38292e',
    '069a88ce-a8a5-4e72-b085-8127476e2abf',
    '885e86e2-a7a9-4c02-bfcd-384794a7452a'
  ]) AS s(id)
 WHERE c.category_id = 'science';

-- spanish_literature: es only, 2 short, and nothing to translate from.
INSERT INTO categories (category_id, name, total_levels, language, is_language_specific, is_active)
VALUES ('spanish_literature', 'spanish_literature', 1, 'es', true, true);
INSERT INTO questions (category_id, question_text, correct_answer, incorrect_answers, language, difficulty, level_number, is_active, in_production)
SELECT c.id, 'spanish_literature'||'-'||g, 'a', '["b","c","d"]'::jsonb, 'es', 'easy', 1, true, true
  FROM categories c, generate_series(1, 168) g
 WHERE c.category_id = 'spanish_literature';

-- portuguese_literature: pt only, 3 short, and nothing to translate from.
INSERT INTO categories (category_id, name, total_levels, language, is_language_specific, is_active)
VALUES ('portuguese_literature', 'portuguese_literature', 1, 'pt', true, true);
INSERT INTO questions (category_id, question_text, correct_answer, incorrect_answers, language, difficulty, level_number, is_active, in_production)
SELECT c.id, 'portuguese_literature'||'-'||g, 'a', '["b","c","d"]'::jsonb, 'pt', 'easy', 1, true, true
  FROM categories c, generate_series(1, 167) g
 WHERE c.category_id = 'portuguese_literature';

-- Before: every one of them is short.
DO $$
DECLARE n bigint;
BEGIN
  SELECT count(*) INTO n FROM public.categories c
   WHERE c.category_id IN ('anime_manga', 'ecology', 'fun_facts', 'myths_reality', 'psychology', 'science', 'spanish_literature', 'portuguese_literature')
     AND (SELECT count(*) FROM public.questions q
           WHERE q.category_id = c.id AND q.language = 'en' AND q.is_active AND q.in_production) >= 170;
  PERFORM pg_temp.must_equal(n, 0, 'no shared category starts at 170 English questions');
END $$;

\i supabase/migrations/20260914100000_level17_backfill.sql

-- And again, because "re-runnable" is the claim most likely to be false
-- and least likely to be noticed.
\i supabase/migrations/20260914100000_level17_backfill.sql

-- After: 170 in every language served, counted exactly — a second
-- run that duplicated its rows would read 340 here, not 170.
DO $$
DECLARE n bigint;
BEGIN
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'anime_manga' AND q.language = 'ka' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 184, 'anime_manga/ka');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'anime_manga' AND q.language = 'en' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 170, 'anime_manga/en');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'anime_manga' AND q.language = 'de' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 170, 'anime_manga/de');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'anime_manga' AND q.language = 'es' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 170, 'anime_manga/es');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'anime_manga' AND q.language = 'fr' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 170, 'anime_manga/fr');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'anime_manga' AND q.language = 'it' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 170, 'anime_manga/it');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'anime_manga' AND q.language = 'pt' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 170, 'anime_manga/pt');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'ecology' AND q.language = 'ka' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 171, 'ecology/ka');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'ecology' AND q.language = 'en' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 170, 'ecology/en');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'ecology' AND q.language = 'de' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 170, 'ecology/de');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'ecology' AND q.language = 'es' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 170, 'ecology/es');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'ecology' AND q.language = 'fr' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 170, 'ecology/fr');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'ecology' AND q.language = 'it' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 170, 'ecology/it');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'ecology' AND q.language = 'pt' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 170, 'ecology/pt');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'fun_facts' AND q.language = 'ka' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 177, 'fun_facts/ka');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'fun_facts' AND q.language = 'en' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 170, 'fun_facts/en');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'fun_facts' AND q.language = 'de' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 170, 'fun_facts/de');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'fun_facts' AND q.language = 'es' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 170, 'fun_facts/es');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'fun_facts' AND q.language = 'fr' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 170, 'fun_facts/fr');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'fun_facts' AND q.language = 'it' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 170, 'fun_facts/it');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'fun_facts' AND q.language = 'pt' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 170, 'fun_facts/pt');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'myths_reality' AND q.language = 'ka' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 203, 'myths_reality/ka');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'myths_reality' AND q.language = 'en' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 170, 'myths_reality/en');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'myths_reality' AND q.language = 'de' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 170, 'myths_reality/de');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'myths_reality' AND q.language = 'es' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 170, 'myths_reality/es');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'myths_reality' AND q.language = 'fr' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 170, 'myths_reality/fr');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'myths_reality' AND q.language = 'it' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 170, 'myths_reality/it');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'myths_reality' AND q.language = 'pt' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 170, 'myths_reality/pt');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'psychology' AND q.language = 'ka' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 175, 'psychology/ka');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'psychology' AND q.language = 'en' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 170, 'psychology/en');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'psychology' AND q.language = 'de' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 170, 'psychology/de');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'psychology' AND q.language = 'es' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 170, 'psychology/es');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'psychology' AND q.language = 'fr' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 170, 'psychology/fr');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'psychology' AND q.language = 'it' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 170, 'psychology/it');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'psychology' AND q.language = 'pt' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 170, 'psychology/pt');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'science' AND q.language = 'ka' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 177, 'science/ka');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'science' AND q.language = 'en' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 170, 'science/en');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'science' AND q.language = 'de' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 170, 'science/de');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'science' AND q.language = 'es' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 170, 'science/es');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'science' AND q.language = 'fr' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 170, 'science/fr');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'science' AND q.language = 'it' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 170, 'science/it');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'science' AND q.language = 'pt' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 170, 'science/pt');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'spanish_literature' AND q.language = 'es' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 170, 'spanish_literature/es');
  SELECT count(*) INTO n FROM public.questions q JOIN public.categories c ON c.id = q.category_id
   WHERE c.category_id = 'portuguese_literature' AND q.language = 'pt' AND q.is_active AND q.in_production;
  PERFORM pg_temp.must_equal(n, 170, 'portuguese_literature/pt');
END $$;

-- The number the player is shown, which the trigger owns.
DO $$
DECLARE r record;
BEGIN
  FOR r IN SELECT category_id, total_levels FROM public.categories
            WHERE category_id IN ('anime_manga', 'ecology', 'fun_facts', 'myths_reality', 'psychology', 'science', 'spanish_literature', 'portuguese_literature') LOOP
    PERFORM pg_temp.must_equal(r.total_levels, 17, r.category_id || ' total_levels');
  END LOOP;
END $$;

-- Lineage: each translated row points at the Georgian question it came
-- from. Pointing the ENGLISH row at the Georgian source, rather than the
-- other way round, is what keeps get_untranslated_questions from later
-- picking these up and translating them back into Georgian as
-- duplicates — it only ever selects English rows whose translated_from
-- is NULL.
DO $$
DECLARE n bigint;
BEGIN
  SELECT count(*) INTO n FROM public.questions t
    JOIN public.questions src ON src.id = t.translated_from
   WHERE src.language = 'ka' AND t.language <> 'ka'
     AND src.category_id IN (SELECT id FROM public.categories WHERE category_id IN ('anime_manga', 'ecology', 'fun_facts', 'myths_reality', 'psychology', 'science'));
  PERFORM pg_temp.must_equal(n, 402, 'translated rows linked to a Georgian source');

  SELECT count(*) INTO n FROM public.questions
   WHERE language = 'en' AND translated_from IS NOT NULL AND is_active AND in_production
     AND category_id IN (SELECT id FROM public.categories WHERE category_id IN ('anime_manga', 'ecology', 'fun_facts', 'myths_reality', 'psychology', 'science'));
  PERFORM pg_temp.must_equal(n, 67, 'English rows the translator will now skip');
END $$;

-- The icon and the difficulty come from the source rather than being
-- invented, so a translated row looks like the question it translates.
DO $$
DECLARE n bigint;
BEGIN
  SELECT count(*) INTO n FROM public.questions t
    JOIN public.questions src ON src.id = t.translated_from
   WHERE src.language = 'ka'
     AND (t.icon_slug IS DISTINCT FROM src.icon_slug
       OR t.difficulty IS DISTINCT FROM src.difficulty
       OR t.level_number IS DISTINCT FROM src.level_number
       OR t.category_id IS DISTINCT FROM src.category_id);
  PERFORM pg_temp.must_equal(n, 0, 'translated rows inherit icon, difficulty, level and category');
END $$;

\echo 'ok: level-17 backfill'
