// German Translation System - Deutsch
import type { KaTranslations } from './ka';
import { en } from './en';

// German translations - extending English as base
export const de: KaTranslations = {
  ...en,
  common: { ...en.common, play: "Spielen", back: "Zurück", next: "Weiter", skip: "Überspringen", done: "Fertig", close: "Schließen", save: "Speichern", cancel: "Abbrechen", loading: "Laden...", error: "Fehler", success: "Erfolg!", continue: "Fortfahren", confirm: "Bestätigen", retry: "Erneut versuchen", gotIt: "Verstanden!", letsGo: "Los geht's!", awesome: "Toll!", nice: "Schön!", oops: "Ups!", welcome: "Willkommen!", hello: "Hallo!", coins: "Münzen", gems: "Edelsteine", noQuestionsTitle: "Noch keine Fragen", noQuestionsMessage: "Fragen in dieser Sprache werden bald hinzugefügt!", popular: "Beliebt", bestValue: "Bester Wert", limited: "Begrenzt", new: "Neu", or: "oder" },
  auth: { ...en.auth, createAccount: "Konto erstellen", username: "Benutzername", usernamePlaceholder: "Gib deinen Benutzernamen ein", password: "Passwort", passwordPlaceholder: "Gib dein Passwort ein", signIn: "Anmelden", signUp: "Registrieren", signOut: "Abmelden", alreadyHaveAccount: "Bereits ein Konto?", dontHaveAccount: "Kein Konto?", usernameRequired: "Benutzername erforderlich", passwordRequired: "Passwort erforderlich", passwordTooShort: "Passwort muss mindestens 6 Zeichen haben", usernameTooShort: "Benutzername muss mindestens 3 Zeichen haben", invalidCredentials: "Ungültige Anmeldedaten", accountCreated: "Konto erstellt!", welcomeBack: "Willkommen zurück!" },
  nav: { ...en.nav, explore: "Entdecken", map: "Karte", play: "Spielen", rank: "Rangliste", sound: "Ton", profile: "Profil", settings: "Einstellungen", home: "Startseite", menu: "Menü" },
  menu: { ...en.menu, rewards: "Belohnungen", missions: "Missionen", treasure: "Schatztruhe", shop: "Shop", party: "Party", otherGames: "Andere Spiele", settings: "Einstellungen", help: "Hilfe", privacy: "Datenschutz", signOut: "Abmelden", signIn: "Anmelden", comingSoon: "Demnächst!", player: "Spieler", points: "Punkte" },
  game: { ...en.game, playToEarn: "Spiele und verdiene XP! ✨", classicTrivia: "Klassisches Quiz", funCasual: "Spaß & Casual", educational: "Bildung", searching: "Suche...", almostThere: "Fast fertig...", findingOpponent: "Suche Gegner", matchFound: "Gegner gefunden!", you: "Du", getReady: "Mach dich bereit!", questionOf: "Frage {current}/{total}", timeUp: "Zeit abgelaufen!", correct: "Richtig! ✓", incorrect: "Falsch ✗", victory: "Sieg!", defeat: "Niederlage", draw: "Unentschieden", playAgain: "Nochmal spielen", backToHome: "Zur Startseite", pointsEarned: "+{points} Punkte", streakBonus: "Serienbonus!", perfectRound: "Perfekte Runde!", newRound: "Neue Runde", starting: "Startet...", backToRoom: "Zurück zum Raum", youWin: "🎉 Du gewinnst!", youLose: "😢 Du verlierst", itsTie: "🤝 Unentschieden!", opponent: "Gegner", quickMatch: "Schnelles Match", whatIsQuickMatch: "Was ist ein schnelles Match?", quickMatchDescription: "Tritt gegen einen zufälligen Gegner an und beantworte Fragen schneller!", howToWin: "Wie gewinnt man?", howToWinDescription: "Antworte richtig und schnell. Je schneller, desto mehr Punkte!", selectCategory: "Kategorie wählen", rewards: "Belohnungen", random: "Zufällig", searchingPlayer: "Suche Spieler...", playerFound: "Spieler gefunden!", preparingQuestions: "Bereite Fragen vor...", startingGame: "Spiel startet!", letsPlay: "Spielen", results: "Ergebnisse", tie: "Unentschieden", coin: "Münze", gem: "Edelstein" },
  discover: { ...en.discover, title: "Entdecken", searchPlaceholder: "Kategorien suchen...", all: "Alle", favorites: "Favoriten", classic: "Klassisch", fun: "Spaß", educational: "Bildung", myFavorites: "Meine Favoriten", chosenByYou: "Von dir gewählt", recentlyViewed: "Kürzlich angesehen", popular: "Beliebt", mostPlayed: "Meistgespielt", classicTrivia: "Klassisches Quiz", classicSubtitle: "Geschichte, Geographie, Wissenschaft", funSubtitle: "Filme, Musik, Sport", educationalSubtitle: "Sprachen, Literatur, Kunst", searchResults: "Ergebnisse ({count})", nothingFound: "Nichts gefunden für \"{query}\"", nothingInCategory: "Noch nichts in dieser Kategorie", noFavoritesYet: "Noch keine Favoriten", trending: "Im Trend", categoryNotFound: "Kategorie nicht gefunden", home: "Startseite", perfectScore: "🏆 Perfekte Punktzahl!", levelCompleted: "🎉 Level abgeschlossen!", tryAgainForNextLevel: "Versuche es erneut um das nächste Level freizuschalten!" },
  profile: { ...en.profile, myProfile: "Mein Profil", editProfile: "Profil bearbeiten", changeAvatar: "Avatar ändern", statistics: "Statistiken", gamesPlayed: "Gespielte Spiele", gamesWon: "Gewonnene Spiele", winRate: "Siegquote", currentStreak: "Serie", bestStreak: "Beste Serie", totalPoints: "Gesamtpunkte", title: "Profil", signInToView: "Melde dich an um dein Profil zu sehen", signIn: "Anmelden", points: "Punkte", worldRank: "Weltrangliste", localRank: "Lokale Rangliste", badge: "Abzeichen", stats: "Stats", details: "Details", email: "E-Mail", country: "Land", notSet: "Nicht festgelegt", memberSince: "Mitglied seit", recently: "Kürzlich", beginner: "Anfänger" },
  leaderboard: { ...en.leaderboard, title: "Rangliste", global: "Global", friends: "Freunde", weekly: "Wöchentlich", allTime: "Alle Zeit", yourRank: "Deine Position", noRankYet: "Noch kein Rang", playToRank: "Spiele um gerankt zu werden!", noPlayersYet: "Noch niemand in dieser Liga", daysLeft: "{days} Tage übrig", regionLeaderboard: "{region} Rangliste", globalLeaderboard: "Globale Rangliste", timeRemaining: "Verbleibende Zeit", days: "Tage", today: "Heute", stars: "Sterne", playToAppear: "Spiele um in der Rangliste zu erscheinen!", noOnePlayedYet: "Noch niemand hat gespielt", beTheFirst: "Sei der Erste!", you: "Du", levelsCompleted: "Level abgeschlossen", level: "Level" },
  team: { ...en.team, newRoom: "Neuer Raum", roomName: "Raumname", enterRoomName: "Raumname eingeben", randomName: "Zufälliger Name", category: "Kategorie", random: "Zufällig", inviteFriends: "Freunde einladen ({count} ausgewählt)", online: "Online", offline: "Offline", noFriendsYet: "Noch keine Freunde", addFriendsHint: "Füge Freunde nach dem Spiel hinzu um sie einzuladen", showMore: "Mehr anzeigen", showLess: "Weniger anzeigen", newPlayerJoined: "Neuer Spieler beigetreten!", linkCopied: "Link kopiert!", copyFailed: "Kopieren fehlgeschlagen", shareFailed: "Teilen fehlgeschlagen", deleteRoomConfirm: "Bist du sicher dass du diesen Raum löschen möchtest?", copyLink: "Link kopieren", share: "Teilen", noMessagesYet: "Noch keine Nachrichten", startGame: "Spiel starten", waitingForPlayers: "Warte auf {count} Spieler", waitingForHost: "Warte auf Host...", leaveRoom: "Raum verlassen", nameUpdated: "Name aktualisiert!", nameUpdateFailed: "Name-Aktualisierung fehlgeschlagen", roomChats: "Raum-Chats", roomsCount: "{count} Räume", selectRoomForChat: "Wähle einen Raum für den Chat", roomClosed: "Raum geschlossen", roomCreated: "Raum erstellt!", challengeSent: "Herausforderung gesendet!", roomCreateFailed: "Raumerstellung fehlgeschlagen", friendWillPlayLater: "Freund wird später spielen!", players: "Spieler", host: "Host", ready: "Bereit", notReady: "Nicht bereit", leaveConfirmTitle: "Verlassen?", leaveConfirmMessage: "Du kannst verlassen und später zurückkehren oder dauerhaft verlassen.", exitKeepRoom: "Verlassen (Im Raum bleiben)", leavePermanently: "Dauerhaft verlassen", multiplayer: "Mehrspieler", signInToPlay: "Melde dich an um mit Freunden zu spielen", onlineGame: "Online-Spiel", friends: "Freunde", yourRooms: "Deine Räume", noActiveRooms: "Keine aktiven Räume", inProgress: "Läuft", room: "Raum", continue: "Fortfahren", join: "Beitreten", recentGames: "Letzte Spiele", noGamesYet: "Noch keine Spiele", game: "Spiel", add: "Hinzufügen", all: "Alle" },
  modals: { ...en.modals, notEnoughCoins: "Nicht genug Münzen", coinsRequired: "Du brauchst {amount} Münzen zum Spielen", yourBalance: "Dein Guthaben:", youNeed: "Du brauchst:", watchAd: "Werbung ansehen", payWithGems: "Mit Edelsteinen bezahlen", dailyGift: "Tägliches Geschenk", getFreeCoins: "Kostenlose Münzen erhalten", myPowers: "Meine Kräfte", goToShop: "Zum Shop", levelUp: "Level Up! 🎉", levelLabel: "Level", rewards: "Belohnungen", coin: "Münze", gem: "Edelstein", xpBonus: "XP-Bonus", powers: "Kräfte", likedIt: "Hat es dir gefallen? 🎉", createAccountToContinue: "Erstelle ein Konto um weiterzuspielen!", levelCompleted: "Abgeschlossene Level", starsCollected: "Gesammelte Sterne", createUniqueAvatar: "Erstelle einen einzigartigen Avatar", saveProgressForever: "Fortschritt für immer speichern", unlockAllFeatures: "Alle Funktionen freischalten", excellentProgress: "Ausgezeichneter Fortschritt! 🎉", dontLoseAchievements: "Verliere nicht deine Erfolge - registriere dich kostenlos!", progressSavedForever: "Fortschritt wird für immer gespeichert", leaderboardParticipation: "Ranglisten-Teilnahme", registerFree: "Kostenlos registrieren", later: "Später", continueAsGuest: "Als Gast fortfahren", playsLimit: "Spiellimit", playsRemaining: "Verbleibend: {current}/{max} Spiele", watchAdGetPlays: "Schau Werbung und erhalte", extraPlays: "+{count} Spiele", watching: "Schaut...", watchingAd: "Schaut Werbung...", adFailed: "Werbung konnte nicht angezeigt werden", watchFailed: "Werbung konnte nicht angesehen werden", errorOccurred: "Ein Fehler ist aufgetreten", orBecomeVip: "oder werde VIP für unbegrenzte Spiele", continueGame: "Spiel fortsetzen", xpProgress: "XP-Fortschritt", maxLevelReached: "Du hast das maximale Level erreicht! 🎉", xpToNextLevel: "{amount} XP bis zum nächsten Level", totalXp: "Gesamt-XP", maximum: "Maximum", nextLevel: "Nächstes Level", levelRewards: "Level {level} Belohnungen", spinTickets: "Drehtickets" },
  settings: { ...en.settings, title: "Einstellungen", editName: "Name bearbeiten", changePassword: "Passwort ändern", language: "Sprache", currentPassword: "Aktuelles Passwort", newPassword: "Neues Passwort", confirmPassword: "Passwort bestätigen", passwordMismatch: "Passwörter stimmen nicht überein", passwordChanged: "Passwort geändert!", nameChanged: "Name geändert!" },
  dailyRewards: { ...en.dailyRewards, title: "Tägliche Belohnungen", subtitle: "Melde dich jeden Tag an für Belohnungen!", day: "Tag {day}", today: "Heute", claimed: "Eingelöst", claim: "Einlösen", claimNow: "Jetzt einlösen!", streak: "Serie", daysInRow: "{days} Tage in Folge", comeBackTomorrow: "Komm morgen wieder für mehr Belohnungen!", streakBonus: "Serienbonus!", coins: "Münze", gems: "Edelstein", xp: "XP", powerUp: "Kraft", keepItUp: "Weiter so!", amazing: "Erstaunlich!", congratulations: "Glückwunsch!" },
  missions: { ...en.missions, title: "Missionen", subtitle: "Schließe Missionen ab und erhalte Belohnungen!", daily: "Täglich", weekly: "Wöchentlich", achievements: "Erfolge", streak: "Serie", days: "Tage", claimReward: "Belohnung einlösen", claimed: "Eingelöst", received: "Erhalten!", noMissions: "Keine Missionen verfügbar", noWeeklyMissions: "Keine wöchentlichen Missionen", newIn: "Neue in", unlocked: "Freigeschaltet", achievementUnlocked: "Erfolg freigeschaltet!", streakBonus: "Serienbonus!", swipeHint: "← Wische um alle Tage zu sehen →" },
  shop: { ...en.shop, title: "Shop", starterPack: "Starterpaket", forBeginners: "Für Anfänger", megaPowers: "Mega-Kräfte", winMoreGames: "Gewinne mehr Spiele", vipStatus: "VIP-Status", vipBenefits: "2x XP + Boni", powers: "Kräfte", advantage: "Spielvorteil", frames: "Rahmen", uniqueProfile: "Einzigartiges Profil", coins: "Münzen", gems: "Edelsteine", withBonuses: "Mit Boni", buy: "Kaufen", buyFor: "Kaufen für {price}", exchange: "Tauschen", currencyExchange: "Währungstausch", exchangeDescription: "Tausche Münzen und Edelsteine", exchangeButton: "Tauschen", diamond: "Edelstein", coin: "Münze", notEnoughGems: "Nicht genug Edelsteine!", notEnoughCoins: "Nicht genug Münzen", purchaseFailed: "Kauf fehlgeschlagen", exchangeFailed: "Tausch fehlgeschlagen", loginRequired: "Anmeldung erforderlich!", purchaseSuccess: "Erfolgreich gekauft!", continue: "Fortfahren", balance: "Guthaben" },
  help: { ...en.help, title: "Hilfe", faq: "FAQ", faqSubtitle: "Antworten auf häufige Fragen", supportChat: "Support-Chat", supportSubtitle: "Kontaktiere uns direkt", email: "E-Mail", guide: "Anleitung", guideSubtitle: "Wie man spielt", howToUsePowers: "Wie benutzt man Kräfte?", learnEachPower: "Lerne jede Kraft kennen", howItWorks: "Wie funktioniert es?", createGame: "Spiel erstellen", createGameDesc: "Klicke auf '+ Spiel erstellen' und wähle eine Kategorie. Du erhältst einen eindeutigen Code.", shareCode: "Code teilen", shareCodeDesc: "Teile den Code mit deinem Freund und warte bis er dem Raum beitritt.", playWithFriends: "Mit Freunden spielen", playWithFriendsDesc: "Füge Freunde hinzu und starte ein Spiel durch Klicken auf ihre Karte.", winning: "Gewinnen", winningDesc: "Antworte schnell und richtig. Der Spieler mit den meisten Punkten gewinnt!" },
  legal: { ...en.legal, privacyPolicy: "Datenschutz", privacyPolicyFull: "Datenschutzrichtlinie", effectiveDate: "Gültig ab: Januar 2025", introduction: "Einführung", termsOfService: "AGB", termsOfServiceFull: "Allgemeine Geschäftsbedingungen", contact: "Kontakt", contactText: "Bei Fragen kontaktiere uns:" },
  tv: { ...en.tv, start: "Los geht's! 🚀", connectToTV: "Mit TV verbinden", scanningForDevices: "Suche nach TVs...", noDevicesFound: "Keine TVs gefunden", connect: "Verbinden", connecting: "Verbindung wird hergestellt...", connected: "Verbunden!", connectionFailed: "Verbindung fehlgeschlagen", startGame: "Spiel starten" },
  spin: { ...en.spin, title: "Glücksdrehung!", coins: "{amount} Münzen", gems: "{amount} Edelsteine", power: "Kraft", received: "Erhalten {item}! 🎉", youWon: "Du hast {item} gewonnen!", claimReward: "Belohnung einlösen", freeSpinsLeft: "{count} kostenlose Drehungen übrig", comeBackTomorrow: "Komm morgen für mehr Drehungen wieder!", loading: "Laden...", winChances: "Gewinnchancen", eachSegmentChance: "Jedes Segment hat die gleiche Chance:", allSegmentsEqual: "Alle Segmente haben die gleiche Chance (1/8)" },
  gameExtra: { prize: "Preis" },
  iap: { ...en.iap, pleaseSignIn: "Bitte anmelden", purchaseOnlyMobile: "Käufe nur in der mobilen App verfügbar", purchaseComplete: "Kauf abgeschlossen! 🎉", purchaseFailed: "Kauf fehlgeschlagen", purchasesRestored: "Käufe wiederhergestellt! 🎉", noPreviousPurchases: "Keine vorherigen Käufe gefunden", restoreFailed: "Wiederherstellung fehlgeschlagen" },
  featured: { starterPack: "Starterpaket", starterPackDesc: "2x Alle Kräfte • 200 Münzen • Perfekt für Anfänger", megaPowers: "Mega-Kräfte", megaPowersDesc: "5x Alle Kräfte • Für Top-Spieler", vipWeek: "VIP Woche", vipWeekDesc: "2x XP • Unbegrenzte Drehungen • Exklusive Rahmen", coinsDesc: "1500 Münzen • +20% Bonus", badgeNew: "Neu", badgePopular: "Beliebt", badgeBestPrice: "Bester Preis", badgeBestValue: "Bester Wert" },
};
