/**
 * Party categories: multiplayer-only categories whose questions are not
 * trivia. The first (and so far only) one is "Most Likely To" — every player
 * votes for a player in the room, and the most-voted player becomes the
 * question's correct answer. Majority voters score; there is no fixed
 * correct answer, so these categories cannot be played solo, against the
 * clock on TV, or in mixed pools.
 *
 * Their question rows are shaped to enforce that: correct_answer is the
 * '__vote__' sentinel and incorrect_answers is empty, which every generic
 * selection pipeline rejects (isValidQuestionLength wants 3+ incorrect
 * answers). Only the dedicated vote path in MultiplayerContextV2 serves
 * them, substituting the room's player names as the answers.
 *
 * Seeded by supabase/migrations/20260916100000_most_likely_to.sql
 * (generated by scripts/most-likely-to/build-migration.py).
 */

export const MOST_LIKELY_CATEGORY_ID = "most_likely_to";

/**
 * What a vote prompt carries in correct_answer — in the questions bank AND
 * in every room_questions row of a vote round. It is how any device
 * (initiator or synced) recognises a vote round without resolving the
 * category, and the database-side settlement function only ever settles
 * questions carrying it.
 */
export const MOST_LIKELY_VOTE_SENTINEL = "__vote__";

/**
 * Flat payout for voting with the majority. Settled server-side by
 * settle_most_likely_votes — the literal 100 in the migration and this
 * constant are pinned together by partyCategories.test.ts. Deliberately
 * below MAX_QUESTION_POINTS (275) so the vote payout never dwarfs a trivia
 * question.
 */
export const MOST_LIKELY_POINTS = 100;

/** The design calls for 10 prompts per party round (bank of 36). */
export const MOST_LIKELY_QUESTIONS_PER_ROUND = 10;

/** Multiplayer-only categories, kept out of solo surfaces (Discover, levels). */
export const PARTY_CATEGORY_IDS: readonly string[] = [MOST_LIKELY_CATEGORY_ID];

export function isPartyCategory(slug: string | null | undefined): boolean {
  return !!slug && PARTY_CATEGORY_IDS.includes(slug);
}

/** Drop party categories from a category list meant for solo play. */
export function excludePartyCategories<T extends { category_id?: string | null; id?: string | null }>(
  rows: T[],
): T[] {
  return rows.filter((r) => !isPartyCategory(r.category_id || r.id));
}

/**
 * Move party categories to the front of a category list, keeping the rest in
 * their arriving order. This is how the room pickers put "Most Likely To" at
 * the top: it is the categories every room can actually play together, so it
 * leads the wall rather than sitting at sort_order's mercy. Handles both row
 * shapes (Discover's slug-as-id, the pickers' uuid-plus-category_id).
 */
export function pinPartyCategoriesFirst<T extends { category_id?: string | null; id?: string | null }>(
  rows: T[],
): T[] {
  const party = rows.filter((r) => isPartyCategory(r.category_id || r.id));
  if (party.length === 0) return rows;
  return [...party, ...rows.filter((r) => !isPartyCategory(r.category_id || r.id))];
}

/**
 * The answer options of a vote round: the players' display names, one per
 * participant, in join order. The round initiator builds this once and it
 * rides in room_questions.shuffled_answers, so every device shows the same
 * list in the same order.
 *
 * Names must be unique — the vote IS the name string, and two players both
 * called "John" would merge their votes — so duplicates get a numeric
 * suffix. Order and suffixes are assigned by join order, which is stable.
 */
export function mostLikelyAnswerOptions(
  participants: Array<{ user_id: string; nickname: string }>,
  excludeUserId?: string | null,
): string[] {
  const seen = new Map<string, number>();
  const names: string[] = [];
  for (const p of participants) {
    if (excludeUserId && p.user_id === excludeUserId) continue;
    const base = (p.nickname || "Player").trim() || "Player";
    const taken = seen.get(base.toLowerCase()) || 0;
    seen.set(base.toLowerCase(), taken + 1);
    names.push(taken === 0 ? base : `${base} (${taken + 1})`);
  }
  return names;
}
