// Centralized video configuration for preloading and display
// IMPORTANT: No cache-busting query params - Service Worker handles versioning

// Map/Adventure videos
export const MAP_VIDEOS = {
  default: "/videos/floating-blob.webm",
  videoB: "/videos/map-video-b.webm",
  videoC: "/videos/map-video-c.webm",
};

// Category card background videos
// Note: Removed ?v=X params - SW cache handles versioning via CACHE_NAME
export const CATEGORY_VIDEOS: Record<string, string> = {
  art: "/videos/art.webm",
  georgian_history: "/videos/geo-history.webm",
  sports: "/videos/sport-final.webm",
  space: "/videos/galaxy.webm",
  georgian_literature: "/videos/literature.webm",
  psychology: "/videos/psyc.webm",
  geography: "/videos/geography.webm",
  science: "/videos/science.webm",
  archaeology: "/videos/archeology.webm",
  fun_facts: "/videos/funny-facts.webm",
  world_history: "/videos/world-history.webm",
  animals: "/videos/animals.webm",
  anime: "/videos/anime.webm",
  anime_manga: "/videos/anime.webm",
  architecture: "/videos/architecture.webm",
  economics: "/videos/economics.webm",
  fashion: "/videos/fashion.webm",
  math: "/videos/mathematics.webm",
  mathematics: "/videos/mathematics.webm",
  military_history: "/videos/military-history.webm",
  movies: "/videos/movies.webm",
  music: "/videos/music.webm",
  tv_shows: "/videos/tvshows.webm",
  tv_series: "/videos/tvshows.webm",
  biology: "/videos/biology.webm",
  memes: "/videos/memes.webm",
  memes_internet: "/videos/memes.webm",
  technology: "/videos/modern-technologies.webm",
  modern_technologies: "/videos/modern-technologies.webm",
  myths_or_reality: "/videos/myths-or-reality.webm",
  myths_reality: "/videos/myths-or-reality.webm",
  paparazzi: "/videos/paparazzi.webm",
  celebrities: "/videos/paparazzi.webm",
  astronomy: "/videos/astrology.webm",
  chemistry: "/videos/chemistry.webm",
  medicine: "/videos/medicine.webm",
  robotics_ai: "/videos/robotics-ai.webm",
  social_media: "/videos/social-media.webm",
  coding: "/videos/coding.webm",
  programming: "/videos/coding.webm",
  ecology: "/videos/ecology.webm",
  nature: "/videos/nature.webm",
  religion: "/videos/religion.webm",
  religion_mythology: "/videos/religion.webm",
  philosophy: "/videos/philosophy.webm",
  physics: "/videos/physics.webm",
  politics: "/videos/politics.webm",
  pop_culture: "/videos/pop-culture.webm",
  pop_culture_trends: "/videos/pop-culture.webm",
  video_games: "/videos/video-games.webm",
  gaming: "/videos/video-games.webm",
  world_cuisine: "/videos/world-cuisine.webm",
  food: "/videos/world-cuisine.webm",
  georgian_cuisine: "/videos/georgian-cuisine.webm",
  georgian_culture: "/videos/georgian-culture.webm",
  geology: "/videos/geology.webm",
  languages: "/videos/languages.webm",
  linguistics: "/videos/languages.webm",
};

// Category card first-frame images for instant loading during animations
export const CATEGORY_IMAGES: Record<string, string> = {
  art: "/images/categories/art.jpg",
  georgian_history: "/images/categories/geo-history.jpg",
  sports: "/images/categories/sport.jpg",
  space: "/images/categories/galaxy.jpg",
  georgian_literature: "/images/categories/literature.jpg",
  psychology: "/images/categories/psyc.jpg",
  geography: "/images/categories/geography.jpg",
  science: "/images/categories/science.jpg",
  archaeology: "/images/categories/archeology.jpg",
  fun_facts: "/images/categories/funny-facts.jpg",
  world_history: "/images/categories/world-history.jpg",
  animals: "/images/categories/animals.jpg",
  anime: "/images/categories/anime.jpg",
  anime_manga: "/images/categories/anime.jpg",
  architecture: "/images/categories/architecture.jpg",
  economics: "/images/categories/economics.jpg",
  fashion: "/images/categories/fashion.jpg",
  math: "/images/categories/mathematics.jpg",
  mathematics: "/images/categories/mathematics.jpg",
  military_history: "/images/categories/military-history.jpg",
  movies: "/images/categories/movies.jpg",
  music: "/images/categories/music.jpg",
  tv_shows: "/images/categories/tvshows.jpg",
  tv_series: "/images/categories/tvshows.jpg",
  biology: "/images/categories/biology.jpg",
  memes: "/images/categories/memes.jpg",
  memes_internet: "/images/categories/memes.jpg",
  technology: "/images/categories/modern-technologies.jpg",
  modern_technologies: "/images/categories/modern-technologies.jpg",
  myths_or_reality: "/images/categories/myths-or-reality.jpg",
  myths_reality: "/images/categories/myths-or-reality.jpg",
  paparazzi: "/images/categories/paparazzi.jpg",
  celebrities: "/images/categories/paparazzi.jpg",
  astronomy: "/images/categories/astrology.jpg",
  chemistry: "/images/categories/chemistry.jpg",
  medicine: "/images/categories/medicine.jpg",
  robotics_ai: "/images/categories/robotics-ai.jpg",
  social_media: "/images/categories/social-media.jpg",
  coding: "/images/categories/coding.jpg",
  programming: "/images/categories/coding.jpg",
  ecology: "/images/categories/ecology.jpg",
  nature: "/images/categories/nature.jpg",
  religion: "/images/categories/religion.jpg",
  religion_mythology: "/images/categories/religion.jpg",
  philosophy: "/images/categories/philosophy.jpg",
  physics: "/images/categories/physics.jpg",
  politics: "/images/categories/politics.jpg",
  pop_culture: "/images/categories/pop-culture.jpg",
  pop_culture_trends: "/images/categories/pop-culture.jpg",
  video_games: "/images/categories/video-games.jpg",
  gaming: "/images/categories/video-games.jpg",
  world_cuisine: "/images/categories/world-cuisine.jpg",
  food: "/images/categories/world-cuisine.jpg",
  georgian_cuisine: "/images/categories/georgian-cuisine.jpg",
  georgian_culture: "/images/categories/georgian-culture.jpg",
  geology: "/images/categories/geology.jpg",
  languages: "/images/categories/languages.jpg",
  linguistics: "/images/categories/languages.jpg",
};

// Get all video URLs for preloading (deduplicated)
export function getAllVideoUrls(): string[] {
  const allUrls = [
    ...Object.values(MAP_VIDEOS),
    ...Object.values(CATEGORY_VIDEOS),
  ];
  // Deduplicate
  return [...new Set(allUrls)];
}

// Get category image URL for instant display while video loads
export function getCategoryImageUrl(categoryId: string): string | null {
  return CATEGORY_IMAGES[categoryId] || null;
}
