/**
 * The names a battle's sides are dealt at creation.
 *
 * "Team A" told nobody anything, so the randomizer names the sides the way
 * it names rooms — from local pools, in the app's language, no round-trip.
 * The owner's rule: names are PLURAL, a crowd — პინგვინები, მებრძოლთა
 * გუნდი, არწივთა კლანი — never a single mascot. The captain renames from
 * the crest picker afterwards (tb_set_team_name, captain-only).
 */

const POOLS: Record<string, readonly string[]> = {
  ka: [
    "პინგვინები",
    "არწივთა კლანი",
    "მებრძოლთა გუნდი",
    "ვეფხვები",
    "მგლების ხროვა",
    "დათვები",
    "ფლამინგოები",
    "დელფინები",
    "ლომთა რაზმი",
    "მელიები",
    "ზვიგენები",
    "ბუების საბჭო",
    "რაინდები",
    "ვიკინგები",
    "ფარაონები",
    "ასტრონავტები",
    "პირატები",
    "ჯადოქრები",
    "გლადიატორები",
    "კომეტები",
  ],
  en: [
    "The Penguins",
    "Eagle Clan",
    "The Warriors",
    "The Tigers",
    "Wolf Pack",
    "The Bears",
    "The Flamingos",
    "The Dolphins",
    "Lion Squad",
    "The Foxes",
    "The Sharks",
    "Owl Council",
    "The Knights",
    "The Vikings",
    "The Pharaohs",
    "The Astronauts",
    "The Pirates",
    "The Wizards",
    "The Gladiators",
    "The Comets",
  ],
  es: [
    "Los Pingüinos",
    "Clan del Águila",
    "Los Guerreros",
    "Los Tigres",
    "La Manada de Lobos",
    "Los Osos",
    "Los Flamencos",
    "Los Delfines",
    "Escuadrón León",
    "Los Zorros",
    "Los Tiburones",
    "Consejo de Búhos",
    "Los Caballeros",
    "Los Vikingos",
    "Los Faraones",
    "Los Astronautas",
    "Los Piratas",
    "Los Magos",
    "Los Gladiadores",
    "Los Cometas",
  ],
  fr: [
    "Les Pingouins",
    "Clan des Aigles",
    "Les Guerriers",
    "Les Tigres",
    "La Meute de Loups",
    "Les Ours",
    "Les Flamants",
    "Les Dauphins",
    "Escouade Lion",
    "Les Renards",
    "Les Requins",
    "Conseil des Hiboux",
    "Les Chevaliers",
    "Les Vikings",
    "Les Pharaons",
    "Les Astronautes",
    "Les Pirates",
    "Les Sorciers",
    "Les Gladiateurs",
    "Les Comètes",
  ],
  de: [
    "Die Pinguine",
    "Adler-Clan",
    "Die Krieger",
    "Die Tiger",
    "Das Wolfsrudel",
    "Die Bären",
    "Die Flamingos",
    "Die Delfine",
    "Löwen-Trupp",
    "Die Füchse",
    "Die Haie",
    "Der Eulenrat",
    "Die Ritter",
    "Die Wikinger",
    "Die Pharaonen",
    "Die Astronauten",
    "Die Piraten",
    "Die Zauberer",
    "Die Gladiatoren",
    "Die Kometen",
  ],
  it: [
    "I Pinguini",
    "Clan delle Aquile",
    "I Guerrieri",
    "Le Tigri",
    "Il Branco di Lupi",
    "Gli Orsi",
    "I Fenicotteri",
    "I Delfini",
    "Squadra Leone",
    "Le Volpi",
    "Gli Squali",
    "Il Consiglio dei Gufi",
    "I Cavalieri",
    "I Vichinghi",
    "I Faraoni",
    "Gli Astronauti",
    "I Pirati",
    "I Maghi",
    "I Gladiatori",
    "Le Comete",
  ],
  pt: [
    "Os Pinguins",
    "Clã das Águias",
    "Os Guerreiros",
    "Os Tigres",
    "A Alcateia",
    "Os Ursos",
    "Os Flamingos",
    "Os Golfinhos",
    "Esquadrão Leão",
    "As Raposas",
    "Os Tubarões",
    "Conselho das Corujas",
    "Os Cavaleiros",
    "Os Vikings",
    "Os Faraós",
    "Os Astronautas",
    "Os Piratas",
    "Os Magos",
    "Os Gladiadores",
    "Os Cometas",
  ],
};

/** Two DISTINCT names for the two sides, in the given app language. */
export function dealTeamNames(language: string): { a: string; b: string } {
  const pool = POOLS[language] ?? POOLS.ka;
  const first = Math.floor(Math.random() * pool.length);
  let second = Math.floor(Math.random() * pool.length);
  if (second === first) second = (second + 1) % pool.length;
  return { a: pool[first], b: pool[second] };
}
