#!/usr/bin/env python3
"""Turn resolved.json into the migration that inserts the questions.

Run:  set -a && . ./.env && set +a && python3 scripts/image-questions-ka/build-migration.py

Ids are uuid5 of the question's own key, not gen_random_uuid(), so the file can
be applied twice without inserting the bank twice — the INSERT carries
ON CONFLICT (id) DO NOTHING. Re-running the generator produces the same ids.

Checked against the live bank before anything is written:
  * the category exists and is the Georgian one
  * no live Georgian question already uses the image
  * no live Georgian question already asks this stem with this answer
  * the 70/20 gameplay limits, again, on the final text
"""

import json
import os
import pathlib
import re
import sys
import urllib.request
import uuid

HERE = pathlib.Path(__file__).parent
OUT = HERE.parent.parent / "supabase" / "migrations" / "20260818120000_image_questions_ka.sql"
RESOLVED = HERE / "resolved.json"

MAX_QUESTION = 70
MAX_ANSWER = 20
LEVEL = 1  # every image question in the bank sits at level 1

# Stable namespace for this batch; changing it re-mints every id.
NS = uuid.uuid5(uuid.NAMESPACE_URL, "flutter-native-play/image-questions-ka")

SUPABASE_URL = os.environ.get("VITE_SUPABASE_URL")
SUPABASE_KEY = os.environ.get("VITE_SUPABASE_PUBLISHABLE_KEY")
if not SUPABASE_URL or not SUPABASE_KEY:
    sys.exit(
        "Missing VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY.\n"
        "  set -a && . ./.env && set +a && python3 scripts/image-questions-ka/build-migration.py"
    )


def get(path):
    req = urllib.request.Request(
        f"{SUPABASE_URL}/rest/v1/{path}",
        headers={"apikey": SUPABASE_KEY, "Authorization": f"Bearer {SUPABASE_KEY}"},
    )
    with urllib.request.urlopen(req) as resp:
        return json.load(resp)


def all_questions():
    rows, page = [], 1000
    for offset in range(0, 20000, page):
        batch = get(
            "questions?select=id,question_text,correct_answer,image_url"
            f"&language=eq.ka&order=id&offset={offset}&limit={page}"
        )
        rows.extend(batch)
        if len(batch) < page:
            break
    return rows


categories = {c["category_id"]: c for c in get("categories?select=id,category_id,name&language=eq.ka")}
live = all_questions()
live_images = {q["image_url"] for q in live if q["image_url"]}


def norm(s):
    return re.sub(r"\s+", " ", s.strip().lower())


live_pairs = {(norm(q["question_text"]), norm(q["correct_answer"])) for q in live}

spec = json.loads(RESOLVED.read_text())
print(f"{len(spec)} questions · {len(live)} live Georgian questions to check against")

rows = []
problems = []
seen_ids = set()
for q in spec:
    where = f"{q['cat']}/{q['answer']}"
    cat = categories.get(q["cat"])
    if not cat:
        problems.append(f"{where}: no Georgian category {q['cat']}")
        continue
    options = [q["answer"]] + q["wrong"]
    if len(q["stem"]) > MAX_QUESTION:
        problems.append(f"{where}: stem {len(q['stem'])} chars")
    for o in options:
        if len(o) > MAX_ANSWER:
            problems.append(f"{where}: option {len(o)} chars: {o}")
    if len({norm(o) for o in options}) != 4:
        problems.append(f"{where}: repeats an option")
    if q["image_url"] in live_images:
        problems.append(f"{where}: image already used by a live question")
    if (norm(q["stem"]), norm(q["answer"])) in live_pairs:
        problems.append(f"{where}: a live question already asks this with this answer")

    qid = str(uuid.uuid5(NS, f"{q['cat']}/{q['wiki']}/{q['answer']}"))
    if qid in seen_ids:
        problems.append(f"{where}: id collision — two questions share cat/wiki/answer")
    seen_ids.add(qid)
    rows.append({**q, "id": qid, "category_uuid": cat["id"], "category_name": cat["name"]})

if problems:
    print("\nNot writing the migration:")
    for p in problems:
        print("  " + p)
    sys.exit(1)

from collections import Counter  # noqa: E402 — only needed for the summary

by_cat = Counter(r["category_name"] for r in rows)
print("\nby category:")
for name, n in by_cat.most_common():
    print(f"  {n:3d}  {name}")


def q(s):
    return "'" + str(s).replace("'", "''") + "'"


def jsonb(values):
    return q(json.dumps(list(values), ensure_ascii=False)) + "::jsonb"


lines = [
    "-- 100 Georgian image questions.",
    "--",
    "-- Generated by scripts/image-questions-ka/build-migration.py from",
    "-- resolved.json beside it. Regenerate rather than editing this by hand.",
    "--",
    "-- An image question hides its own text while it is being played —",
    "-- QuizGameScreenProd passes hideQuestionText={!!currentQuestion.imageUrl} —",
    "-- so each of these is answerable from the picture alone: a photograph of one",
    "-- animal, one flag, one building, one dish, against three options that are",
    "-- not it. The stem is what the card falls back to if the image fails to load.",
    "--",
    "-- Every picture is the lead image of a Wikipedia article, served from",
    "-- upload.wikimedia.org exactly as the 435 image questions already in the bank",
    "-- are, and every one was looked at before it was accepted: taxobox collages,",
    "-- botanical plates and satellite views were replaced with single photographs.",
    "--",
    f"-- Text is inside the limits gameplay enforces ({MAX_QUESTION} chars of question,",
    f"-- {MAX_ANSWER} per option, src/constants/questionQuality.ts). Past either,",
    "-- isValidQuestionLength drops the question and the row would never be served.",
    "--",
    "-- Ids are uuid5 of the question's own key, so applying this twice inserts",
    "-- nothing the second time.",
    "",
    "BEGIN;",
    "",
    "INSERT INTO public.questions (",
    "  id, category_id, language, question_text, correct_answer, incorrect_answers,",
    "  image_url, difficulty, level_number, is_active, in_production",
    ") VALUES",
]

values = []
current_cat = None
for r in sorted(rows, key=lambda r: (r["cat"], r["answer"])):
    if r["cat"] != current_cat:
        current_cat = r["cat"]
        values.append(f"-- {r['category_name']}")
    values.append(
        f"  ({q(r['id'])}, {q(r['category_uuid'])}, 'ka', {q(r['stem'])}, "
        f"{q(r['answer'])}, {jsonb(r['wrong'])}, {q(r['image_url'])}, "
        f"{q(r['difficulty'])}, {LEVEL}, true, true)"
    )

# comma-separate the value rows, leaving the category comments alone
value_lines = []
value_rows = [i for i, v in enumerate(values) if not v.startswith("--")]
for i, v in enumerate(values):
    if v.startswith("--"):
        value_lines.append(v)
    else:
        value_lines.append(v + ("," if i != value_rows[-1] else ""))

lines += value_lines
lines += [
    "ON CONFLICT (id) DO NOTHING;",
    "",
    "COMMIT;",
    "",
    f"-- {len(rows)} image questions inserted, active and in production.",
    "",
]

OUT.write_text("\n".join(lines))
print(f"\nwrote {OUT.relative_to(HERE.parent.parent)} ({len(lines)} lines)")
