-- "Most Likely To" — a party category where players vote for a player and
-- the most-voted player is the correct answer (majority scoring).
--
-- Generated by scripts/most-likely-to/build-migration.py.
-- Regenerate rather than editing by hand. Idempotent: uuid5 ids and
-- ON CONFLICT DO NOTHING throughout.
--
-- The prompt rows carry correct_answer '__vote__' and NO incorrect answers,
-- which every generic selection pipeline rejects (fewer than 3 incorrect
-- answers) — so they cannot leak into solo levels, TV rounds or mixed
-- pools. Only the dedicated multiplayer vote path serves them, with the
-- room's player names as the answers.

BEGIN;

-- ══ most_likely_to ══
INSERT INTO public.categories (id, category_id, name, description, icon, icon_slug, color, type, is_active, total_levels, sort_order, language, is_language_specific)
VALUES ('b7cdb122-2175-5434-9f5f-756cf7e215c8', 'most_likely_to', 'ვინ არის ყველაზე?', 'მიეცი ხმა მოთამაშეს, რომელიც ყველაზე მეტად შეესაბამება — უმრავლესობის პასუხი იმარჯვებს!', '🗳️', 'group-of-people', 'from-fuchsia-400 to-pink-500', 'fun', true, 1, 8, 'ka', false)
ON CONFLICT (category_id) DO NOTHING;
INSERT INTO public.category_translations (category_id, language, name, description) VALUES
  ('b7cdb122-2175-5434-9f5f-756cf7e215c8', 'en', 'Most Likely To', 'Vote for the player who fits best — the most-voted answer wins!'),
  ('b7cdb122-2175-5434-9f5f-756cf7e215c8', 'ka', 'ვინ არის ყველაზე?', 'მიეცი ხმა მოთამაშეს, რომელიც ყველაზე მეტად შეესაბამება — უმრავლესობის პასუხი იმარჯვებს!'),
  ('b7cdb122-2175-5434-9f5f-756cf7e215c8', 'de', 'Wer von uns?', 'Stimme für den Spieler, der am besten passt — die meistgewählte Antwort gewinnt!'),
  ('b7cdb122-2175-5434-9f5f-756cf7e215c8', 'es', '¿Quién de nosotros?', 'Vota por el jugador que mejor encaje: ¡gana la respuesta más votada!'),
  ('b7cdb122-2175-5434-9f5f-756cf7e215c8', 'fr', 'Qui de nous ?', 'Vote pour le joueur qui correspond le mieux — la réponse la plus votée gagne !'),
  ('b7cdb122-2175-5434-9f5f-756cf7e215c8', 'it', 'Chi di noi?', 'Vota il giocatore più adatto: vince la risposta più votata!'),
  ('b7cdb122-2175-5434-9f5f-756cf7e215c8', 'pt', 'Quem de nós?', 'Vote no jogador que mais combina — a resposta mais votada vence!')
ON CONFLICT (category_id, language) DO NOTHING;

-- ── the prompt bank: 36 prompts x 7 languages ─────────────────────────────
INSERT INTO public.questions (
  id, category_id, language, question_text, correct_answer, incorrect_answers,
  difficulty, level_number, is_active, in_production, translated_from
) VALUES
  ('197a3a14-b938-5689-847e-37975b41925a', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'en', 'Who wakes up the earliest?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, NULL),
  ('100a60f0-faee-5355-97d7-bfbf7f89b28c', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'ka', 'ვინ იღვიძებს ყველაზე ადრე?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '197a3a14-b938-5689-847e-37975b41925a'),
  ('b5c7b238-c3a3-5897-af15-fa3af218def8', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'de', 'Wer wacht am frühesten auf?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '197a3a14-b938-5689-847e-37975b41925a'),
  ('c9e9168b-affb-5421-8b11-adf052564693', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'es', '¿Quién se despierta más temprano?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '197a3a14-b938-5689-847e-37975b41925a'),
  ('74d59d90-c43f-5048-b7d0-8148e8008cfb', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'fr', 'Qui se réveille le plus tôt ?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '197a3a14-b938-5689-847e-37975b41925a'),
  ('189a8b71-b309-5095-8b5e-10e06152e9a8', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'it', 'Chi si sveglia più presto?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '197a3a14-b938-5689-847e-37975b41925a'),
  ('4dec2188-1872-5d25-ae4b-1eb70ce7af42', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'pt', 'Quem acorda mais cedo?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '197a3a14-b938-5689-847e-37975b41925a'),
  ('99466797-0aae-577b-8f96-c31a85691fa9', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'en', 'Who goes to bed the latest?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, NULL),
  ('fc8c00e5-d7de-543c-9bf2-1c48fb9d0bf8', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'ka', 'ვინ იძინებს ყველაზე გვიან?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '99466797-0aae-577b-8f96-c31a85691fa9'),
  ('09a21119-bb5c-5fb8-b1c7-c436e3dadeec', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'de', 'Wer geht am spätesten ins Bett?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '99466797-0aae-577b-8f96-c31a85691fa9'),
  ('c840b5ed-dc71-5fce-9187-bad3cd2fc984', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'es', '¿Quién se acuesta más tarde?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '99466797-0aae-577b-8f96-c31a85691fa9'),
  ('7a8086bf-aaee-53b0-801f-02060f9ca181', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'fr', 'Qui se couche le plus tard ?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '99466797-0aae-577b-8f96-c31a85691fa9'),
  ('43db98f5-6a81-537a-93e8-20d497f069e0', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'it', 'Chi va a letto più tardi?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '99466797-0aae-577b-8f96-c31a85691fa9'),
  ('ac1f3667-cffb-5207-9772-76a0e13aa6d7', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'pt', 'Quem vai dormir mais tarde?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '99466797-0aae-577b-8f96-c31a85691fa9'),
  ('b231df74-5aff-5696-8d89-6cf103be8a56', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'en', 'Who is late most often?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, NULL),
  ('cd6b5b40-c591-5d5a-a52f-563c10169ed8', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'ka', 'ვინ აგვიანებს ყველაზე ხშირად?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'b231df74-5aff-5696-8d89-6cf103be8a56'),
  ('26a57333-ec9b-5caf-a55b-9e2721119fd5', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'de', 'Wer kommt am häufigsten zu spät?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'b231df74-5aff-5696-8d89-6cf103be8a56'),
  ('78f99e57-3f3d-5c94-959b-d255dd074727', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'es', '¿Quién llega tarde más a menudo?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'b231df74-5aff-5696-8d89-6cf103be8a56'),
  ('309512c0-2da5-5d28-90e4-2eac62a103ca', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'fr', 'Qui est le plus souvent en retard ?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'b231df74-5aff-5696-8d89-6cf103be8a56'),
  ('63918cc6-6513-5b4f-ad0e-d2015a596d20', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'it', 'Chi è in ritardo più spesso?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'b231df74-5aff-5696-8d89-6cf103be8a56'),
  ('d08b764d-3bdd-593e-bdfb-8c0139c8c9ab', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'pt', 'Quem se atrasa com mais frequência?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'b231df74-5aff-5696-8d89-6cf103be8a56'),
  ('fe01455f-05e8-5765-b3ff-8c027b8fa532', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'en', 'Who drinks the most coffee?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, NULL),
  ('f8a7f763-c4f3-5e75-9ae8-e88904dedef6', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'ka', 'ვინ სვამს ყველაზე მეტ ყავას?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'fe01455f-05e8-5765-b3ff-8c027b8fa532'),
  ('57c04b73-c9d8-5823-af52-405f7f999804', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'de', 'Wer trinkt den meisten Kaffee?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'fe01455f-05e8-5765-b3ff-8c027b8fa532'),
  ('e80bb3b0-8d44-5c40-aa50-3d40586ef728', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'es', '¿Quién toma más café?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'fe01455f-05e8-5765-b3ff-8c027b8fa532'),
  ('f9c706f3-89c6-5e7e-b83f-3c7809439d2e', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'fr', 'Qui boit le plus de café ?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'fe01455f-05e8-5765-b3ff-8c027b8fa532'),
  ('87d4c3ff-1269-5dee-ac12-4b0fd1b2f882', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'it', 'Chi beve più caffè?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'fe01455f-05e8-5765-b3ff-8c027b8fa532'),
  ('74bd01f5-4c91-531e-9d07-53aaf22aaf38', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'pt', 'Quem bebe mais café?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'fe01455f-05e8-5765-b3ff-8c027b8fa532'),
  ('f372e4fc-853d-522d-a24d-f09ceb179518', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'en', 'Who spends the most time on their phone?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, NULL),
  ('a27683b9-fe6d-5cba-aeb7-81c67546f684', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'ka', 'ვინ ატარებს ყველაზე მეტ დროს ტელეფონზე?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'f372e4fc-853d-522d-a24d-f09ceb179518'),
  ('8d822744-ff70-5c20-bb12-31dfe1537b29', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'de', 'Wer verbringt die meiste Zeit am Handy?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'f372e4fc-853d-522d-a24d-f09ceb179518'),
  ('943e418b-f19e-50c5-bb54-2afe1e2d0720', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'es', '¿Quién pasa más tiempo con el móvil?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'f372e4fc-853d-522d-a24d-f09ceb179518'),
  ('7c1f9a19-6d06-54a0-b678-55d9721477f3', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'fr', 'Qui passe le plus de temps sur son téléphone ?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'f372e4fc-853d-522d-a24d-f09ceb179518'),
  ('ebb0c440-2c03-50ea-8efa-58fe92a4df10', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'it', 'Chi passa più tempo al telefono?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'f372e4fc-853d-522d-a24d-f09ceb179518'),
  ('580d5de7-3215-54d4-bb8d-e29f1e03919c', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'pt', 'Quem passa mais tempo no telefone?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'f372e4fc-853d-522d-a24d-f09ceb179518'),
  ('7ae8f712-559a-53ef-9012-cc2cbcb7d57e', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'en', 'Who always forgets their keys?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, NULL),
  ('9f647ba3-4e65-54f4-ac3e-f705191c1242', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'ka', 'ვინ ივიწყებს ხოლმე გასაღებებს?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '7ae8f712-559a-53ef-9012-cc2cbcb7d57e'),
  ('59faf328-6c5a-5b72-b8df-a4d9fa18815e', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'de', 'Wer vergisst ständig seine Schlüssel?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '7ae8f712-559a-53ef-9012-cc2cbcb7d57e'),
  ('c03cc087-6542-5cfe-b4b4-44c2d163d3cf', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'es', '¿Quién olvida siempre las llaves?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '7ae8f712-559a-53ef-9012-cc2cbcb7d57e'),
  ('81601235-9196-5af7-a6a4-384592ccc94e', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'fr', 'Qui oublie toujours ses clés ?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '7ae8f712-559a-53ef-9012-cc2cbcb7d57e'),
  ('77359323-8630-5ac6-8314-c0f80f23bce1', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'it', 'Chi dimentica sempre le chiavi?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '7ae8f712-559a-53ef-9012-cc2cbcb7d57e'),
  ('f0c75799-9e3e-58da-ad65-d426a63c0465', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'pt', 'Quem sempre esquece as chaves?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '7ae8f712-559a-53ef-9012-cc2cbcb7d57e'),
  ('5e882763-fc4c-5d6b-be77-ec1b5ac189a0', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'en', 'Who tidies up most often?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, NULL),
  ('c3b56dcc-bd45-5e06-8bc3-c2a473f49a10', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'ka', 'ვინ ალაგებს სახლში ყველაზე ხშირად?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '5e882763-fc4c-5d6b-be77-ec1b5ac189a0'),
  ('b67bf6c5-81e7-5a3c-8430-b4d61723af83', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'de', 'Wer räumt am häufigsten auf?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '5e882763-fc4c-5d6b-be77-ec1b5ac189a0'),
  ('9b24ab56-3fcd-5586-9190-c11e0195bc2c', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'es', '¿Quién ordena la casa más a menudo?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '5e882763-fc4c-5d6b-be77-ec1b5ac189a0'),
  ('38a08c5e-8edb-5fc1-a5d4-c6e2b6d6546e', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'fr', 'Qui range le plus souvent ?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '5e882763-fc4c-5d6b-be77-ec1b5ac189a0'),
  ('2219a9b7-3362-59be-ac90-090df3abe871', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'it', 'Chi mette in ordine più spesso?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '5e882763-fc4c-5d6b-be77-ec1b5ac189a0'),
  ('178369c1-43a9-55ab-b806-419a99db8631', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'pt', 'Quem arruma a casa com mais frequência?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '5e882763-fc4c-5d6b-be77-ec1b5ac189a0'),
  ('1513f54c-7bc8-547a-acd6-84b5d1851225', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'en', 'Who does the washing-up most often?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, NULL),
  ('52d10721-652f-58f8-8b71-885c19be1240', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'ka', 'ვინ რეცხავს ჭურჭელს ყველაზე ხშირად?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '1513f54c-7bc8-547a-acd6-84b5d1851225'),
  ('4f085186-6e7e-5754-a604-d9816a6ed842', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'de', 'Wer spült am häufigsten das Geschirr?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '1513f54c-7bc8-547a-acd6-84b5d1851225'),
  ('9f7f3925-7b46-585b-b4c9-05fa93c8de71', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'es', '¿Quién friega los platos más a menudo?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '1513f54c-7bc8-547a-acd6-84b5d1851225'),
  ('69cc3792-3da5-552c-a1b6-bd0053db9e31', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'fr', 'Qui fait le plus souvent la vaisselle ?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '1513f54c-7bc8-547a-acd6-84b5d1851225'),
  ('77fe3608-180d-567e-a635-0031b83ed5f1', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'it', 'Chi lava i piatti più spesso?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '1513f54c-7bc8-547a-acd6-84b5d1851225'),
  ('f8188b9f-9656-5c6b-aa61-a7e3e27331f8', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'pt', 'Quem lava a louça com mais frequência?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '1513f54c-7bc8-547a-acd6-84b5d1851225'),
  ('13d19575-fa9f-5fe7-8ece-b719ab1fa9da', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'en', 'Who is the tidiest?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, NULL),
  ('73357276-63f8-5b33-b4bb-bdf9889c0cb6', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'ka', 'ვინ არის ყველაზე მოწესრიგებული?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '13d19575-fa9f-5fe7-8ece-b719ab1fa9da'),
  ('01fa7ea5-bdf9-56eb-a773-b2dccede762b', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'de', 'Wer ist am ordentlichsten?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '13d19575-fa9f-5fe7-8ece-b719ab1fa9da'),
  ('cc50ab1a-62c0-541c-8ed8-c3bd552369ef', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'es', '¿Quién es el más ordenado?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '13d19575-fa9f-5fe7-8ece-b719ab1fa9da'),
  ('b35a67b8-876a-5e48-ab33-a057e3aacb71', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'fr', 'Qui est le plus ordonné ?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '13d19575-fa9f-5fe7-8ece-b719ab1fa9da'),
  ('3d6f85be-046e-5385-8aea-0b26d6b4c110', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'it', 'Chi è il più ordinato?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '13d19575-fa9f-5fe7-8ece-b719ab1fa9da'),
  ('b02e1533-9acc-5d1a-976d-9190c0ac7a8a', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'pt', 'Quem é o mais organizado?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '13d19575-fa9f-5fe7-8ece-b719ab1fa9da'),
  ('1e9cc3b0-1945-530d-b70e-f7cc45d9ff17', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'en', 'Who cooks the best food?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, NULL),
  ('92ad3374-d214-5788-aa88-d5de6bf1d73d', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'ka', 'ვინ ამზადებს ყველაზე გემრიელ საჭმელს?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '1e9cc3b0-1945-530d-b70e-f7cc45d9ff17'),
  ('6972f13d-74b6-58a7-ade9-8b2aa7405b5b', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'de', 'Wer kocht das leckerste Essen?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '1e9cc3b0-1945-530d-b70e-f7cc45d9ff17'),
  ('ef95ebb0-9e47-5f56-b381-cf128819b6ff', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'es', '¿Quién cocina la comida más rica?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '1e9cc3b0-1945-530d-b70e-f7cc45d9ff17'),
  ('a88cccfa-71ac-5996-b692-09e7dabc08c7', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'fr', 'Qui cuisine les meilleurs plats ?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '1e9cc3b0-1945-530d-b70e-f7cc45d9ff17'),
  ('ffc00623-8985-5f76-93e7-9b320b88d505', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'it', 'Chi cucina i piatti più buoni?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '1e9cc3b0-1945-530d-b70e-f7cc45d9ff17'),
  ('d400b565-cdbd-5a72-9af2-3455d771b4e3', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'pt', 'Quem cozinha a comida mais gostosa?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '1e9cc3b0-1945-530d-b70e-f7cc45d9ff17'),
  ('00caa2b6-a51d-5a0c-9fe6-76024f37d77a', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'en', 'Who loves sweets the most?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, NULL),
  ('514ef174-cce3-57ad-a46a-d73a3d7ced53', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'ka', 'ვის უყვარს ყველაზე მეტად ტკბილეული?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '00caa2b6-a51d-5a0c-9fe6-76024f37d77a'),
  ('59ead474-0e14-552d-9d91-9c38dd1ba833', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'de', 'Wer liebt Süßigkeiten am meisten?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '00caa2b6-a51d-5a0c-9fe6-76024f37d77a'),
  ('c91d9ebd-dbcc-52dc-84f6-2de46eddf1bf', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'es', '¿Quién ama más los dulces?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '00caa2b6-a51d-5a0c-9fe6-76024f37d77a'),
  ('91df0afc-ad0d-5723-b06c-f0fb5ca55cd1', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'fr', 'Qui aime le plus les sucreries ?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '00caa2b6-a51d-5a0c-9fe6-76024f37d77a'),
  ('76989171-806b-511d-9a33-2eee685cc8ed', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'it', 'Chi ama di più i dolci?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '00caa2b6-a51d-5a0c-9fe6-76024f37d77a'),
  ('3d7c027b-89b6-5524-ace7-9566d1faebfd', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'pt', 'Quem ama mais os doces?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '00caa2b6-a51d-5a0c-9fe6-76024f37d77a'),
  ('7cf5ef8c-8789-5d08-a4a1-e307b2b18ff3', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'en', 'Who eats the slowest?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, NULL),
  ('8d9cd56c-937a-5905-bcdf-b4d54a686cf1', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'ka', 'ვინ ჭამს ყველაზე ნელა?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '7cf5ef8c-8789-5d08-a4a1-e307b2b18ff3'),
  ('7a21b38f-b1a9-5afd-b5d8-72bdc807fbd9', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'de', 'Wer isst am langsamsten?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '7cf5ef8c-8789-5d08-a4a1-e307b2b18ff3'),
  ('43e71d4c-0dd1-5740-805f-a2a41b59ce5a', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'es', '¿Quién come más despacio?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '7cf5ef8c-8789-5d08-a4a1-e307b2b18ff3'),
  ('63beac27-34e9-5818-a946-7df852235bd8', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'fr', 'Qui mange le plus lentement ?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '7cf5ef8c-8789-5d08-a4a1-e307b2b18ff3'),
  ('c191327e-3cda-594b-94ef-98cb42d7c9cb', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'it', 'Chi mangia più lentamente?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '7cf5ef8c-8789-5d08-a4a1-e307b2b18ff3'),
  ('991b460a-de24-5c94-8c6e-cff2ae46cb3e', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'pt', 'Quem come mais devagar?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '7cf5ef8c-8789-5d08-a4a1-e307b2b18ff3'),
  ('c8d02807-ae9c-5988-bc21-a4b270474287', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'en', 'Who always picks the restaurant?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, NULL),
  ('26d9a40d-8d88-565e-9d90-2df958257f6b', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'ka', 'ვინ ირჩევს ხოლმე რესტორანს?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'c8d02807-ae9c-5988-bc21-a4b270474287'),
  ('d89e5e1c-331a-5d51-938d-3c61c86e44f5', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'de', 'Wer sucht immer das Restaurant aus?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'c8d02807-ae9c-5988-bc21-a4b270474287'),
  ('a2301948-a865-553f-ac60-17c3a93c9d26', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'es', '¿Quién elige siempre el restaurante?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'c8d02807-ae9c-5988-bc21-a4b270474287'),
  ('4ea22916-5d20-50ab-a7c0-2d1ed83e454f', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'fr', 'Qui choisit toujours le restaurant ?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'c8d02807-ae9c-5988-bc21-a4b270474287'),
  ('38d39f9f-f1be-51cb-992c-b422438adc87', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'it', 'Chi sceglie sempre il ristorante?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'c8d02807-ae9c-5988-bc21-a4b270474287'),
  ('be70e2ac-7f00-5800-9ba3-0f66e925894a', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'pt', 'Quem sempre escolhe o restaurante?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'c8d02807-ae9c-5988-bc21-a4b270474287'),
  ('ee541083-b56d-5f68-9f77-374eea548c5c', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'en', 'Who bakes the best cake?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, NULL),
  ('02d15068-3277-598b-bccb-e78ad73c5996', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'ka', 'ვინ აცხობს ყველაზე გემრიელ ტორტს?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'ee541083-b56d-5f68-9f77-374eea548c5c'),
  ('397dd226-755f-5543-bbea-e5577900ff78', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'de', 'Wer backt den leckersten Kuchen?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'ee541083-b56d-5f68-9f77-374eea548c5c'),
  ('f95c6e53-5c02-5f1f-85c4-af1c226c3995', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'es', '¿Quién hornea el mejor pastel?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'ee541083-b56d-5f68-9f77-374eea548c5c'),
  ('86441819-ad48-51e6-93a7-5409d57d2cae', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'fr', 'Qui fait le meilleur gâteau ?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'ee541083-b56d-5f68-9f77-374eea548c5c'),
  ('3fa4a750-e3cf-5783-9780-49c4de608ede', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'it', 'Chi prepara la torta più buona?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'ee541083-b56d-5f68-9f77-374eea548c5c'),
  ('c25fa769-0c63-503c-9255-f29445427b5d', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'pt', 'Quem faz o melhor bolo?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'ee541083-b56d-5f68-9f77-374eea548c5c'),
  ('32e51797-fde5-5526-a02b-a81207e55299', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'en', 'Who feeds the pet?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, NULL),
  ('dffcb0e5-876f-5557-882d-9a03f2502974', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'ka', 'ვინ აჭმევს შინაურ ცხოველს?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '32e51797-fde5-5526-a02b-a81207e55299'),
  ('a490fb5c-acb7-52bc-81af-8e646da0c0ee', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'de', 'Wer füttert das Haustier?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '32e51797-fde5-5526-a02b-a81207e55299'),
  ('bda4e009-2242-5b6f-b6e5-de7cce9943f5', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'es', '¿Quién da de comer a la mascota?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '32e51797-fde5-5526-a02b-a81207e55299'),
  ('cb6c6c72-fc7b-5f85-a198-1ac7b6cc33f0', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'fr', 'Qui nourrit l''animal de compagnie ?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '32e51797-fde5-5526-a02b-a81207e55299'),
  ('eda5acfb-8ec6-5848-b8f3-1d238f170c88', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'it', 'Chi dà da mangiare all''animale domestico?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '32e51797-fde5-5526-a02b-a81207e55299'),
  ('f768a807-15fb-53fc-8815-ce43fd40c6c9', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'pt', 'Quem alimenta o animal de estimação?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '32e51797-fde5-5526-a02b-a81207e55299'),
  ('248adff4-d239-544f-969f-20d9bb27162e', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'en', 'Who can make everyone laugh?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, NULL),
  ('d1cad278-e22f-5119-b587-dd1dc7315340', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'ka', 'ვის შეუძლია ყველას გაცინება?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '248adff4-d239-544f-969f-20d9bb27162e'),
  ('e20b512e-5ef2-50db-8f62-5e0e2d23019f', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'de', 'Wer kann alle zum Lachen bringen?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '248adff4-d239-544f-969f-20d9bb27162e'),
  ('875c4d50-0fb9-53bd-8258-5e680c17f348', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'es', '¿Quién puede hacer reír a todos?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '248adff4-d239-544f-969f-20d9bb27162e'),
  ('10cf3624-3262-5a59-8b24-6bfc5bf5695c', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'fr', 'Qui peut faire rire tout le monde ?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '248adff4-d239-544f-969f-20d9bb27162e'),
  ('464accd5-9841-5c6d-81d1-149301b2dc70', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'it', 'Chi riesce a far ridere tutti?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '248adff4-d239-544f-969f-20d9bb27162e'),
  ('2a3c6ffe-48d1-5660-aab8-13c12018e81d', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'pt', 'Quem consegue fazer todos rirem?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '248adff4-d239-544f-969f-20d9bb27162e'),
  ('43edda39-7098-5389-bc9e-208f86fe9f18', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'en', 'Who sings loudest in the car?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, NULL),
  ('5a3bc82f-7ac0-5bec-91da-ece12ab7e2e3', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'ka', 'ვინ მღერის მანქანაში ყველაზე ხმამაღლა?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '43edda39-7098-5389-bc9e-208f86fe9f18'),
  ('0b233f71-7e17-5b90-b084-f2b029b06b25', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'de', 'Wer singt im Auto am lautesten?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '43edda39-7098-5389-bc9e-208f86fe9f18'),
  ('fb7156f3-1caf-5771-a760-c740ac3b3858', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'es', '¿Quién canta más fuerte en el coche?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '43edda39-7098-5389-bc9e-208f86fe9f18'),
  ('4e5a0e4c-25b3-5b85-b966-84fce4338a54', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'fr', 'Qui chante le plus fort en voiture ?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '43edda39-7098-5389-bc9e-208f86fe9f18'),
  ('05daf6ae-a0fc-57bd-8d72-f11c951f8859', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'it', 'Chi canta più forte in macchina?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '43edda39-7098-5389-bc9e-208f86fe9f18'),
  ('be6755b5-cb11-5a32-b2da-00da8f4b3294', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'pt', 'Quem canta mais alto no carro?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '43edda39-7098-5389-bc9e-208f86fe9f18'),
  ('2ff7e288-3a86-5a2a-a49e-f53295e92764', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'en', 'Who talks the most?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, NULL),
  ('05510243-1c7d-5723-b6f8-00ffb2fc815b', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'ka', 'ვინ ლაპარაკობს ყველაზე მეტს?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '2ff7e288-3a86-5a2a-a49e-f53295e92764'),
  ('b6eb9be4-36ba-5ce3-8761-a5328278f032', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'de', 'Wer redet am meisten?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '2ff7e288-3a86-5a2a-a49e-f53295e92764'),
  ('ca4788eb-3d93-511e-b046-ec662e3cef8f', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'es', '¿Quién habla más?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '2ff7e288-3a86-5a2a-a49e-f53295e92764'),
  ('f5c14827-e0d4-5593-8d5b-e5e94b46f9fc', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'fr', 'Qui parle le plus ?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '2ff7e288-3a86-5a2a-a49e-f53295e92764'),
  ('a5212d48-06ec-51f5-a854-46e5894c0af1', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'it', 'Chi parla di più?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '2ff7e288-3a86-5a2a-a49e-f53295e92764'),
  ('1b1f9216-e9e6-5825-b518-1817ded40949', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'pt', 'Quem fala mais?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '2ff7e288-3a86-5a2a-a49e-f53295e92764'),
  ('5ae02788-9b7e-525f-9ef7-00129955dba1', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'en', 'Who takes the most selfies?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, NULL),
  ('b1aaed32-45a8-50ed-8fdf-da1dced0edec', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'ka', 'ვინ იღებს ყველაზე მეტ სელფის?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '5ae02788-9b7e-525f-9ef7-00129955dba1'),
  ('d552823d-9da4-55fc-a175-b708d26f3fa6', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'de', 'Wer macht die meisten Selfies?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '5ae02788-9b7e-525f-9ef7-00129955dba1'),
  ('fff26215-291d-554c-8a0c-5dd06b9be4df', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'es', '¿Quién se hace más selfis?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '5ae02788-9b7e-525f-9ef7-00129955dba1'),
  ('47701322-2722-53bc-9785-444d4a4ceeec', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'fr', 'Qui prend le plus de selfies ?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '5ae02788-9b7e-525f-9ef7-00129955dba1'),
  ('3c77f692-d5fe-5e29-b2bb-c6165322ff53', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'it', 'Chi si fa più selfie?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '5ae02788-9b7e-525f-9ef7-00129955dba1'),
  ('9ad8e5f5-26f1-574e-956e-0a68797445ae', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'pt', 'Quem tira mais selfies?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '5ae02788-9b7e-525f-9ef7-00129955dba1'),
  ('ca2edc1c-a7b3-52e1-ab00-d0f1aad7598d', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'en', 'Who is most afraid of spiders?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, NULL),
  ('41b17a45-0374-51a2-93bf-3586b31d2e42', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'ka', 'ვის ეშინია ყველაზე მეტად ობობების?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'ca2edc1c-a7b3-52e1-ab00-d0f1aad7598d'),
  ('433fd16d-25d5-5440-9d9a-cc799ab457b2', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'de', 'Wer hat am meisten Angst vor Spinnen?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'ca2edc1c-a7b3-52e1-ab00-d0f1aad7598d'),
  ('1ac95140-741a-57b7-9cc9-55fda8125e86', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'es', '¿Quién tiene más miedo a las arañas?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'ca2edc1c-a7b3-52e1-ab00-d0f1aad7598d'),
  ('5ce6b152-9305-548a-a085-d6597d233d47', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'fr', 'Qui a le plus peur des araignées ?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'ca2edc1c-a7b3-52e1-ab00-d0f1aad7598d'),
  ('466a4559-5a78-5cfc-af0d-1c7caee06a89', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'it', 'Chi ha più paura dei ragni?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'ca2edc1c-a7b3-52e1-ab00-d0f1aad7598d'),
  ('fb1ac8fb-93b5-5b09-b426-36abaa463e51', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'pt', 'Quem tem mais medo de aranhas?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'ca2edc1c-a7b3-52e1-ab00-d0f1aad7598d'),
  ('64062a79-30c2-53fe-9449-5ca018a8285a', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'en', 'Who watches the most television?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, NULL),
  ('3904f56c-c920-5e80-b4b8-33bbec6e2f3b', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'ka', 'ვინ უყურებს ტელევიზორს ყველაზე ხშირად?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '64062a79-30c2-53fe-9449-5ca018a8285a'),
  ('2e1508bc-491b-52cb-ac6e-8b9fdd6a7b2a', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'de', 'Wer schaut am meisten fern?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '64062a79-30c2-53fe-9449-5ca018a8285a'),
  ('04eb0801-f6e0-5864-840a-a13a1dabd129', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'es', '¿Quién ve más la televisión?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '64062a79-30c2-53fe-9449-5ca018a8285a'),
  ('5c97ee5d-aad6-5ac3-805e-a6ac5a946a4e', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'fr', 'Qui regarde le plus la télévision ?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '64062a79-30c2-53fe-9449-5ca018a8285a'),
  ('8b7d7143-1cc3-5152-92f3-9551b5da2462', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'it', 'Chi guarda più la televisione?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '64062a79-30c2-53fe-9449-5ca018a8285a'),
  ('9f5ba9ac-2551-5bad-b251-4cb9c94bef57', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'pt', 'Quem vê mais televisão?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '64062a79-30c2-53fe-9449-5ca018a8285a'),
  ('faad53b2-037d-58e2-8b82-fac6ae1fccdb', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'en', 'Who remembers everyone''s birthday?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, NULL),
  ('b44c5c20-4527-54a3-8623-687b5cc2a86d', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'ka', 'ვის ახსოვს ყველას დაბადების დღე?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'faad53b2-037d-58e2-8b82-fac6ae1fccdb'),
  ('be1c25a3-3519-5e12-bfc5-e65e374f976c', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'de', 'Wer merkt sich die Geburtstage von allen?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'faad53b2-037d-58e2-8b82-fac6ae1fccdb'),
  ('3a7e0a79-3010-522c-81a7-bce3533a1eee', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'es', '¿Quién recuerda el cumpleaños de todos?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'faad53b2-037d-58e2-8b82-fac6ae1fccdb'),
  ('49c93c7f-61d8-55a4-88bf-036caebdfe71', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'fr', 'Qui se souvient de l''anniversaire de tout le monde ?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'faad53b2-037d-58e2-8b82-fac6ae1fccdb'),
  ('490c08dd-26a3-558a-ac61-99f1dbb5e76c', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'it', 'Chi ricorda il compleanno di tutti?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'faad53b2-037d-58e2-8b82-fac6ae1fccdb'),
  ('f3b5174b-5780-5556-bc23-f1c72c516e4e', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'pt', 'Quem lembra o aniversário de todos?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'faad53b2-037d-58e2-8b82-fac6ae1fccdb'),
  ('aeacb34f-14cd-50b3-8952-438dac25696a', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'en', 'Who knows the most jokes?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, NULL),
  ('822b426f-a963-51e3-b5b4-fd0967c64918', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'ka', 'ვინ იცის ყველაზე მეტი ანეკდოტი?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'aeacb34f-14cd-50b3-8952-438dac25696a'),
  ('26f61937-1451-5893-bde3-a287795874a6', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'de', 'Wer kennt die meisten Witze?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'aeacb34f-14cd-50b3-8952-438dac25696a'),
  ('db1ece4f-28fa-52f3-b812-75a4765cbd56', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'es', '¿Quién sabe más chistes?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'aeacb34f-14cd-50b3-8952-438dac25696a'),
  ('7d781a50-5985-543f-876a-4f638b56c198', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'fr', 'Qui connaît le plus de blagues ?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'aeacb34f-14cd-50b3-8952-438dac25696a'),
  ('e9458889-0935-5acc-ba14-e760a7a39525', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'it', 'Chi conosce più barzellette?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'aeacb34f-14cd-50b3-8952-438dac25696a'),
  ('b484c0cb-6092-5678-b424-e96ba0b3bac5', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'pt', 'Quem sabe mais piadas?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'aeacb34f-14cd-50b3-8952-438dac25696a'),
  ('9eee7406-cde8-5057-81ee-42243849bc1d', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'en', 'Who finds the things everyone loses?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, NULL),
  ('f231190f-8de2-5223-8c0c-c024f2017212', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'ka', 'ვინ პოულობს დაკარგულ ნივთებს?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '9eee7406-cde8-5057-81ee-42243849bc1d'),
  ('266dd182-1da6-50c5-aa59-22061e7839cd', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'de', 'Wer findet die Sachen, die alle verlieren?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '9eee7406-cde8-5057-81ee-42243849bc1d'),
  ('1d97f099-51cd-54da-a34f-6a23ae50d623', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'es', '¿Quién encuentra las cosas que todos pierden?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '9eee7406-cde8-5057-81ee-42243849bc1d'),
  ('b105e1bf-3fe9-58b4-90b0-b3e0f7ed5fb8', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'fr', 'Qui retrouve les objets que tout le monde perd ?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '9eee7406-cde8-5057-81ee-42243849bc1d'),
  ('29372ac7-44f6-597f-98cf-75c2e7d86596', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'it', 'Chi trova le cose che tutti perdono?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '9eee7406-cde8-5057-81ee-42243849bc1d'),
  ('5a09abfd-d42b-5434-893f-2b24925163a2', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'pt', 'Quem encontra as coisas que todos perdem?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '9eee7406-cde8-5057-81ee-42243849bc1d'),
  ('8c310d39-7e91-5e8e-92af-6332cca605e3', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'en', 'Who remembers childhood stories best?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, NULL),
  ('23e808ae-17c9-5b3d-be45-c7bf6eaef308', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'ka', 'ვის ახსოვს ბავშვობის ამბები ყველაზე კარგად?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '8c310d39-7e91-5e8e-92af-6332cca605e3'),
  ('d257ce4e-dcc2-5014-bd11-f0d07ed10bac', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'de', 'Wer erinnert sich am besten an Kindheitsgeschichten?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '8c310d39-7e91-5e8e-92af-6332cca605e3'),
  ('c9c5fe07-9b05-517c-abb2-d0da1c022b36', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'es', '¿Quién recuerda mejor las historias de la infancia?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '8c310d39-7e91-5e8e-92af-6332cca605e3'),
  ('1d66a9e4-d1c0-5faf-924d-31f55dae2175', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'fr', 'Qui se souvient le mieux des histoires d''enfance ?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '8c310d39-7e91-5e8e-92af-6332cca605e3'),
  ('666c9c1f-0cb7-5cd6-be0c-ecef785d6740', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'it', 'Chi ricorda meglio le storie d''infanzia?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '8c310d39-7e91-5e8e-92af-6332cca605e3'),
  ('92765e26-3bbc-595a-8b44-c8997d494caf', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'pt', 'Quem lembra melhor as histórias de infância?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '8c310d39-7e91-5e8e-92af-6332cca605e3'),
  ('eb1aa2c8-b547-504a-85a4-1bd8217300d3', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'en', 'Who will travel somewhere soon?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, NULL),
  ('0544b0f6-4acb-5ce7-8a7c-6cb922367fda', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'ka', 'ვინ აპირებს უახლოეს მომავალში მოგზაურობას?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'eb1aa2c8-b547-504a-85a4-1bd8217300d3'),
  ('8990a36b-c2ae-5035-b556-0aae0b71966b', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'de', 'Wer wird bald verreisen?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'eb1aa2c8-b547-504a-85a4-1bd8217300d3'),
  ('76d3244f-1120-54f9-8ccd-1438e91a57fa', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'es', '¿Quién viajará pronto?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'eb1aa2c8-b547-504a-85a4-1bd8217300d3'),
  ('ce8d87a7-a069-5144-beb7-4a8d4b5f13dd', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'fr', 'Qui va bientôt partir en voyage ?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'eb1aa2c8-b547-504a-85a4-1bd8217300d3'),
  ('2544c24d-98de-518c-8bed-3664b468a10c', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'it', 'Chi partirà presto per un viaggio?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'eb1aa2c8-b547-504a-85a4-1bd8217300d3'),
  ('3c4f7fff-6a84-594f-ad02-63e293b8ec61', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'pt', 'Quem vai viajar em breve?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'eb1aa2c8-b547-504a-85a4-1bd8217300d3'),
  ('b0ee23fa-e6e1-5900-acd3-b6859eef7f3a', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'en', 'Who loves flying the most?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, NULL),
  ('345962cc-31bc-519f-ae3c-0775e3377e19', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'ka', 'ვის უყვარს თვითმფრინავით ფრენა ყველაზე მეტად?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'b0ee23fa-e6e1-5900-acd3-b6859eef7f3a'),
  ('8c6e3fff-15e6-5f3c-a6d2-711a1a1e15f8', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'de', 'Wer liebt das Fliegen am meisten?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'b0ee23fa-e6e1-5900-acd3-b6859eef7f3a'),
  ('c947300b-ce44-5158-a063-3f1d0d921b89', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'es', '¿Quién ama más volar?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'b0ee23fa-e6e1-5900-acd3-b6859eef7f3a'),
  ('7db28b24-79b8-5c87-bcf5-89abbe86f26c', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'fr', 'Qui aime le plus prendre l''avion ?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'b0ee23fa-e6e1-5900-acd3-b6859eef7f3a'),
  ('133dddb3-b89a-522e-bb1e-8d38b9a241a3', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'it', 'Chi ama di più volare?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'b0ee23fa-e6e1-5900-acd3-b6859eef7f3a'),
  ('00147030-db58-559a-b989-bbd129ef9abf', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'pt', 'Quem ama mais voar?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'b0ee23fa-e6e1-5900-acd3-b6859eef7f3a'),
  ('2b1731dd-7c42-56c3-9a1f-4ae6a5a84119', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'en', 'Who most wants to go to the seaside?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, NULL),
  ('8fcd6af5-4ca9-5517-9512-6ff153456f5e', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'ka', 'ვის უნდა ყველაზე მეტად ზღვაზე წასვლა?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '2b1731dd-7c42-56c3-9a1f-4ae6a5a84119'),
  ('4c383295-3a8a-5b3e-98bd-a96d3fdc285b', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'de', 'Wer will am liebsten ans Meer?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '2b1731dd-7c42-56c3-9a1f-4ae6a5a84119'),
  ('d5504cc6-62bd-5d77-a966-e631a6abd683', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'es', '¿Quién quiere más ir a la playa?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '2b1731dd-7c42-56c3-9a1f-4ae6a5a84119'),
  ('d77bab1e-9a4e-50a1-a5ec-82d1cff0041b', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'fr', 'Qui a le plus envie d''aller à la mer ?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '2b1731dd-7c42-56c3-9a1f-4ae6a5a84119'),
  ('7ecd5e50-284c-52ed-9e3e-98d39eef1906', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'it', 'Chi vuole di più andare al mare?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '2b1731dd-7c42-56c3-9a1f-4ae6a5a84119'),
  ('a67dac85-025b-5452-a5d0-af59ec1dff06', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'pt', 'Quem mais quer ir à praia?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '2b1731dd-7c42-56c3-9a1f-4ae6a5a84119'),
  ('1ffe162c-362e-54f9-9df4-b59bc7e13fcc', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'en', 'Who picks the music in the car?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, NULL),
  ('43fd325b-1856-5372-ae73-43b0fb169c92', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'ka', 'ვინ ირჩევს მუსიკას მანქანაში?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '1ffe162c-362e-54f9-9df4-b59bc7e13fcc'),
  ('a4ee8338-7a79-5e33-9164-40864c2ea0b2', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'de', 'Wer sucht im Auto die Musik aus?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '1ffe162c-362e-54f9-9df4-b59bc7e13fcc'),
  ('a4bb6b8d-866b-5839-9b34-cdc930c16201', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'es', '¿Quién elige la música en el coche?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '1ffe162c-362e-54f9-9df4-b59bc7e13fcc'),
  ('1762f33b-a039-5c5d-b59f-9ed5de6b006e', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'fr', 'Qui choisit la musique en voiture ?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '1ffe162c-362e-54f9-9df4-b59bc7e13fcc'),
  ('76cc90b7-b899-548e-bbee-1f9d5eb2de01', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'it', 'Chi sceglie la musica in macchina?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '1ffe162c-362e-54f9-9df4-b59bc7e13fcc'),
  ('1f940cca-beea-55bd-91bf-9ce0724db2d5', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'pt', 'Quem escolhe a música no carro?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '1ffe162c-362e-54f9-9df4-b59bc7e13fcc'),
  ('80d0ce4a-32d4-5cfe-87b8-5a6ba7b0c15a', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'en', 'Who loves bright colours the most?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, NULL),
  ('c3fc61f3-c27c-54ae-85ec-2dc1397d07c1', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'ka', 'ვის უყვარს კაშკაშა ფერები ყველაზე მეტად?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '80d0ce4a-32d4-5cfe-87b8-5a6ba7b0c15a'),
  ('168a844e-4dc4-5467-8603-5cb2f98e4c03', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'de', 'Wer liebt bunte Farben am meisten?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '80d0ce4a-32d4-5cfe-87b8-5a6ba7b0c15a'),
  ('46fd75b0-2e3e-5a01-80c0-71867384703a', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'es', '¿Quién ama más los colores vivos?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '80d0ce4a-32d4-5cfe-87b8-5a6ba7b0c15a'),
  ('d7a18344-d603-55ee-ab47-626dd58558b9', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'fr', 'Qui aime le plus les couleurs vives ?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '80d0ce4a-32d4-5cfe-87b8-5a6ba7b0c15a'),
  ('f4bdcde6-1168-5edc-a582-f6d2ae226007', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'it', 'Chi ama di più i colori vivaci?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '80d0ce4a-32d4-5cfe-87b8-5a6ba7b0c15a'),
  ('838402c0-0ddf-51d9-93e1-c38568b3c7c2', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'pt', 'Quem ama mais as cores vivas?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '80d0ce4a-32d4-5cfe-87b8-5a6ba7b0c15a'),
  ('600b5a8f-89f1-5146-a77b-339c55fc9477', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'en', 'Who watches the most films?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, NULL),
  ('5db7cc26-8726-55b2-a94c-9df951197546', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'ka', 'ვინ უყურებს ყველაზე მეტ ფილმს?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '600b5a8f-89f1-5146-a77b-339c55fc9477'),
  ('2de9e45f-cd83-5f46-87f6-03c7bb1e5b63', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'de', 'Wer schaut die meisten Filme?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '600b5a8f-89f1-5146-a77b-339c55fc9477'),
  ('a5b5ac54-ee54-59c8-b27c-cbe21e9b49f7', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'es', '¿Quién ve más películas?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '600b5a8f-89f1-5146-a77b-339c55fc9477'),
  ('324986a7-d070-56dc-afac-c33396b2966c', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'fr', 'Qui regarde le plus de films ?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '600b5a8f-89f1-5146-a77b-339c55fc9477'),
  ('b8b59ea8-c32b-5aff-a3b5-7ea73db30321', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'it', 'Chi guarda più film?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '600b5a8f-89f1-5146-a77b-339c55fc9477'),
  ('0c428b49-c1f5-5c34-9667-cd297f2dd3ce', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'pt', 'Quem vê mais filmes?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '600b5a8f-89f1-5146-a77b-339c55fc9477'),
  ('6720f311-904d-5a21-a4eb-c705fec8bdfd', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'en', 'Who loves winter the most?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, NULL),
  ('9cdf1e03-39b9-550b-b4d1-1eae4b27da41', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'ka', 'ვის უყვარს ზამთარი ყველაზე მეტად?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '6720f311-904d-5a21-a4eb-c705fec8bdfd'),
  ('74e45f59-992f-526e-9b8a-f0e75f40daac', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'de', 'Wer liebt den Winter am meisten?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '6720f311-904d-5a21-a4eb-c705fec8bdfd'),
  ('bb793ce1-2e5b-52c1-9572-48355ab0998a', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'es', '¿Quién ama más el invierno?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '6720f311-904d-5a21-a4eb-c705fec8bdfd'),
  ('994b3440-7d06-5e56-9c0b-5e2ba2a72507', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'fr', 'Qui aime le plus l''hiver ?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '6720f311-904d-5a21-a4eb-c705fec8bdfd'),
  ('f4ca2bf0-a084-5804-9f2b-bc2af618d249', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'it', 'Chi ama di più l''inverno?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '6720f311-904d-5a21-a4eb-c705fec8bdfd'),
  ('8994713f-d0fd-509b-8351-be67d1ba0888', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'pt', 'Quem ama mais o inverno?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '6720f311-904d-5a21-a4eb-c705fec8bdfd'),
  ('e66fe194-815b-5b42-913e-27681db82ddf', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'en', 'Who loves football the most?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, NULL),
  ('f03db3ab-4814-5aa4-a5d2-7d56f61fd342', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'ka', 'ვის უყვარს ფეხბურთი ყველაზე მეტად?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'e66fe194-815b-5b42-913e-27681db82ddf'),
  ('5ec732a8-deb1-5afa-b933-d81232336394', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'de', 'Wer liebt Fußball am meisten?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'e66fe194-815b-5b42-913e-27681db82ddf'),
  ('f384073e-6864-520e-92b0-ccc043b965f6', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'es', '¿Quién ama más el fútbol?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'e66fe194-815b-5b42-913e-27681db82ddf'),
  ('cf3e08ad-485a-5b07-aa6d-1213c3792ba8', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'fr', 'Qui aime le plus le football ?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'e66fe194-815b-5b42-913e-27681db82ddf'),
  ('6d7885af-fe57-5f9b-96e2-9ca75873b168', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'it', 'Chi ama di più il calcio?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'e66fe194-815b-5b42-913e-27681db82ddf'),
  ('d2086736-976a-543e-bd79-683bb4733734', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'pt', 'Quem ama mais o futebol?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, 'e66fe194-815b-5b42-913e-27681db82ddf'),
  ('6608de8c-4a82-5c7b-8eab-8d722903a3cc', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'en', 'Who chooses the best presents?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, NULL),
  ('56828b76-a99d-56cb-8e7b-1f50b969eac0', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'ka', 'ვინ ირჩევს საჩუქრებს ყველაზე კარგად?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '6608de8c-4a82-5c7b-8eab-8d722903a3cc'),
  ('a53b98f3-473c-5615-bfcf-5697db9f1a8e', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'de', 'Wer sucht die besten Geschenke aus?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '6608de8c-4a82-5c7b-8eab-8d722903a3cc'),
  ('c77c931b-d763-547d-97ce-960e9e433158', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'es', '¿Quién elige los mejores regalos?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '6608de8c-4a82-5c7b-8eab-8d722903a3cc'),
  ('6e91aa6a-9930-5a91-ad71-a004a4946231', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'fr', 'Qui choisit les meilleurs cadeaux ?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '6608de8c-4a82-5c7b-8eab-8d722903a3cc'),
  ('ed12a399-05a9-5e45-b150-5ff2e17369d7', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'it', 'Chi sceglie i regali migliori?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '6608de8c-4a82-5c7b-8eab-8d722903a3cc'),
  ('a920f11f-650b-547f-98c3-69ff314f7e3a', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'pt', 'Quem escolhe os melhores presentes?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '6608de8c-4a82-5c7b-8eab-8d722903a3cc'),
  ('7680b5b1-f94d-5ee3-981d-5b18e873d605', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'en', 'Who takes the most photos at dinner?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, NULL),
  ('7f6cf796-4c0a-5ffa-b6c0-058cf2bb309e', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'ka', 'ვინ იღებს ყველაზე მეტ ფოტოს სადილზე?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '7680b5b1-f94d-5ee3-981d-5b18e873d605'),
  ('3360e54d-3e7b-52c4-9706-cb20fe9da99c', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'de', 'Wer macht beim Essen die meisten Fotos?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '7680b5b1-f94d-5ee3-981d-5b18e873d605'),
  ('e81b137c-03eb-5382-8197-1347e931a089', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'es', '¿Quién hace más fotos en la cena?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '7680b5b1-f94d-5ee3-981d-5b18e873d605'),
  ('d4f6afaa-88d2-5390-a8d8-83ff7777a0fb', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'fr', 'Qui prend le plus de photos au dîner ?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '7680b5b1-f94d-5ee3-981d-5b18e873d605'),
  ('b604e6f8-59f0-5545-87b9-bd3c879d36d0', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'it', 'Chi fa più foto a cena?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '7680b5b1-f94d-5ee3-981d-5b18e873d605'),
  ('a5240392-4fa2-5b39-9311-3a937727262d', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'pt', 'Quem tira mais fotos no jantar?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '7680b5b1-f94d-5ee3-981d-5b18e873d605'),
  ('325588ab-b48b-52a3-b647-3c0f66e72733', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'en', 'Who always forgets their umbrella?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, NULL),
  ('9a6c5ee1-0fe0-5552-94b8-1ce65efdce50', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'ka', 'ვინ ივიწყებს ხოლმე ქოლგას?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '325588ab-b48b-52a3-b647-3c0f66e72733'),
  ('a5660972-b490-5912-a9f0-6db7f89dbb41', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'de', 'Wer vergisst ständig seinen Regenschirm?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '325588ab-b48b-52a3-b647-3c0f66e72733'),
  ('ce0ca8d0-00a6-54f9-b2be-316955398e6e', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'es', '¿Quién olvida siempre el paraguas?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '325588ab-b48b-52a3-b647-3c0f66e72733'),
  ('8f0c9487-fab3-5074-909a-54c8ff6d3e7b', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'fr', 'Qui oublie toujours son parapluie ?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '325588ab-b48b-52a3-b647-3c0f66e72733'),
  ('4c35fe1e-6753-5de8-8b3b-75caacdbb670', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'it', 'Chi dimentica sempre l''ombrello?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '325588ab-b48b-52a3-b647-3c0f66e72733'),
  ('325e1f6c-e675-5c2e-8276-0ea8316ffd0b', 'b7cdb122-2175-5434-9f5f-756cf7e215c8', 'pt', 'Quem sempre esquece o guarda-chuva?', '__vote__', '[]'::jsonb, 'easy', 1, true, true, '325588ab-b48b-52a3-b647-3c0f66e72733')
ON CONFLICT (id) DO NOTHING;

-- ── vote settlement ────────────────────────────────────────────────────────
--
-- One row per settled question. The primary key is the idempotency claim
-- (same pattern as room_first_correct / tv_observer_awards): the first
-- settle_most_likely_votes call for a (game, question) inserts the row and
-- pays out; every later call is a no-op. The table is in the realtime
-- publication so every device learns the winners the moment they exist.

CREATE TABLE IF NOT EXISTS public.room_vote_results (
  game_id        uuid        NOT NULL,
  question_index integer     NOT NULL,
  room_id        uuid        NOT NULL,
  winners        text[]      NOT NULL DEFAULT '{}',
  vote_counts    jsonb       NOT NULL DEFAULT '{}'::jsonb,
  settled_at     timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (game_id, question_index)
);

ALTER TABLE public.room_vote_results ENABLE ROW LEVEL SECURITY;

-- Readable by players; written ONLY by the SECURITY DEFINER settlement
-- function (no INSERT/UPDATE/DELETE policy on purpose). Guarded so a
-- re-apply stays a no-op.
DO $$ BEGIN
  CREATE POLICY "vote results readable"
    ON public.room_vote_results
    FOR SELECT TO authenticated
    USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Realtime delivery of settlements. Guarded: the CI harness has no
-- supabase_realtime publication, and a bare ALTER would abort this whole
-- transaction there.
DO $$ BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.room_vote_results;
EXCEPTION
  WHEN undefined_object THEN NULL;  -- no publication (CI harness)
  WHEN duplicate_object THEN NULL;  -- already added (re-apply)
END $$;

-- Settle the vote for one question (p_question_index set) or for every
-- still-unsettled question of the game (p_question_index NULL — the results
-- screen's catch-all sweep).
--
-- For each question: tally player_answers (empty answers are timeouts and
-- don't count), take the most-voted answer(s) — ties all win — and pay every
-- player who voted for a winner a flat 100 points, marking their answer row
-- correct. Scores land in room_participants.score exactly like live play, so
-- complete_room_round's totals pick them up unchanged.
--
-- Only questions whose room_questions row carries the '__vote__' sentinel are
-- ever settled, so this function cannot mint points on a normal trivia round.
CREATE OR REPLACE FUNCTION public.settle_most_likely_votes(
  p_room_id uuid,
  p_game_id uuid,
  p_question_index integer DEFAULT NULL
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_idx integer;
  v_winners text[];
  v_counts jsonb;
  v_claimed integer;
  v_settled integer := 0;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'authentication required';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.room_participants
    WHERE room_id = p_room_id AND user_id = auth.uid()
  ) THEN
    RAISE EXCEPTION 'not a participant of this room';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.room_games
    WHERE id = p_game_id AND room_id = p_room_id
  ) THEN
    RAISE EXCEPTION 'game does not belong to this room';
  END IF;

  FOR v_idx IN
    SELECT rq.question_index
    FROM public.room_questions rq
    WHERE rq.game_id = p_game_id
      AND rq.room_id = p_room_id
      AND rq.correct_answer = '__vote__'
      AND (p_question_index IS NULL OR rq.question_index = p_question_index)
    ORDER BY rq.question_index
  LOOP
    -- The tally. player_answers rows are wiped at every round start, so
    -- (room_id, question_index) only ever holds the current round's votes.
    SELECT COALESCE(array_agg(answer ORDER BY answer), '{}')
    INTO v_winners
    FROM (
      SELECT answer, count(*) AS votes
      FROM public.player_answers
      WHERE room_id = p_room_id
        AND question_index = v_idx
        AND answer <> ''
      GROUP BY answer
    ) tallied
    WHERE votes = (
      SELECT max(votes) FROM (
        SELECT count(*) AS votes
        FROM public.player_answers
        WHERE room_id = p_room_id
          AND question_index = v_idx
          AND answer <> ''
        GROUP BY answer
      ) m
    );

    SELECT COALESCE(jsonb_object_agg(answer, votes), '{}'::jsonb)
    INTO v_counts
    FROM (
      SELECT answer, count(*) AS votes
      FROM public.player_answers
      WHERE room_id = p_room_id
        AND question_index = v_idx
        AND answer <> ''
      GROUP BY answer
    ) c;

    -- The claim. Exactly one caller inserts the row; the payout below rides
    -- in the same transaction, so a question settles exactly once or not at
    -- all.
    INSERT INTO public.room_vote_results (game_id, question_index, room_id, winners, vote_counts)
    VALUES (p_game_id, v_idx, p_room_id, v_winners, v_counts)
    ON CONFLICT (game_id, question_index) DO NOTHING
    RETURNING 1 INTO v_claimed;

    IF v_claimed IS NULL THEN
      CONTINUE;
    END IF;

    v_settled := v_settled + 1;

    IF array_length(v_winners, 1) IS NULL THEN
      CONTINUE; -- nobody voted; nothing to pay
    END IF;

    UPDATE public.player_answers
    SET is_correct = true,
        points_earned = 100
    WHERE room_id = p_room_id
      AND question_index = v_idx
      AND answer = ANY(v_winners);

    UPDATE public.room_participants rp
    SET score = COALESCE(rp.score, 0) + 100
    FROM public.player_answers pa
    WHERE pa.room_id = p_room_id
      AND pa.question_index = v_idx
      AND pa.answer = ANY(v_winners)
      AND rp.room_id = p_room_id
      AND rp.user_id = pa.user_id;
  END LOOP;

  RETURN v_settled;
END;
$$;

-- SECURITY DEFINER functions are granted to PUBLIC *and* anon by Supabase's
-- bootstrap — close both, then grant exactly who may call it (AGENTS.md
-- rule 3).
REVOKE ALL ON FUNCTION public.settle_most_likely_votes(uuid, uuid, integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.settle_most_likely_votes(uuid, uuid, integer) FROM anon;
GRANT EXECUTE ON FUNCTION public.settle_most_likely_votes(uuid, uuid, integer) TO authenticated;

COMMIT;
