-- Georgian question bank: the review queue, read and cleared.
--
-- Generated by scripts/question-repair-ka/build-migration-4.py from
-- review-flagged.json beside it. Regenerate rather than editing this by hand.
--
-- Batches 1 and 2 left 260 questions at quality_status = 'needs_review' and
-- in production. The status marked a claim that pass could not verify, or a
-- question with more than one defensible answer — not a question it had found
-- wrong. This is the read of all 260.
--
-- What the read kept finding, in rough order of how often:
--
--   * an invented fact. A title no author wrote, a dish no region cooks, an
--     epithet nobody uses. „ვეფხვის ქურდი“, „ქაქლიბი“, „the green sport“.
--     These are retired: there is nothing to repair.
--
--   * a wrong answer sitting among the options as a distractor. Salmon under
--     „which fish lives in fresh water“, the Oort cloud under „where do
--     short-period comets come from“. Most of these are repaired by replacing
--     the one distractor, which keeps the question.
--
--   * a stem that asks less than it means. „The oldest organism“ where a tree
--     was meant, „the biggest snake“ where the heaviest was. Repaired by
--     saying it.
--
-- Rewrites are inside the limits gameplay enforces — 70 characters of
-- question, 20 per option — because isValidQuestionLength drops anything past
-- them before a game sees it. A repair that overshot would delete the
-- question instead of fixing it.
--
-- Every rewrite keeps its original in original_question_text /
-- original_correct_answer / original_incorrect_answers.

BEGIN;

-- ── retired ──────────────────────────────────────────────────────────

-- ადამიანის მსგავსად მოაზროვნე და მოქმედ რობოტს რა ჰქვია?
--   an android is a human-like thinking robot too, and it is offered
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '4ad4121f-f029-4881-bd7e-eed513389217';
-- ეგვიპტის რომელი დინასტია მართავდა ყველაზე დიდხანს?
--   the longest-reigning Egyptian dynasty is not settled and the four options are only numbers
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '9baed019-8eaa-4fc6-abd3-280560ca92e0';
-- ვინ არის ავტორი რომანისა „დიდი მგოსანი“?
--   „დიდი მგოსანი“ is not a known Dochanashvili title
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'c5c38053-bb00-4dea-a5f3-dea54eda046c';
-- ვინ არის მოთხრობა „მოცეკვავე მოკასინების“ ავტორი?
--   „მოცეკვავე მოკასინები“ is not a documented Rcheulishvili title
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'fc3662ad-614b-4769-88b4-26977239812b';
-- ვინ არის ცნობილი როგორც "სამეცნიერო ფანტასტიკის მამა"?
--   Verne and Wells are both called the father of science fiction, and both are offered
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '27ef0f8f-03aa-4be7-b8f1-a30561c806f1';
-- ვინ არის ცნობილი როგორც „ქართული პროზის დედოფალი“?
--   „ქართული პროზის დედოფალი“ is not an established epithet
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'ffa1c3fd-a2bc-43db-8207-0de951686cd4';
-- ვინ არის „ბაბო და ნიკო“-ს ავტორი?
--   „ბაბო და ნიკო“ is not a documented Kldiashvili title
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '121acd9a-654e-4fd3-9cf4-dde1617a4d14';
-- ვინ არის „ბაბუაწვერას“ ავტორი?
--   „ბაბუაწვერა“ is not a documented Vazha title
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '6fbff03c-a21b-47ac-9e87-f83bbdc4c706';
-- ვინ არის „ვეფხვის ქურდის“ ავტორი?
--   „ვეფხვის ქურდი“ is not a documented Georgian title
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '2fac416e-2ab6-4b03-b54d-580393aaeb0f';
-- ვინ გააცნო ევროპელებს სამხრეთი ამერიკა?
--   South America is conventionally credited to Vespucci, who is not offered
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '810a7e53-d351-4118-86cd-df9501bfcf87';
-- ვინ გამოიგონა ელექტრო გიტარა?
--   the invention of the electric guitar is contested and two of the cited claimants are offered
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '70887c0b-b86a-42d3-bfb8-9e8fbec62e4d';
-- ვინ დაწერა „გენერლის ყვარყვარე“?
--   „გენერლის ყვარყვარე“ is not an Amirejibi title
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '228671e8-a0ca-4c23-a367-62f48557199e';
-- ვინ იყო არქეოლოგი შლიმანი?
--   asks who Schliemann was and answers with his first name
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '971d195a-483c-4065-952c-5b78229eef6c';
-- ვინ იყო ისტორიაში პირველი ცნობილი იმპერატორი?
--   Augustus is Rome's first emperor, not history's; tightening the stem to say Rome landed it word for word on cff9e395, which already asks it
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'd43e8498-0815-446e-beb1-eb27a73dc1b5';
-- ვინ იყო მარჯანიშვილის თეატრის 2002 წლის სპექტაკლის, „გოდოს მოლოდინში“, რეჟისორი?
--   a 2002 theatre production, filed under film and too specific to check
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'c40966c3-1733-4279-a42f-c599239bd32f';
-- ვინ იყო სოციალ-დემოკრატიის ფუძემდებელი?
--   the founding of social democracy is credited to Lassalle and to Bernstein, and both are offered
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '005e4935-1808-4526-bb68-327f553ef742';
-- ვინ იყო ფილმის „კიკუ“ რეჟისორი?
--   no film „კიკუ“ by Tsutsunava is traceable
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '23487201-5f34-4b4e-bea0-1874e04925d2';
-- ვინ შეასრულა მთავარი როლი ფილმში „მანანა“?
--   the lead of „მანანა“ cannot be verified and all four options are actresses of the same period
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'cf9d29da-095c-4c87-9dd6-ae80d93cdefc';
-- ვინ შემოიღო ნულოვანი სიმრავლე?
--   Cantor founded set theory but did not introduce the empty set
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'bde01e88-0400-4a74-aa0d-0e5b90832b2a';
-- ვინ შექმნა ტელესკოპი?
--   the telescope is Lippershey's; 9a728424 asks the answerable version — who first turned one on the sky
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '81130396-cc66-41ca-ba8d-6b600124cc9d';
-- ვის ეკუთვნის რომანი „გურამ ბაონი“?
--   „გურამ ბაონი“ is not a known Robakidze title
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'c3401c53-ecad-42f5-bd75-f3d68f2a1804';
-- ვის ეკუთვნის ფრაზა: ადამიანის 90%-ს მისი განათლება აყალიბებს?
--   the „nine tenths of a man“ line is a loose paraphrase of Locke, not a quotation
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'e4540ef3-8600-4e71-bda8-5612aba7a9f1';
-- ვის უწოდებდნენ „ათენის მამას“?
--   „father of Athens“ is not an established epithet, and 27580280 credits Cleisthenes with the democracy
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '533f4e99-f7fb-4c9a-a64f-4aab7266e51e';
-- ვისი ფილოსოფია ეფუძნება სინდისის ძალას?
--   „founded on the force of conscience“ describes Rousseau as readily as Kant, and both are offered
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '06b2318a-f7c2-4a06-8891-d50d76afd778';
-- კვერცხის, რძის და ყველის დესერტი რა არის?
--   „ქაქლიბი“ is not a documented Georgian dessert
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '0e5a7a65-3ad8-4700-b973-d4b862b7e194';
-- მბზინავი ობიექტი სითბოს ნელა ასხივებს, ვიდრე მქრქალი?
--   two of the four options are not answers to a yes-or-no question
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '70f2ceb1-0a76-4ad8-97f0-e402b99a2aca';
-- რა არის "კვალამკვარი"?
--   „კვალამკვარი“ is not a documented dish
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'a9af37bc-c2ea-4787-aa4e-4f17c8ec22f5';
-- რა არის 'კოსმეტიკა' მოდაში?
--   „what is cosmetics in fashion“ answered „make-up“ is circular
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '5c3cb15a-c196-4a80-a830-108fdc9f8eb5';
-- რა არის ასტრონომიის მოძღვრება?
--   „ასტრონომიის მოძღვრება“ names no discipline
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '9a972e4d-77f9-471a-8752-bc49a2fe6a1c';
-- რა არის ბიორეაქტორი?
--   „ორგანული სისტემა“ does not define a bioreactor
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'd3064d2a-c25d-42f9-84af-8232c48f7d2a';
-- რა არის გიბსის ფენომენი?
--   the options are topics rather than answers, and a bare „Fourier series“ does not state the phenomenon
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'b6eaf52c-1c6a-4e7d-b4ef-e75bc7641886';
-- რა არის ენის არქეტიპი?
--   „ენის არქეტიპი“ is not a term of art for a proto-language
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'ab0ac73a-7734-45bf-85da-5076e9bf59d0';
-- რა არის ვარსკვლავის სიცოცხლის ციკლის ბოლო?
--   most stars end as white dwarfs; de6c16ea answers the same question correctly
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '75fcb396-32e9-459e-bff4-41dc6803a3e9';
-- რა არის კაკლის ძირითადი ცილა?
--   the walnut's principal protein is glutelin, not albumin
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'e763cfbf-4295-4db9-947a-f8d315126b8d';
-- რა არის კარე?
--   კარე and კარი are one letter apart and the bank uses კარი for the Indian dish
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '136baf46-f108-4e51-9028-c8a9cb752c9d';
-- რა არის კრაბის რანგონის მთავარი ინგრედიენტი?
--   crab rangoon is built on cream cheese and usually uses imitation crab
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'ec7b6861-86fd-42cc-bd54-cacd69943339';
-- რა არის მიკროტალღების მთავარი გამოყენება?
--   radio communication is as central a use of microwaves as heating, and it is offered
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'e2030300-c3e2-42cc-bf74-31f95b4c4b5e';
-- რა არის ნივთიერების ყველაზე მცირე ნაწილი?
--   the atom is the smallest particle of an element and the molecule of a compound; the stem does not say which
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '42ad1c31-8cd0-4d13-81f8-9da447f1d98c';
-- რა არის პარაცეტამოლის აქტიური ნივთიერება?
--   circular — paracetamol and acetaminophen are two names for one molecule
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'fb297802-79d9-4b90-b3f9-aeb94a8ab85c';
-- რა არის საოპერო დარბაზის ფორმა?
--   opera houses are built in several plan shapes
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'a66f161f-b9d4-47ce-a1b9-c137fedd5665';
-- რა არის ტრადიციული ქართული ცივი სუპი?
--   „ოქროში“ is okroshka, which is not Georgian
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'bce1b1db-16ee-41f3-8be7-f0ae2c45fb11';
-- რა არის ფილო ცომი?
--   filo is a layered dough, so the wrong answer „ფენოვანი ცომი“ also describes it
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'f5f471ea-659b-4222-ab00-9035c653babe';
-- რა არის ყველაზე სწრაფი გუნდური სპორტი?
--   „the fastest team sport“ is a marketing claim rather than a measurable fact
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '6ce5735b-df29-4843-9567-f52af4cb0d08';
-- რა არის შორეული გალაქტიკების მეცნიერება?
--   asks for the name of a science and answers with an adjective
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '2105dd69-9c79-4209-9274-5d439b22022a';
-- რა არის ცეცხლის რგოლი? (მზის სისტემაში)
--   „ring of fire“ is not a term for anything in the solar system
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '60f28134-fed0-4090-ab1a-54669eccfbd9';
-- რა ეპოქაში გამოჩნდა პირველი ვარსკვლავები?
--   the first stars formed at the end of the dark ages and caused reionisation, so both offered epochs are defensible
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '523747b7-1770-42f8-8cce-69392ced7b1e';
-- რა ერქვა ბუდისტურ სამოთხეს?
--   nirvana is the extinction of craving, not a paradise
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'f01842f2-1504-4350-bb39-0e95589d2203';
-- რა ერქვა მესხური დიალექტის ერთ-ერთ განშტოებას?
--   „ფარონა“ is not a documented Meskhian sub-dialect
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'bc3934c6-f4cd-49ae-a71c-a086618ffb96';
-- რა ერქვა წერეთლის ცხენს?
--   „წერეთლის ცხენი“ does not say which Tsereteli, and the horse's name cannot be checked
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '48795ea3-9fab-4cda-af21-205b3973e16b';
-- რა ეწოდება ბუდისტურ სამონასტრო ტაძარს?
--   a pagoda is a tiered tower, not a monastery
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'da62a1e7-94fa-4263-b75a-53131bec5447';
-- რა ეწოდება მანგას ფორმატს, რომელსაც მარჯვნიდან კითხულობენ?
--   „იომი“ is not a term for right-to-left manga format
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '7a34a7a6-b1fd-4bd0-b710-bbb80a64f1c0';
-- რა ეწოდება მერქნიანი მცენარის მკვდარ გარე შრეს?
--   „ქერქსერა“ is not a word; the dead outer layer is the რიტიდომი
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '7261043c-d69d-4c09-8114-722bce31372e';
-- რა ეწოდება შორეულ გალაქტიკებს?
--   quasars are active galactic nuclei, not distant galaxies as a class
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '03fb37f8-0083-48f1-be4e-e4ed8139a7ba';
-- რა იწვევს სავარდნო ტექტონიკურ ძალებს?
--   „სავარდნო ტექტონიკური ძალები“ is not a recognised term
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'b8495915-4921-4b9c-8012-9559c22970c0';
-- რა სტილს მიეკუთვნება ბაქოს ქალწულის კოშკი?
--   the Maiden Tower is Shirvanshah-era local work; „Persian“ is not the standard attribution
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'a767953d-5304-413b-8672-ec07b80057b8';
-- რა ფერი ჭარბობს საკურთხევლის კანკელის დეკორაციებში?
--   „which colour predominates“ on an iconostasis has no documented answer
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '311e6344-acf2-4e6b-bcab-f1c574af0d42';
-- რა ფერია საშიში ნარჩენის კონტეინერი?
--   hazardous-waste container colours differ by country
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '94ba22d9-a3b3-41f9-b6e2-67f85a9d7e79';
-- რა ჰქვია Facebook-ის ვირტუალურ ვალუტას?
--   Libra was renamed Diem and wound up in 2022; Facebook has no virtual currency
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '5010bc1f-841d-406d-b4fb-1e8c113d4662';
-- რა ჰქვია ადამიანის/ორგანიზაციის ციფრულ იმიჯს ინტერნეტში?
--   „ვირტუალური იდენტობა“ names a digital image at least as well as the answer
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '4360f977-51a8-412f-a067-0089ef1fbe4c';
-- რა ჰქვია ანიმე-მანგას პერსონაჟების დიდი თვალების სტილს?
--   „მანგა თვალები“ is not a term of art and repeats the stem
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'f744c103-a00e-46dd-8ff5-68c1ff4c46fc';
-- რა ჰქვია გამოყვანილ, დამარილებულ ხორცს?
--   „ყაღი“ for cured meat is not documented; the Georgian terms are ლორი and აპოხტი
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'c90a717f-3ae9-4cc6-82cf-33f089a7d983';
-- რა ჰქვია დედამიწის გარშემო არსებულ ოზონის ფენას?
--   the ozone layer sits inside the stratosphere, which is offered as a wrong answer
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'dfadb355-f64f-4a3c-a78e-b2b67b41f112';
-- რა ჰქვია ვარსკვლავის სიკვდილის ბოლო ფაზას?
--   the same black-hole claim as 75fcb396
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'b78feda3-1ee8-4b96-b15b-4fb2f8aa019b';
-- რა ჰქვია ინდუიზმში ხელახლა დაბადების პროცესს?
--   the Hindu term is samsara, which 756d0126 already asks
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '688af91a-7bb6-4627-98ab-78b1abb320c8';
-- რა ჰქვია კერამიკის დამზადების ტექნიკას?
--   terra sigillata is a ware, not a technique, and the three wrong answers are dating methods
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'a28c18dd-9ba7-41d9-973a-734087d53002';
-- რა ჰქვია კლდის ციკლს?
--   ქანების ციკლი is the established Georgian name, and 47d8b0ba uses it
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '733fd0ef-fad8-42a2-9056-4860e909946f';
-- რა ჰქვია კოსმოსში არსებულ ვაკუუმს?
--   asks what the vacuum in space is called and answers with the word for space
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '464658ef-fa63-4d46-91c7-28ca2ef5256f';
-- რა ჰქვია მესხურ კერძს, რომელსაც მოხარშული გოგრისგან ამზადებენ და თაფლით ატკბობენ?
--   khavitsi is flour roasted in butter, not boiled pumpkin sweetened with honey
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '29f5f9b1-2fb6-4b8b-916f-1a5c1e64196e';
-- რა ჰქვია მტვრის ბურთულებს, რომლებიც გროვდება ავეჯის ქვეშ?
--   „dust bunnies“ has no settled Georgian calque and two options are equally plausible
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '89c22bda-b8a5-4475-8eed-2411b885000f';
-- რა ჰქვია მუქ ფერს ოფიციალურ სამოსში?
--   formalwear uses several dark colours and nothing marks charcoal
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '2b7fe407-1983-40aa-9219-aca4979ab1c4';
-- რა ჰქვია პატარა ნაქსოვ ხელჩანთას?
--   a clutch is not knitted, and the bank defines the clutch correctly in five other questions
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '8238f2ec-0dfe-4ab0-94af-ac0fe467f8b3';
-- რა ჰქვია პატარა ჩანთას, რომელსაც მაჯაზე იკეთებენ?
--   a bag worn on the wrist is a wristlet
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '9af0da6a-c968-4784-b811-36067dfab8f3';
-- რა ჰქვია პეპლის ფრთების ფერად ქერცლებს?
--   butterfly wing scales are scales; chromatophores are pigment cells in other animals
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '2d655f0b-ec8d-43eb-982a-5c488fe5ccf1';
-- რა ჰქვია სამოსის იმ დეტალს, რომელსაც ხშირად 'კეპს' ვუწოდებთ?
--   a cap is headwear, not a detail of a garment
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'c3f239ef-b351-49d9-a506-f1d4f21980c6';
-- რა ჰქვია სახვითი ხელოვნების განშტოებას?
--   „a branch of fine art“ fits several of the options
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '7dc7cfd4-80ba-4feb-82ae-fb45cfc2383d';
-- რა ჰქვია სახვითი ხელოვნების ფორმას ქვიშით?
--   all four options are „sand X“ and the stem gives nothing to choose between them
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '9d69cf65-7fc5-460f-b845-5d129b66b97f';
-- რა ჰქვია სოც. მედია ქცევის შესწავლას?
--   cyberpsychology, offered as a wrong answer, studies online behaviour as squarely as digital ethnography
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '05294c04-30fe-4f79-a183-fc5f58823f9f';
-- რა ჰქვია ტიბეტის პლატოს?
--   a second question for the same epithet, and its three wrong answers — დიდი ვაკე, მთის გული, კლდოვანი მასა — are invented terms
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '36ffd950-d202-4ab8-97bc-302afabaea67';
-- რა ჰქვია უცნობ სიდიდეს მათემატიკურ განტოლებაში?
--   marks ცვლადი correct for the unknown in an equation, which aa88d2ea offers as a wrong answer
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'd98426d2-71f1-4212-91a3-818d0ef69d19';
-- რა ჰქვია ფეხსაცმლის ძირის ტიპს?
--   „a type of shoe sole“ fits the heel offered as a wrong answer
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '405ec1fa-99b5-46f6-b1f8-b8ae6f5feb93';
-- რა ჰქვია ფილოსოფიურ მიმდინარეობას, რომელიც უარყოფს ჭეშმარიტებას?
--   relativism relativises truth rather than denying it
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'dbb2b263-fcfb-4f35-82bb-4e097f866fc0';
-- რა ჰქვია ძველ საბერძნეთში მოქალაქეთა კრებას?
--   the Athenian ekklesia renders in Georgian as ეკლესია, which reads as „church“, and the agora is offered as a wrong answer
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'd1449073-5b94-4f27-914d-9bc358dd4164';
-- რა ჰქვია ძილის წინ ნათქვამ კეთილ სურვილს?
--   „მშვიდი ღამე“, offered as a wrong answer, is the standard phrase
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '21073d2f-c24b-47d1-9d2f-af3cda576a8c';
-- რამდენი დასტა კარტი გამოიყენება სტანდარტულ კაზინოს ბაკარაში?
--   casino baccarat is usually dealt from eight decks, which is not among the options
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'c6f50722-9011-444b-9a22-4d32dc64e7f7';
-- რამდენი რბოლაა ფორმულა 1-ის სეზონში?
--   the number of Formula 1 races changes from season to season
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '31d48f70-4123-4391-8df8-5e69d118b6f0';
-- რისგან შედგება საპროცენტო განაკვეთი?
--   „მტკიცე + რისკი“ does not name the components of an interest rate
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '4ae3cb27-e93d-4699-a34c-35a787672919';
-- როგორ მოიხსენიება ოქროს ხანის პერიოდის ქართული სამეფო ტახტი ისტორიულ წყაროებში?
--   the golden-age throne „is referred to as“ the golden throne — circular
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'f7adc1bb-afad-42af-8d5e-4cc3ba862b32';
-- როგორ მოიხსენიებენ მემს „Hide the Pain Harold“-ს ქართულად?
--   the meme has no settled Georgian name and all four options are inventions
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'f59e128b-0c50-4d85-ba29-53611539958b';
-- როგორ უწოდებენ კაპიტალის გრძელვადიან ინვესტირებას ქვეყნებს შორის?
--   long-term cross-border capital investment is პირდაპირი უცხოური ინვესტიცია
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'bb0b5c6d-06b6-42d8-b2e5-8154d4aa5ba3';
-- როდის არის მოქცევა ყველაზე ძლიერი?
--   spring tides occur at both new and full moon, and both are offered
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '5044f2bc-f513-4956-94f0-1f139d64c085';
-- როდის დაიწყო ატლანტიდის ძიება?
--   the search for Atlantis has no datable start
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '76881c44-32d4-43b0-862b-2c9ec961579f';
-- რომელ ათწლეულს უწოდებენ სამრეწველო რობოტიკის ოქროს ხანას?
--   no decade is conventionally called the golden age of industrial robotics
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'da89f9f2-169d-4ced-9f39-42221efc2704';
-- რომელ ანიმეში ჩნდება ალტერ ეგო?
--   alter egos appear across the medium
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '2e595005-5520-4f8b-a61a-2ec195939366';
-- რომელ ბრძოლაზე თქვა ნაპოლეონმა: „მარცხი ამინდის ბრალია“?
--   „the defeat was the weather's fault“ is not a quotation Napoleon is recorded as making
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '50a2dd0e-c0ca-425e-ab7d-77cce478f9c7';
-- რომელ ენას ჰქვია „ღმერთების სიტყვა“ ანუ „ღვთაებრივი ენა“?
--   answers „language of the gods“ as Egyptian while offering Sanskrit — devavani — as a wrong answer
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '22d24e52-6254-4f82-9b0e-e1790270e44c';
-- რომელ კონტინენტზე არ ყრია ნაგავი?
--   Antarctica has waste, from stations and from the ocean
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'd0bbe413-806e-4531-998b-b7bb07515ec2';
-- რომელ მინერალს ჰქვია „მეოცნებე ქვა“?
--   „the dreamer's stone“ is not an established epithet for nephrite
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'a821134b-88f0-45e8-b202-0fdcc7291d44';
-- რომელ ობიექტს აქვს ყველაზე დიდი სიმკვრივე?
--   a supermassive black hole's mean density is lower than water's
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '1eaff3d3-da3a-4b80-8fb0-788e6ef8092b';
-- რომელ რეგიონშია გავრცელებული გოჭის ტაბაკა?
--   tabaka is a chicken preparation; „გოჭის ტაბაკა“ is not a Georgian dish
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'cf55827d-ef99-404c-a7b3-357d46621e55';
-- რომელ რელიგიურ მიმდინარეობას მიეკუთვნება კოშო-ძის ტაძარი?
--   no temple by this name is traceable
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '2389ae70-c1cc-455e-96aa-5f0a2a2a2eb4';
-- რომელ რიცხვებს უწოდებენ „რიცხვთა დედოფალს“ მათემატიკაში?
--   Gauss called arithmetic the queen of mathematics, not primes the queen of numbers
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '349113e3-5c1b-41c8-8acb-b86bde71912f';
-- რომელ საუკუნეს მიეკუთვნება ასომთავრულის შექმნა?
--   puts Asomtavruli in the IV c.; bb7fb85a, d92af455 and 50624fc2 all say V, and one of them offers IV as a wrong answer
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '0151944e-c44f-45fd-aca8-a7d8b7fb13bb';
-- რომელ საუკუნეში აშენდა მცხეთის ჯვარი?
--   dates Jvari to the VI c. and offers VII as a wrong answer, while f0aa8be0 does the reverse; the church standing today was finished in 605
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '1e992194-060a-4743-922b-e8bd7b05f322';
-- რომელ საუკუნეში დაიწყო ქინძმარაულის ისტორია?
--   Kindzmarauli as an appellation dates from the 20th century
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'bfafc73f-ef2c-482d-9d1e-0855244b2403';
-- რომელ საუკუნეში შეიქმნა ლურჯი სუფრის ტრადიცია?
--   ლურჯი სუფრა is a 19th-century printed textile
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '9a2766b6-4a7e-498c-b94e-358b63e25a89';
-- რომელ სპორტში ჯილდოვდებიან ჩემპიონები ბეჭდებით?
--   the NFL, MLB and NHL all award championship rings, and all three are offered
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '875a777e-0059-4a23-9c39-6c6e30cfeeae';
-- რომელ ქალაქშია „სამყაროს კარიბჭის“ კოშკი?
--   no „Gate of the World“ tower is documented at Al Khobar
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'c990e1e6-14e1-4f5e-a729-f44b6c0e39c9';
-- რომელ ქართულ საბრძოლო სპორტშია 'ხრიდოლი'?
--   khridoli is a Georgian martial art in its own right, not a technique within wrestling
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '13b48f89-dede-4405-8b90-970bf6b988d3';
-- რომელ ქვეყანაში გადაიღეს ლევან თუთბერიძის 2022 წლის მოკლემეტრაჟიანი ფილმი „კატის თვალი“?
--   a 2022 short with no traceable record, and the stem runs to the edge of the card
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '7e1103b3-6280-4e13-b99c-6cbd34dc4a8d';
-- რომელ შტატშია აბაზანაში კითხვა აკრძალული?
--   the Arkansas bathroom-reading law is an urban legend
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '966715e2-e87d-4484-91c4-1ece77337122';
-- რომელ ცხოველს ჰქვია სუამუსი?
--   „სუამუსი“ is not a documented name for any reptile
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'fab7e097-6722-445c-a27b-c7ae016d5877';
-- რომელ წელს აიღო შაჰ-აბას I-ის ლაშქარმა დუშეთის ციხე?
--   the three wrong answers are the adjacent years, so the question is unanswerable without the exact date
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'e6b5a597-08c8-4d67-8107-c378608c4e11';
-- რომელი ბანკი გასცემს სესხს ცენტრალურ ბანკებს?
--   the World Bank lends to states; the bank for central banks is the BIS
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'dfde08ac-a99f-4d39-907b-01b7ec650c0e';
-- რომელი ბოსტნეულია თათარბერაკის ინგრედიენტი?
--   tatarberaki is a dough-and-yoghurt dish; onion is not its defining vegetable
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'a4bbe5e4-9ed3-4c61-b928-f884fad4f289';
-- რომელი ბრენდი იყო პიონერი სპორტული ფეხსაცმლის მოდაში?
--   names Adidas the pioneer of the sports shoe, which Converse was
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '16b290ed-5f02-4755-b9b4-001241c92a38';
-- რომელი ენის ქართული სახელწოდება მომდინარეობს ტომის სახელიდან?
--   several Georgian language names come from tribe names, so more than one option fits
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'f5758ed6-82b5-4f3f-912f-5ab99e3271ae';
-- რომელი იარაღი იყო ვაჟკაცობის სიმბოლო საქართველოში?
--   asks the same question without the long-bladed qualifier, so both the sword and the dagger answer it
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '469f4cf7-e9e5-4747-8d92-17db23af56d7';
-- რომელი იკვლევს ძველ გზებს?
--   „არქეოტოპოგრაფია“ is not an established discipline name
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '7fb1db9e-bc4d-4d7a-b278-338f29113f86';
-- რომელი ინგრედიენტია ტორტილაში?
--   wheat tortillas are as standard as corn ones, and wheat flour is offered
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'f2438d31-93d7-4b38-a0dc-6578a8887e89';
-- რომელი იყო გურამ დოჩანაშვილის ბოლო ნაწარმოები?
--   „last work“ is a moving target
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '9469a0d6-0417-4d35-bfeb-ddc184dd9158';
-- რომელი იყო პირველი დინასტია ჩინეთში?
--   the Xia is traditionally China's first dynasty and the Shang the first attested one, so the question has two defensible answers
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'ba1603aa-5ae0-4eb7-8a40-73c041e59d75';
-- რომელი იყო ქალთა ტრიადა ბერძნულ მითში?
--   Demeter and Persephone are two of the three goddesses the triad usually comprises, and both are offered
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'b511a6d2-4e43-4a74-8cb8-95f3ea835370';
-- რომელი კერძი მზადდება ნადუღის, ყველისა და პიტნისგან?
--   „ფუჩხოლია“ is not a documented dish
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '1c0ab7e5-f68c-47fc-8808-e567bbabf291';
-- რომელი კუთხის სანელებელია ცნობილი თავისი არომატითა და გემოთი?
--   „famed for its aroma and taste“ describes every option
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'bf6df85c-4adc-4953-869f-c6462456a9b2';
-- რომელი ლიდერი იყო ჩინეთის კომუნისტური პარტიის დამაარსებელი?
--   the CPC was founded by Chen Duxiu and Li Dazhao; Mao was one of the delegates
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'd9fab09e-7eed-4ef4-9221-8f99b9be7597';
-- რომელი მათგანია მაგმური სხეულის ფორმა?
--   an extrusion is a form of igneous body as much as an intrusion
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '0a3348d0-e863-4346-9c99-ed8fd59f0641';
-- რომელი მეცნიერია ელექტრომაგნეტიზმის ფუძემდებელი?
--   Ampere and Maxwell founded electromagnetism as much as Faraday, and both are offered
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '2872f288-4b1a-43c6-a70b-6f84685cf036';
-- რომელი მეცნიერია ცნობილი დისტილაციის გამოგონებით?
--   distillation predates al-Razi by centuries
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'be15b3a9-8400-4231-b965-6006ee3518b2';
-- რომელი მოლეკულა აკავშირებს ფერმენტს სუბსტრატთან?
--   a cofactor assists catalysis; it does not bind enzyme to substrate
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '9f23383e-eebd-4c4e-bc9d-fed52db3672f';
-- რომელი მტაცებელია ცნობილი ხანგრძლივი, მელოდიური ყმუილით, ხშირად სავსე მთვარის დროს?
--   the stem states as fact that wolves howl at the full moon, which they do not
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'd1834211-4cd2-4238-b8f2-35ac23f98d44';
-- რომელი მუზეუმი ინახავს საქართველოს უდიდეს ოქროს საგანძურს, ვანის არქეოლოგიური აღმოჩენები
--   the Simon Janashia museum is part of the National Museum, which is offered as a wrong answer; the stem is also 96 characters
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'f9a22a52-1289-4a05-b616-101c69b72bb5';
-- რომელი მწერალია 'გველის შხამის' ავტორი?
--   „გველის შხამი“ is not a known Chiladze title
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '779a341d-668a-46cc-be92-fa4a742d1d2d';
-- რომელი მწერლის ბებია იყო ზუზია?
--   Dumbadze's grandmother character is Olga
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'e6e6dcf5-42e0-436d-a907-75740145de8d';
-- რომელი ნივთიერებაა ცნობილი როგორც ქვანახშირი?
--   coal is a rock and carbon an element; the stem conflates them
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '3624a9d2-2d01-4278-bd42-438f2d244a76';
-- რომელი სანელებელია აუცილებელი გურულ ღვეზელში?
--   ძირა is the signature spice of kubdari, not of Gurian ghvezeli
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '60baa88c-423e-43b6-a93c-27a433003711';
-- რომელი სანელებელია კუმინი?
--   the same spice appears as კუმინი, ძირა and ზირა across the bank, so a player learns three names as three spices
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'f9eda304-bf49-44e2-a836-1afcdb18b752';
-- რომელი სანელებელია მნიშვნელოვანი ფაფაში?
--   „ფაფა“ names no particular dish, so no spice is uniquely important to it
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'ddf95ed7-8b9d-4b34-bdb3-e265ae38baef';
-- რომელი სერიალია ცნობილი დიდი რობოტებით?
--   Gundam is at least as famous for giant robots, and it is offered as a wrong answer
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '1e10df2c-04d0-4428-9ddb-fd63139457f5';
-- რომელი სკოლა უსვამს ხაზს აბსოლუტურ სიკეთეს?
--   „stresses absolute good“ fits Platonism at least as well as Stoicism
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'e66bb219-9655-4583-b316-bb7f2d3c02c0';
-- რომელი სპორტია ცნობილი როგორც 'მწვანე სპორტი'?
--   „the green sport“ is not an established epithet for golf
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '1f89ec3e-c397-412d-bda7-dfa899abd7f6';
-- რომელი სპორტის სახეობაა ცნობილი როგორც 'მეფური სპორტი'?
--   gives chess for „მეფური სპორტი“, which collides with 7a5cff22; the four other chess questions all say თამაში
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '8484f283-3dee-4a37-a04c-04b75749cc4d';
-- რომელი სპორტსმენია ცნობილი როგორც 'ჰაეროვანი მაიკი'?
--   Jordan's nickname is Air Jordan; „ჰაეროვანი მაიკი“ translates a name that was never his
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '9563b5de-c2c6-4f08-8b42-f8ea6342e7fc';
-- რომელი სტრუქტურაა ცნობილი თავისი საყრდენებით?
--   „famous for its supports“ fits every option; 433f7fbb asks the flying-buttress question properly
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '98e938e8-5b89-466f-a450-f6c166c43213';
-- რომელი ტერმინი აღნიშნავს არტეფაქტს, ორიგინალის მიბაძვით შექმნილს?
--   „ეპიმორფული“ is not a term for a copy of an artefact
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '502bdac5-d98b-47e2-b65d-c23b50664f92';
-- რომელი ფერია ცისარტყელას მთავარი ფერი?
--   a rainbow has no principal colour
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'c819bf80-ce3c-4b8d-91bf-24329ce176b4';
-- რომელი ფილოსოფოსია სოლიფსიზმის ფუძემდებელი?
--   Berkeley explicitly denied solipsism; 5d2e3a1f already names him the subjective idealist
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '0e69ac6f-46e2-403c-8351-a194fd48af83';
-- რომელი ქართული კერძია სოკოსგან დამზადებული?
--   the answer, mushroom khinkali, repeats the word the stem asks about
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '541242db-28bb-4587-81da-0ff6cb578522';
-- რომელი ქართული პურია ნაქსოვი, სადღესასწაულო, ორნამენტით?
--   კაკალხაჭაპური is not an ornamented festive bread
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'f299358b-bbc3-4556-9acf-362de3eb80d5';
-- რომელი ქართული რომანის მთავარი გმირია პერსონაჟი გიორგი ელიოზი?
--   the protagonist of დიდოსტატის მარჯვენა is Konstantine Arsakidze
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '909f1da7-1ba7-4e0c-ba4c-37430e3018a2';
-- რომელი ქართული სიმღერაა იუნესკოს სიაში?
--   UNESCO lists Georgian polyphony as a whole; 4bd0bbea covers Chakrulo's Voyager fact properly
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '50b11f69-015e-4812-9c2c-a12ab1f0ef97';
-- რომელი ქართული ცეკვის თემაა ნადირობა?
--   „ნადირობანა“ is not a documented dance
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '61792392-6e23-449f-98ef-8e4304d6172d';
-- რომელი ქვეყანაა ცნობილი „ფალაფელით“?
--   falafel is Egyptian and Levantine in origin; naming one country as „known for“ it is contested
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'aaa8f7c2-1cf8-4b58-9c3b-66e695b7973e';
-- რომელი ქვეყნის ტრადიციული კერძია „ჰუმუსი“?
--   hummus is common to the whole Levant and Egypt is offered as a wrong answer
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '96bd46f1-d932-49b2-bf4f-2cc673451a08';
-- რომელი ცხოველი გახდა ინტერნეტ მემების სიმბოლო?
--   dogs and frogs are meme symbols as much as cats, and both are offered
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '842af238-08cb-4c9b-8bf7-948bfcf0fb4b';
-- რომელი ცხოველია გადამუშავების სიმბოლო?
--   no animal is the recycling symbol; the symbol is the Mobius loop
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '18b587e1-cd99-4ae2-b3cd-fbfa176ab600';
-- რომელი ცხოველია ერთადერთი, რომელსაც ოთხი მუხლი აქვს?
--   the same myth stated the other way round
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '4ae85639-5369-4cdd-b203-0c6d01eba6c9';
-- რომელი ცხოველია იაპონიაში სიძლიერის სიმბოლო, სუმოსთან?
--   no animal is the established Japanese symbol of strength alongside sumo
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'c6ad3641-3a26-4668-b8ed-68c83d728fe5';
-- რომელი ცხოველის "მუხლები" სინამდვილეში მაჯებია?
--   an elephant's front knees are knees; the „wrists“ claim is a myth
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '9d7e713b-cf16-4e5e-91b6-afcb2b8ffdbe';
-- რომელი ცხოველის რძეა ვარდისფერი?
--   hippo milk is not pink; the pink secretion is its skin's „blood sweat“
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'c020b77a-70eb-44df-8263-4581de743a51';
-- რომელია ბავშვის განვითარების ეტაპი?
--   the oral stage is Freudian psychosexual, not a stage of child development in general
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '1cbfb125-431b-414d-b67c-573281bf3678';
-- რომელია ეკოსისტემის დაშლის მაგალითი?
--   „რიყის წყალმცენარე“ does not describe ecosystem collapse
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'ac45c0a1-5042-4196-a97e-90e17170c5fb';
-- რომელია საქართველოს ამჟამინდელი პრეზიდენტი?
--   „the current president“ has been out of date since December 2024, and 8b304737 asks the same thing with a year attached
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'ee9d7f12-4b4d-4097-9937-89a763849ed9';
-- რომელია სერიალ „ფარული ვნების“ ერთ-ერთი მთავარი გმირი?
--   the telenovela and its characters cannot be verified
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '671f888f-4949-4bb8-9117-eefb2cd11371';
-- რომელია ტრადიციული ქართული თექის ქუდის ერთ-ერთი ყველაზე ცნობილი სახეობა?
--   ჩაჩი is not a Georgian felt hat; ფაფახი and ყაბალახი, both offered as wrong answers, are
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '24f7a146-b091-4193-a305-ccd3a101b69c';
-- რომელია ფილოსოფიის აკვანი?
--   Chinese and Indian philosophy are older than Greek, and both are offered
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '9cb0f0c2-bf9f-4877-978a-072f505395ba';
-- რომელია ყველაზე მდიდარი ენა სიტყვების რაოდენობით, ოქსფორდის ინგლისური ლექსიკონის მიხედვი
--   circular — an English dictionary counts English words, and word counts are not comparable across languages
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '633db580-5b37-436c-804f-840eba818f4d';
-- რომელმა რომის იმპერატორმა აკრძალა ქრისტიანობა?
--   Nero persecuted Christians locally; the empire-wide bans were Diocletian's, and he is offered as a wrong answer
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '837f5b57-3255-4034-9001-a737d0d47842';
-- რომელმა ქართველმა მწერალმა მიიღო ნობელის პრემია ლიტერატურის დარგში?
--   a17c505b asks the same fact and answers it the same way
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '5a1f39c4-a133-48db-b5f1-b2cc3b23e596';
-- როცა ნივთები სულ ერთი ბრენდია, რა ჰქვია ამას?
--   a total look is head-to-toe coordination, not head-to-toe one brand
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'b115a281-dd96-4eec-b3b0-52efbda8b75c';
-- საქართველოში რომელ დღეს აღნიშნავენ დავითობას?
--   Davitoba falls in May, not 8 February
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = 'e769726d-b6f7-4d2e-9dcc-8ba2acaea48c';
-- ტექსტილის ინდუსტრიაში, რას ნიშნავს ტერმინი „ლუპა“?
--   ლუპა is a magnifying glass; the textile loop is ლუპი
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '00fd3272-3365-4ed6-86f3-3efa34519ddc';
-- ფაქტია თუ არა, რომ კამელეონი გარემოსთან ერთად ფერს იცვლის?
--   teaches that chameleons change colour to match their surroundings — the myth, in the myths-versus-reality category
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '1e37a979-0102-4c91-a83f-fcd2b3e24ae9';
-- შეუძლია წყლის ტორნადოს წყალქვეშა ობიექტების დაზიანება?
--   waterspouts do disturb the water column, so a flat „no“ is not supportable
UPDATE public.questions SET is_active = false, in_production = false, quality_status = 'retired_ka_repair', updated_at = now() WHERE id = '915098f0-f30d-41ee-a2c6-3cc2b66cfffe';

-- ── repaired, and the flag cleared ───────────────────────────────────

-- ვინ არის სუპერგმირული ანიმე სერიალის მთავარი გმირი?
--   „the superhero anime series“ named no series
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), question_text = 'ვინ არის „ჩემი გმირი აკადემიის“ მთავარი გმირი?', quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = 'c62f46e2-cf14-4cce-8df9-9d45920ecf44';
-- ვინ არის ცნობილი ქცევითი თერაპიის მამა?
--   Watson is the father of behaviourism; behaviour therapy is Wolpe's and Skinner's
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), question_text = 'ვინ არის ბიჰევიორიზმის მამა?', quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = 'da14db47-5e73-41b9-b229-cd6bbcb761d8';
-- ვინ იყო პირველი ადამიანი, რომელმაც დედამიწის გარშემო იმოგზაურა?
--   Magellan was killed in the Philippines and Elcano completed the voyage; Magellan led it
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), question_text = 'ვინ ხელმძღვანელობდა პირველ ნაოსნობას დედამიწის გარშემო?', quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = 'a3181201-7fef-4a36-8ac7-64c032152218';
-- ვინ იყო სამხრეთ აფრიკის პირველი პრეზიდენტი?
--   presidents held office under apartheid before Mandela
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), question_text = 'ვინ იყო სამხრეთ აფრიკის პირველი დემოკრატიულად არჩეული პრეზიდენტი?', quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = 'e972df8d-db68-4289-818a-08a674490e3d';
-- ვინ იყო ძველი ეგვიპტის პირველი ქალი ფარაონი?
--   Sobekneferu and Merneith ruled before Hatshepsut
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), question_text = 'ვინ იყო ეგვიპტის ყველაზე ცნობილი ქალი ფარაონი?', quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = '18c51dc4-4947-4ce0-8123-911582afebd7';
-- ვინ შექმნა ტომი და ჯერის პერსონაჟები?
--   Tom and Jerry are Hanna and Barbera's together
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), correct_answer = 'ჰანა და ბარბერა', quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = '3b30a8d4-a80e-4071-bab5-fe26714008ef';
-- კანის ანთების სამკურნალოდ რა მცენარე გამოიყენება?
--   chamomile is used for skin inflammation as widely as calendula
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), incorrect_answers = '["ტიტა", "ორქიდეა", "ია"]'::jsonb, quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = 'e4e2ceed-f074-4382-9a61-1552da8ab0e2';
-- მიწის რომელ მყარ ფენაში ვრცელდება სეისმური ტალღები?
--   seismic waves travel through the core, which was offered as a wrong answer
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), incorrect_answers = '["ატმოსფერო", "ჰიდროსფერო", "იონოსფერო"]'::jsonb, quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = '398568af-a9ef-41aa-97fb-9461eb117ee4';
-- რა არის მუსიკალური ტერმინი „ანდანტე“?
--   „საშუალო ტემპი“ said the same thing as the answer
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), incorrect_answers = '["ძალიან სწრაფი", "ძალიან ნელი", "ცოცხალი ტემპი"]'::jsonb, quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = '1aa7395a-ef93-44cb-a40f-17bd7a60b268';
-- რა ევროპული მთებია ახალგაზრდა?
--   the Apennines are an Alpine-orogeny range too
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), incorrect_answers = '["ურალი", "სკანდინავია", "შოტლანდიის მთები"]'::jsonb, quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = '15db0dd6-b4a2-4601-b972-333773a0ff5e';
-- რა ეწოდება დოკუმენტს, რომელიც პარტიის პოლიტიკურ მიზნებსა და სამოქმედო გეგმებს აერთიანებს
--   a manifesto is exactly what the stem describes; the stem was also 88 characters, past the length gameplay allows
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), question_text = 'რა ჰქვია პარტიის მიზნებისა და გეგმების დოკუმენტს?', incorrect_answers = '["რეგლამენტი", "დოქტრინა", "კონცეფცია"]'::jsonb, quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = '3cde8ee8-9e4b-4c8d-acfb-e0910f015d33';
-- რა ეწოდება მზის ატმოსფეროში ენერგიის მძლავრ ამონთხვევას?
--   a coronal mass ejection answers the stem as well, and at 26 characters it was past the option limit anyway
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), incorrect_answers = '["მზის ლაქები", "ვარსკვლავური ქარი", "პროტუბერანცი"]'::jsonb, quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = 'a7cf80af-1a64-4f47-b9a7-9d82a63eceda';
-- რა ეწოდება შორეულ გალაქტიკებს შორის სიცარიელეს?
--   „კოსმოსური ვაკუუმი“ said the same thing as the answer
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), incorrect_answers = '["გალაქტიკური ჰალო", "გალაქტიკური ზონა", "ბნელი მატერია"]'::jsonb, quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = '0e9ea146-16da-48b5-a2a2-34581a14bdc5';
-- რა ინგრედიენტია აუცილებელი ბაჟესთვის?
--   bazhe is defined by walnut, which was not among the options
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), correct_answer = 'ნიგოზი', incorrect_answers = '["ყვითელი ყვავილი", "ქონდარი", "ოხრახუში"]'::jsonb, quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = 'b9a30662-2059-49d6-99ca-8a9992221300';
-- რა ჰქვია გიგანტურ ყინულის მასას?
--   an iceberg is a giant mass of ice too; the stem now says the glacier's defining trait
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), question_text = 'რა ჰქვია ხმელეთზე მოძრავ გიგანტურ ყინულის მასას?', quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = '0a7774fb-e36c-4640-9a1f-362e6b094cec';
-- რა ჰქვია დედამიწის გარშემო არსებულ დამცავ ფენას?
--   the atmosphere as a whole is protective; the stem now names what it protects against
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), question_text = 'რომელი შრე იცავს დედამიწას ულტრაიისფერი გამოსხივებისგან?', quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = '93fb07ae-be18-4f9b-ad70-e40f77b1b40d';
-- რა ჰქვია ებრაულ წმინდა ტექსტთა კრებულს?
--   the canonical Hebrew collection is the Tanakh; the Talmud is commentary
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), correct_answer = 'თანახი', incorrect_answers = '["თალმუდი", "კაბალა", "ზოჰარი"]'::jsonb, quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = 'ec26deb5-01b1-4e97-9c69-ab69f8771ee0';
-- რა ჰქვია კომეტების მოძრაობის სარტყელს?
--   the Kuiper belt sources short-period comets and the Oort cloud long-period ones
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), question_text = 'საიდან მოდიან მოკლეპერიოდიანი კომეტები?', quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = '429c6f6d-2088-47ca-b29d-fb1b82d3e8e2';
-- რა ჰქვია კუიპერის სარტყლის უდიდეს ჯუჯა პლანეტას?
--   Eris is more massive and Pluto larger across; the stem now says which
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), question_text = 'რომელია კუიპერის სარტყლის ყველაზე დიდი დიამეტრის ჯუჯა პლანეტა?', quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = 'a63517f1-2ffe-4c0b-b19c-559dadd0de07';
-- რა ჰქვია მრავალუჯრედიან ორგანიზმს?
--   yeast is a unicellular eukaryote, so the stem had to change rather than the answer
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), question_text = 'რა ჰქვია ორგანიზმს, რომლის უჯრედს აქვს ბირთვი?', quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = 'd7f9cd6d-566c-454c-8cf9-6ac52840a83f';
-- რა ჰქვია მტკნარი წყლის ეკოსისტემას?
--   limnology is the study, so the stem now asks for the study
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), question_text = 'რა ჰქვია მტკნარი წყლის შემსწავლელ მეცნიერებას?', correct_answer = 'ლიმნოლოგია', incorrect_answers = '["ოკეანოლოგია", "გეოლოგია", "მეტეოროლოგია"]'::jsonb, quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = '663a273e-27c4-4117-bc3b-9de4f3acbbb2';
-- რა ჰქვია პატარა პროგრამულ შეცდომას?
--   a glitch is a small software fault too
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), incorrect_answers = '["ვირუსი", "ჭია", "პაჩი"]'::jsonb, quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = '6c53dad2-c3b6-4eb2-9e0d-8a813ea9c946';
-- რა ჰქვია პოლიტიკურ უფლებებს ქალთა თანასწორობისთვის?
--   suffragism is specifically the vote, which the stem now says
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), question_text = 'რა ჰქვია მოძრაობას ქალთა ხმის უფლებისთვის?', quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = 'e4870b8f-43a4-4c87-ab98-bfcbdb803ad4';
-- რა ჰქვია სინათლის ერთეულს?
--   the lumen measures luminous flux, which the stem now says
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), question_text = 'რა ჰქვია სინათლის ნაკადის ერთეულს?', quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = '53b897a7-dbbd-4b87-8366-2e644c3c5232';
-- რა ჰქვია სპორტსმენს, რომელიც მარათონს დარბის?
--   „მორბენალი“ is also what a marathon runner is called
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), incorrect_answers = '["მსაჯი", "მოცურავე", "მხტომელი"]'::jsonb, quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = '52b61c19-01b0-49f6-800e-339bee4b0316';
-- რა ჰქვია შუმერულ მითში ღმერთების ქალაქს?
--   Nippur is the Sumerian city of the gods; Uruk is Gilgamesh's
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), correct_answer = 'ნიპური', incorrect_answers = '["ურუქი", "ლაგაში", "ერიდუ"]'::jsonb, quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = 'ee2fe2b9-94ee-4484-b5ca-c87af9eaa9fb';
-- რა ჰქვია ჩვენი მზის სისტემის გარე ნაწილს?
--   the Kuiper belt is an outer part of the solar system too
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), question_text = 'რომელია მზის სისტემის ყველაზე შორეული გარსი?', quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = '91c14a94-4e02-4482-ae89-9c67e74f0067';
-- რა ჰქვია ჩვენს უახლოეს ვარსკვლავს მზის გარდა?
--   the nearest star is Proxima Centauri; Alpha Centauri names the system
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), correct_answer = 'პროქსიმა კენტავრი', incorrect_answers = '["ალფა კენტავრი", "სირიუსი", "ვეგა"]'::jsonb, quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = 'c457ae5e-dfb9-4613-af83-4cf7c5f1ff76';
-- რამდენ ხანს ცოცხლობს დედამიწაზე ყველაზე დიდი ხე?
--   the stem asked about the largest tree and the answer was about the oldest
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), question_text = 'რამდენ ხანს ცოცხლობს დედამიწაზე ყველაზე ხნიერი ხე?', quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = 'df922f61-a8d4-4387-83b6-f4d74453fd6a';
-- რამდენია სირბილის ტრეკის ყველაზე მოკლე დისტანცია?
--   the 60 m is shorter indoors; the stem now says Olympic track
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), question_text = 'რამდენია ოლიმპიურ ტრეკზე სირბილის ყველაზე მოკლე დისტანცია?', quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = '27f46ecf-e775-4af2-bbdd-036edc40c127';
-- რას გამოხატავს, როგორც წესი, 'Galaxy Brain' მემი?
--   the meme mocks overconfidence; all four options read it as praise
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), correct_answer = 'ყალბი გენიალურობა', quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = '741e09f7-dce7-498b-81b5-2e1e4160c147';
-- როგორია შავი ხვრელის სიმკვრივე?
--   a black hole's mean density can be low; the singularity's is not
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), question_text = 'როგორია შავი ხვრელის სინგულარობის სიმკვრივე?', quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = '6de00460-fa93-4b62-86c5-55139b033b86';
-- რომელ სპორტშია ყველაზე მეტი ოლიმპიური დისციპლინა?
--   athletics has more Olympic events than swimming, so the answer was the wrong way round
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), correct_answer = 'მძლეოსნობა', incorrect_answers = '["ცურვა", "ტანვარჯიში", "ველოსპორტი"]'::jsonb, quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = 'a8daff46-d6c1-4282-9978-1198c595d319';
-- რომელ წელს გახდა ქალი აშშ-ში საპრეზიდენტო კანდიდატი?
--   Victoria Woodhull ran in 1872; only major-party nomination makes 2016 the answer
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), question_text = 'რომელ წელს იყო ქალი აშშ-ის მთავარი პარტიის კანდიდატი?', quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = '7acb10f0-2167-4bb3-8565-b13e21d26c44';
-- რომელი გალაქტიკაა ჩვენთან უახლოესი?
--   the Milky Way is our own galaxy and was offered as an option
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), question_text = 'რომელია ჩვენთან უახლოესი დიდი გალაქტიკა?', incorrect_answers = '["ტრიანგულუმი", "კენტავრი", "ვირლპული"]'::jsonb, quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = '7320c034-e38c-407f-b280-fedb6f3f6cc3';
-- რომელი დემოკრატიული ინსტიტუტი აკონტროლებს მთავრობას?
--   the courts check the government too
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), incorrect_answers = '["პოლიცია", "მედია", "პროკურატურა"]'::jsonb, quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = '8c8aaa62-fea2-4c4b-b486-46ea9178bb85';
-- რომელი დიეტაა მაღალცხიმოვანი, კეტოზის მისაღწევად?
--   Atkins is also a high-fat diet aimed at ketosis, and one wrong answer ran past the 20-character limit
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), incorrect_answers = '["ვეგანური დიეტა", "პალეო დიეტა", "დუკანის დიეტა"]'::jsonb, quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = '7a1314cf-2bbe-45d6-bacd-286166ef28c9';
-- რომელი ვიტამინი არის ანტიოქსიდანტი?
--   C and E are both antioxidants; the stems now name which
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), question_text = 'რომელი წყალში ხსნადი ვიტამინია ანტიოქსიდანტი?', quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = 'd0491186-8a18-4c39-9d74-ce005b3ba954';
-- რომელი ვიტამინია ანტიოქსიდანტი?
--   the fat-soluble half of the same pair
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), question_text = 'რომელი ცხიმში ხსნადი ვიტამინია ანტიოქსიდანტი?', quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = '6312b8ca-4230-4abb-9b95-3bfb1fb19e8e';
-- რომელი თევზი ცხოვრობს მტკნარ წყალში?
--   salmon live in fresh water too
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), incorrect_answers = '["ზვიგენი", "სკუმბრია", "ტუნა"]'::jsonb, quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = '4568da0e-4789-425e-a4a1-f2fd0a3f7bcf';
-- რომელი იყო ძველი ეგვიპტის დედაქალაქი?
--   Thebes was a capital too; the stem now names the period
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), question_text = 'რომელი იყო ძველი ეგვიპტის ძველი სამეფოს დედაქალაქი?', quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = '1d53e0d9-4174-4cdb-92b4-6e4609a2daf1';
-- რომელი მხატვარია ცნობილი მისი „გოთური ტრიპტიქით“?
--   Bosch's triptych is not Gothic; naming it removes the guesswork
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), question_text = 'რომელი მხატვრის ტრიპტიქია „მიწიერ სიამოვნებათა ბაღი“?', quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = '517b6b85-9990-4f43-a685-48e7b46004df';
-- რომელი ორგანიზმია დედამიწაზე ყველაზე ხანდაზმული ინდივიდი?
--   Pando and Armillaria are older but neither is a single tree
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), question_text = 'რომელი ხეა დედამიწაზე ყველაზე ხანდაზმული ინდივიდი?', quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = '62ff8d82-af3e-40fa-9964-cafcdb07ef9c';
-- რომელი ტრადიციული ქართული ყველის კერძი ცხვება კეცზე?
--   chvishtari is baked on a ketsi as well
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), incorrect_answers = '["ფხალოვანი", "ლობიანი", "მჭადი"]'::jsonb, quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = '1735cc27-f702-4cbb-86a5-881046523721';
-- რომელი ფოტოსინთეზური პიგმენტი არ არის ქლოროფილი?
--   flavonoids and anthocyanins are also not chlorophyll; the question now asks something with one answer
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), question_text = 'რომელი პიგმენტი ანიჭებს სტაფილოს ნარინჯისფერს?', incorrect_answers = '["ქლოროფილი", "ანთოციანინი", "ფიკოციანინი"]'::jsonb, quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = '8f4abfa5-e244-40fe-b8e7-6a97fc7ed9be';
-- რომელი ცხოველი ქმნის კოკონს მეტამორფოზისას?
--   butterflies form a chrysalis; the cocoon is a moth's
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), question_text = 'რომელი მწერი ქმნის ჭუპრს მეტამორფოზისას?', quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = 'd6aae36a-9391-4162-ade2-5cfd5aaf5d7a';
-- რომელი ცხოველი წარმოქმნის მარგალიტს?
--   mussels produce pearls too
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), incorrect_answers = '["კიბორჩხალა", "ლოკოკინა", "მედუზა"]'::jsonb, quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = '3337be9c-912f-4b08-b17d-4e3cff6bf48b';
-- რომელია ყველაზე დიდი გველის სახეობა?
--   the reticulated python is longest and the anaconda heaviest; the stem now asks for the heaviest
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), question_text = 'რომელია ყველაზე მძიმე გველის სახეობა?', quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = '25d05f3e-8b67-4118-8b01-78a6fe9d33a4';
-- რომელმა მოაზროვნემ შექმნა დიალექტიკის კონცეფცია?
--   Zeno is credited with inventing dialectic and Hegel with developing the method
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), question_text = 'რომელმა ფილოსოფოსმა განავითარა დიალექტიკური მეთოდი?', quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = 'bf04bf9a-5ea2-4dd5-b071-e1d71dfa4101';
-- რომელმა ფილოსოფოსმა შექმნა „ღვთაებრივი კომედია“?
--   Dante wrote the Divine Comedy as a poet; the stem called him a philosopher
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), question_text = 'რომელმა პოეტმა შექმნა „ღვთაებრივი კომედია“?', quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = '58983981-6a80-4146-b388-3f06bba6c05f';
-- რუსეთის რომელ ნაწილშია შესაძლებელი მზის ხილვა შუაღამისას?
--   northern Siberia is inside the Arctic Circle, so that wrong answer overlapped the right one
UPDATE public.questions SET original_question_text = COALESCE(original_question_text, question_text), original_correct_answer = COALESCE(original_correct_answer, correct_answer), original_incorrect_answers = COALESCE(original_incorrect_answers, incorrect_answers), incorrect_answers = '["კამჩატკაზე", "მოსკოვში", "არცერთ ნაწილში"]'::jsonb, quality_status = 'repaired_ka', in_production = true, is_active = true, updated_at = now() WHERE id = 'd819b26a-dc92-4913-b4d7-39bc380d0ad9';

-- ── reviewed and sound; the flag comes off ───────────────────────────

-- ამ სერიალებიდან რომელი ეხება სამედიცინო სფეროს?
--   Grey's Anatomy is the medical one; the two Georgian titles for Suits do not affect this question
UPDATE public.questions SET quality_status = NULL, quality_issues = NULL, updated_at = now() WHERE id = 'ef45de47-8689-41dd-aa95-2c774d96a154';
-- ბიბლიაში, ვინ იყო პირველი ქალი?
--   as above
UPDATE public.questions SET quality_status = NULL, quality_issues = NULL, updated_at = now() WHERE id = 'd2dcd622-c6d2-42c8-aab3-f698c36b1788';
-- რა არის ქამელეონის ფერის შეცვლის ძირითადი მიზეზი?
--   communication and thermoregulation is the current account
UPDATE public.questions SET quality_status = NULL, quality_issues = NULL, updated_at = now() WHERE id = '76c5380c-975a-4aa9-a80a-fe525f2998d0';
-- რა ეწოდება განტოლებაში ასოთი აღნიშნულ საძებნ სიდიდეს?
--   the letter in an equation is the unknown
UPDATE public.questions SET quality_status = NULL, quality_issues = NULL, updated_at = now() WHERE id = 'aa88d2ea-825a-4d4e-97ac-7565c9c564b3';
-- რა სანელებელი არ გამოიყენება საცივში?
--   reviewed again: the marked answer is ქონდარი and saffron sits among the wrong answers, which is consistent with 73be50bc
UPDATE public.questions SET quality_status = NULL, quality_issues = NULL, updated_at = now() WHERE id = '56819aa9-bc93-4ff8-b042-00d8bc15ae6b';
-- რომელ ენას ჰქვია „ღმერთების ენა“?
--   Sanskrit is the standard answer
UPDATE public.questions SET quality_status = NULL, quality_issues = NULL, updated_at = now() WHERE id = 'e6daf6a1-25f6-4b4c-8fed-f3113e4d4e68';
-- რომელ რელიგიას უკავშირდება კარმის კონცეფცია?
--   karma is Buddhist as well as Hindu, and neither question offers the other's answer
UPDATE public.questions SET quality_status = NULL, quality_issues = NULL, updated_at = now() WHERE id = '5a9cf584-327f-4b93-b055-6cb5d8291555';
-- რომელი ბრენდი იყო პიონერი სპორტულ ფეხსაცმელში?
--   Converse 1917 predates Adidas by three decades
UPDATE public.questions SET quality_status = NULL, quality_issues = NULL, updated_at = now() WHERE id = 'a2800e33-ab6e-4828-9521-dcd99b81d0c2';
-- რომელი გეოგრაფიული ობიექტია ცნობილი როგორც 'მსოფლიოს სახურავი'?
--   the Pamirs carry the epithet in its original use
UPDATE public.questions SET quality_status = NULL, quality_issues = NULL, updated_at = now() WHERE id = '53cd8996-6102-4579-9298-7dfa9c89ce13';
-- რომელი თუშური კერძი მზადდება მოხალული ქერისგან და კარაქისგან?
--   the barley-and-butter description is the mountain-region khavitsi
UPDATE public.questions SET quality_status = NULL, quality_issues = NULL, updated_at = now() WHERE id = '96f9bae4-45d3-40bf-88d6-0f565f0ff7aa';
-- რომელი იყო ებრაულ მითში პირველი ქალი?
--   „in Hebrew myth“ and „in the Bible“ are different questions
UPDATE public.questions SET quality_status = NULL, quality_issues = NULL, updated_at = now() WHERE id = '615be55d-2b21-4277-9245-829442850c77';
-- რომელი მდინარე ქმნის საზღვარს ბრაზილიასთან?
--   the Nile spelling was corrected in batch 2 and none of the wrong answers borders Brazil
UPDATE public.questions SET quality_status = NULL, quality_issues = NULL, updated_at = now() WHERE id = 'f6293cc1-9002-4936-8e66-e42af5a90523';
-- რომელი სპორტის სახეობაა ცნობილი როგორც 'მეფეთა სპორტი'?
--   the sport of kings is horse racing; the chess questions ask about the game of kings, which is a different epithet
UPDATE public.questions SET quality_status = NULL, quality_issues = NULL, updated_at = now() WHERE id = '7a5cff22-44eb-4be2-af38-73ab8de06602';
-- რომელია ისტორიაში ყველაზე ხანგრძლივი სამხედრო კონფლიქტი?
--   the Reconquista is the longest conflict; e46629f7 asks which war ran 335 years, a different question
UPDATE public.questions SET quality_status = NULL, quality_issues = NULL, updated_at = now() WHERE id = '097272c2-aa73-4535-9ae6-624c42610a2a';
-- ქართული ვაჟკაცობის სიმბოლო, გრძელპირიანი ცივი იარაღი?
--   the stem says long-bladed, which settles it as the sword
UPDATE public.questions SET quality_status = NULL, quality_issues = NULL, updated_at = now() WHERE id = '4208cf3b-9922-4c67-9107-1e601b3d1050';

-- ── right question, wrong category ───────────────────────────────────

-- რა არის ბიოლუმინესცენცია?
--   bioluminescence is biology
UPDATE public.questions SET category_id = '17a65a4f-22a9-4e41-b312-0990f68ff04e', quality_status = NULL, quality_issues = NULL, updated_at = now() WHERE id = 'fc01755c-9666-4be5-b0a7-c854cb7b3f22';
-- რას ნიშნავს ქართული იდიომი „ეშმაკის ქვირითი“?
--   a Georgian idiom, not an internet meme
UPDATE public.questions SET category_id = '3ddbd6b0-e031-4fa3-99ce-e8c1f89e193f', quality_status = NULL, quality_issues = NULL, updated_at = now() WHERE id = 'd9ff1b4a-2d4b-4aae-8f1f-806ced2a9d4b';
-- რომელ კომიქსების პერსონაჟს ჰქონდა მჭრელი კლანჭები?
--   Wolverine's claws are a comics question
UPDATE public.questions SET category_id = '0faf0fd6-dafc-4fb0-9719-dd639a089bbc', quality_status = NULL, quality_issues = NULL, updated_at = now() WHERE id = '9a9db818-24d9-413a-8071-98d2c2d7380b';
-- რომელ ფილმში ცდილობს ჯუდი ფოსტერი სერიული მკვლელის დაჭერას?
--   a feature film filed under television series
UPDATE public.questions SET category_id = 'cd03367e-62fd-425e-a81a-cd5664149e14', quality_status = NULL, quality_issues = NULL, updated_at = now() WHERE id = '1c0877ea-10b8-4831-8b4c-b522c8d79851';
-- რომელი 1999 წლის ფილმი მოგვითხრობს ეგვიპტოლოგების გუნდის მიერ მუმიას გახოცხლების ამბავზე
--   a 1999 feature film filed under television series
UPDATE public.questions SET category_id = 'cd03367e-62fd-425e-a81a-cd5664149e14', quality_status = NULL, quality_issues = NULL, updated_at = now() WHERE id = '3b964a5c-9a27-482f-8de7-24a91c62b2a8';
-- რომელმა ინდოელმა მათემატიკოსმა აღწერა ნული თავის „ბრაჰმასფუტასიდჰანტა“-ში?
--   Brahmagupta on zero is mathematics
UPDATE public.questions SET category_id = 'a9bd3fe7-d241-4265-86fd-eab21226bd49', quality_status = NULL, quality_issues = NULL, updated_at = now() WHERE id = 'bfd60840-8cbf-48ec-9919-c976d0c59fce';
-- რომელმა პროგრამისტმა შექმნა RSS-ის სპეციფიკაცია?
--   the RSS specification is software history
UPDATE public.questions SET category_id = '9a515acc-54fc-4bbf-80b1-cfa21cb7ceb3', quality_status = NULL, quality_issues = NULL, updated_at = now() WHERE id = '60c7c89d-7907-4740-8796-231781e0bc21';

-- ── left for a Georgian editor ───────────────────────────────────────
--
-- These stay flagged and stay in production, which is where they already
-- were. Each is an attribution this pass could neither confirm nor refute:
-- a title, a dedication, a fresco. Retiring them on a hunch would lose
-- questions that may be perfectly good.
--
--   03f2d7a3  ამ ჩამოთვლილ ქართველ მწერალთაგან რომელი იყო პროფესიით ექიმი?
--     „დავით კასრაძე“ as the writer-physician is unverified
--   98c21b7e  ვინ დაწერა „იავნანა“?
--     „იავნანა“ is a traditional lullaby with several settings; the flat attribution to Paliashvili cannot be checked
--   558a7260  ვინ დაწერა „იყო და არა იყო რა“?
--     „იყო და არა იყო რა“ attributed to Demna Shengelaia; its twin attributed the same title to Dumbadze and was retired
--   4ea9c160  ვინ შექმნა მონუმენტური ფრესკები, მათ შორის თბილისის უნივერსიტეტში?
--     the Tbilisi university frescoes are not attributed to Shalva Mikeladze in any standard source
--   dac0ee7a  ვინ ხელმძღვანელობდა სიონის მიმდებარე ტერიტორიის რეკონსტრუქციას 1980-ია
--     the 1980s Sioni-quarter reconstruction is not attributed to Kaplanishvili in any published source
--   92db9c0d  ვის ეკუთვნის ნაშრომი „ქართული ლექსის თეორია“?
--     the standard work on Georgian verse theory is Gatserelia's, not Tsereteli's
--   ebf4f7c2  ვის ეკუთვნის ცნობილი სამეცნიერო ნაშრომი ვარძიის მონასტრის შესახებ?
--     the standard Vardzia monograph is Taqaishvili's or Amiranashvili's, not Bakradze's
--   5ba2b31e  ვის უძღვნა ვაჟა-ფშაველამ პოემა „ალუდა ქეთელაური“?
--     „ალუდა ქეთელაური“ carries no dedication to Ilia that a standard edition records
--   047b4396  ილიას რომელი ნაწარმოების პერსონაჟია ოსმანი?
--     three questions place a character named Osman in three different works; at most one can be right
--   6a5072a0  რომელ ნაწარმოებში არის პერსონაჟი ოსმანი?
--     the second of the three Osman questions
--   c2a0c43f  რომელ ნაწარმოებში გვხვდება პერსონაჟი ოსმან აღა?
--     the third of the three Osman questions
--   e7b39f57  რომელ ქართველ მწერალს ეკუთვნის „დობილი“?
--     „დობილი“ is not a known Vazha title
--   5677308f  რომელი პოეტური კრებული ეკუთვნის ტიციან ტაბიძეს?
--     „ცისფერი ყანწები“ is offered as a wrong answer and is the better-known Titsian Tabidze association
--   e1ad333b  რომელი ქართული ცეკვის თავდაპირველი სახელია ფერხული?
--     Khorumi's original name being ფერხული is not established
--   0cf222cf  რომელია ქართული საგალობლების ერთ-ერთი ყველაზე ცნობილი კრებული?
--     names the Anchiskhati collection; the well-known chant collections are Shemokmedi and Gelati
--   795b4e99  რომელმა მეფემ შექმნა ანტი-ყიზილბაშური ალიანსი ოსმალეთთან?
--     Simon I rather than Luarsab I is usually the king associated with Ottoman dealings against the Qizilbash
--   e4976eac  რომელმა სამხედრო მოღვაწემ ითამაშა დიდი როლი ალექსანდროპოლის ციხესიმაგრ
--     Alexandropol fortress construction is not attributed to Andronikashvili in any standard source

COMMIT;

-- After this migration:
--   173 retired
--   51 repaired and returned to production
--   15 reviewed and unflagged
--   7 moved to the right category
--   17 left flagged for a Georgian editor
