
-- Insert 8 new auth users for mascot accounts
INSERT INTO auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, confirmation_token, raw_app_meta_data, raw_user_meta_data)
VALUES
('b1a2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'mascot-tornike@bot.local', '$2a$10$abcdefghijklmnopqrstuuABCDEFGHIJKLMNOPQRSTUVWXYZ012345', now(), now(), now(), '', '{"provider":"email","providers":["email"]}', '{"nickname":"Tornike"}'),
('c2b3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'mascot-nino@bot.local', '$2a$10$abcdefghijklmnopqrstuuABCDEFGHIJKLMNOPQRSTUVWXYZ012345', now(), now(), now(), '', '{"provider":"email","providers":["email"]}', '{"nickname":"Nino"}'),
('d3c4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'mascot-saba@bot.local', '$2a$10$abcdefghijklmnopqrstuuABCDEFGHIJKLMNOPQRSTUVWXYZ012345', now(), now(), now(), '', '{"provider":"email","providers":["email"]}', '{"nickname":"Saba"}'),
('e4d5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f8a', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'mascot-salome@bot.local', '$2a$10$abcdefghijklmnopqrstuuABCDEFGHIJKLMNOPQRSTUVWXYZ012345', now(), now(), now(), '', '{"provider":"email","providers":["email"]}', '{"nickname":"Salome"}'),
('f5e6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8a9b', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'mascot-dato@bot.local', '$2a$10$abcdefghijklmnopqrstuuABCDEFGHIJKLMNOPQRSTUVWXYZ012345', now(), now(), now(), '', '{"provider":"email","providers":["email"]}', '{"nickname":"Dato"}'),
('a6f7b8c9-d0e1-4f2a-3b4c-5d6e7f8a9b0c', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'mascot-keti@bot.local', '$2a$10$abcdefghijklmnopqrstuuABCDEFGHIJKLMNOPQRSTUVWXYZ012345', now(), now(), now(), '', '{"provider":"email","providers":["email"]}', '{"nickname":"Keti"}'),
('b7a8c9d0-e1f2-4a3b-4c5d-6e7f8a9b0c1d', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'mascot-irakli@bot.local', '$2a$10$abcdefghijklmnopqrstuuABCDEFGHIJKLMNOPQRSTUVWXYZ012345', now(), now(), now(), '', '{"provider":"email","providers":["email"]}', '{"nickname":"Irakli"}'),
('c8b9d0e1-f2a3-4b4c-5d6e-7f8a9b0c1d2e', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'mascot-tekla@bot.local', '$2a$10$abcdefghijklmnopqrstuuABCDEFGHIJKLMNOPQRSTUVWXYZ012345', now(), now(), now(), '', '{"provider":"email","providers":["email"]}', '{"nickname":"Tekla"}');

-- Update auto-created profiles with proper mascot data
UPDATE profiles SET nickname = 'Tornike', avatar_url = '/src/assets/avatars/mascot-avatar-1.png', country_code = 'GE', preferred_language = 'ka', region = 'ge', coins = 2900, games_played = 6, games_won = 3, total_points = 890, best_streak = 3 WHERE user_id = 'b1a2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d';
UPDATE profiles SET nickname = 'Nino', avatar_url = '/src/assets/avatars/mascot-avatar-2.png', country_code = 'GE', preferred_language = 'ka', region = 'ge', coins = 4500, games_played = 12, games_won = 7, total_points = 1650, best_streak = 5 WHERE user_id = 'c2b3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e';
UPDATE profiles SET nickname = 'Saba', avatar_url = '/src/assets/avatars/mascot-avatar-3.png', country_code = 'GE', preferred_language = 'ka', region = 'ge', coins = 1800, games_played = 3, games_won = 1, total_points = 420, best_streak = 2 WHERE user_id = 'd3c4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f';
UPDATE profiles SET nickname = 'Salome', avatar_url = '/src/assets/avatars/mascot-avatar-4.png', country_code = 'GE', preferred_language = 'ka', region = 'ge', coins = 3600, games_played = 8, games_won = 5, total_points = 1200, best_streak = 4 WHERE user_id = 'e4d5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f8a';
UPDATE profiles SET nickname = 'Dato', avatar_url = '/src/assets/avatars/mascot-avatar-5.png', country_code = 'GE', preferred_language = 'ka', region = 'ge', coins = 5100, games_played = 15, games_won = 9, total_points = 2100, best_streak = 6 WHERE user_id = 'f5e6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8a9b';
UPDATE profiles SET nickname = 'Keti', avatar_url = '/src/assets/avatars/mascot-avatar-6.png', country_code = 'GE', preferred_language = 'ka', region = 'ge', coins = 2200, games_played = 5, games_won = 2, total_points = 650, best_streak = 2 WHERE user_id = 'a6f7b8c9-d0e1-4f2a-3b4c-5d6e7f8a9b0c';
UPDATE profiles SET nickname = 'Irakli', avatar_url = '/src/assets/avatars/mascot-avatar-7.png', country_code = 'GE', preferred_language = 'ka', region = 'ge', coins = 3900, games_played = 10, games_won = 6, total_points = 1450, best_streak = 4 WHERE user_id = 'b7a8c9d0-e1f2-4a3b-4c5d-6e7f8a9b0c1d';
UPDATE profiles SET nickname = 'Tekla', avatar_url = '/src/assets/avatars/mascot-avatar-8.png', country_code = 'GE', preferred_language = 'ka', region = 'ge', coins = 2700, games_played = 4, games_won = 2, total_points = 780, best_streak = 3 WHERE user_id = 'c8b9d0e1-f2a3-4b4c-5d6e-7f8a9b0c1d2e';

-- Insert 8 mixed trivias (Georgian quotes replaced with standard quotes)
INSERT INTO user_quiz_posts (user_id, title, subject, question_count, answer_format, is_public, cover_gradient, likes_count, plays_count, saves_count, questions) VALUES

('b1a2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d', 'ყველაფერი ცოტ-ცოტა', 'სხვადასხვა', 5, '4_answers', true,
 'linear-gradient(135deg, #0C4A6E 0%, #0E7490 25%, #312E81 50%, #1E3A5F 75%, #134E4A 100%)', 12, 34, 5,
 '[{"question_text":"რომელია მსოფლიოში ყველაზე გრძელი მდინარე?","correct_answer":"ნილოსი","incorrect_answers":["ამაზონი","მისისიპი","იანძი"],"difficulty":"mixed","icon_slug":"river"},{"question_text":"რომელ წელს დაიწყო მეორე მსოფლიო ომი?","correct_answer":"1939","incorrect_answers":["1941","1938","1940"],"difficulty":"mixed","icon_slug":"war"},{"question_text":"რომელი ელემენტის ქიმიური სიმბოლოა Fe?","correct_answer":"რკინა","incorrect_answers":["ოქრო","ვერცხლი","სპილენძი"],"difficulty":"mixed","icon_slug":"science"},{"question_text":"რომელ ქალაქშია მოთავსებული კოლიზეუმი?","correct_answer":"რომი","incorrect_answers":["ათენი","პარიზი","მადრიდი"],"difficulty":"mixed","icon_slug":"landmark"},{"question_text":"რომელი ცხოველი ითვლება ყველაზე სწრაფ ხმელეთის ცხოველად?","correct_answer":"გეპარდი","incorrect_answers":["ლომი","ანტილოპა","ცხენი"],"difficulty":"mixed","icon_slug":"animal"}]'::jsonb),

('c2b3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e', 'შერეული ვიქტორინა', 'სხვადასხვა', 5, '4_answers', true,
 'linear-gradient(135deg, #7F1D1D 0%, #831843 25%, #991B1B 50%, #7F1D1D 75%, #6D1C4C 100%)', 8, 27, 3,
 '[{"question_text":"რომელი პლანეტაა მზის სისტემაში ყველაზე დიდი?","correct_answer":"იუპიტერი","incorrect_answers":["სატურნი","ნეპტუნი","ურანი"],"difficulty":"mixed","icon_slug":"planet"},{"question_text":"რომელ ქვეყანაში გამოიგონეს პიცა?","correct_answer":"იტალია","incorrect_answers":["საბერძნეთი","ესპანეთი","საფრანგეთი"],"difficulty":"mixed","icon_slug":"food"},{"question_text":"ვინ დაწერა ვეფხისტყაოსანი?","correct_answer":"შოთა რუსთაველი","incorrect_answers":["ილია ჭავჭავაძე","აკაკი წერეთელი","ნიკოლოზ ბარათაშვილი"],"difficulty":"mixed","icon_slug":"book"},{"question_text":"რომელი სპორტის ბურთი ყველაზე მძიმეა?","correct_answer":"ბოულინგის ბურთი","incorrect_answers":["კალათბურთის ბურთი","ფეხბურთის ბურთი","რაგბის ბურთი"],"difficulty":"mixed","icon_slug":"sports"},{"question_text":"რომელია ყველაზე პატარა ოკეანე?","correct_answer":"არქტიკული","incorrect_answers":["ინდოეთის","ატლანტის","წყნარი"],"difficulty":"mixed","icon_slug":"ocean"}]'::jsonb),

('d3c4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f', 'გამოიცანი!', 'სხვადასხვა', 5, '4_answers', true,
 'linear-gradient(135deg, #065F46 0%, #166534 25%, #3730A3 50%, #14532D 75%, #1E3A5F 100%)', 15, 42, 7,
 '[{"question_text":"რომელი ფილმით გახდა ცნობილი ლეონარდო დიკაპრიო?","correct_answer":"ტიტანიკი","incorrect_answers":["ინცეფშენი","შატერ აილენდი","ჯანგლის წიგნი"],"difficulty":"mixed","icon_slug":"movie"},{"question_text":"რამდენი კბილი აქვს ზრდასრულ ადამიანს?","correct_answer":"32","incorrect_answers":["28","30","34"],"difficulty":"mixed","icon_slug":"tooth"},{"question_text":"რომელი ქვეყნის დედაქალაქია ტოკიო?","correct_answer":"იაპონია","incorrect_answers":["ჩინეთი","სამხრეთ კორეა","ტაილანდი"],"difficulty":"mixed","icon_slug":"globe"},{"question_text":"რომელ წელს გაიმართა პირველი ოლიმპიური თამაშები თანამედროვე ეპოქაში?","correct_answer":"1896","incorrect_answers":["1900","1888","1904"],"difficulty":"mixed","icon_slug":"olympic"},{"question_text":"რა ფერისაა ზურმუხტი?","correct_answer":"მწვანე","incorrect_answers":["ლურჯი","წითელი","იასამნისფერი"],"difficulty":"mixed","icon_slug":"gem"}]'::jsonb),

('e4d5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f8a', 'ტესტი ერუდიტებისთვის', 'სხვადასხვა', 5, '4_answers', true,
 'linear-gradient(135deg, #5B21B6 0%, #4C1D95 25%, #581C87 50%, #6B21A8 75%, #4C1D95 100%)', 20, 55, 9,
 '[{"question_text":"რომელი მუსიკოსი ცნობილია როგორც პოპის მეფე?","correct_answer":"მაიკლ ჯექსონი","incorrect_answers":["ელვის პრესლი","პრინსი","ფრედი მერკური"],"difficulty":"mixed","icon_slug":"music"},{"question_text":"რომელია დედამიწაზე ყველაზე მშრალი უდაბნო?","correct_answer":"ატაკამა","incorrect_answers":["სახარა","გობი","კალაჰარი"],"difficulty":"mixed","icon_slug":"desert"},{"question_text":"რომელ ცხოველს შეუძლია ფერის შეცვლა?","correct_answer":"ქამელეონი","incorrect_answers":["იგუანა","გეკონი","გველი"],"difficulty":"mixed","icon_slug":"animal"},{"question_text":"რომელი ქვეყანა მოიგებს ფეხბურთის მსოფლიო ჩემპიონატს ყველაზე ხშირად?","correct_answer":"ბრაზილია","incorrect_answers":["გერმანია","იტალია","არგენტინა"],"difficulty":"mixed","icon_slug":"football"},{"question_text":"რა ჰქვია ადამიანის ყველაზე დიდ ორგანოს?","correct_answer":"კანი","incorrect_answers":["ღვიძლი","ტვინი","ფილტვები"],"difficulty":"mixed","icon_slug":"body"}]'::jsonb),

('f5e6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8a9b', 'მრავალფეროვანი კითხვები', 'სხვადასხვა', 5, '4_answers', true,
 'linear-gradient(135deg, #78350F 0%, #92400E 25%, #7C2D12 50%, #854D0E 75%, #78350F 100%)', 6, 19, 2,
 '[{"question_text":"რომელი ლითონი თხევადია ოთახის ტემპერატურაზე?","correct_answer":"ვერცხლისწყალი","incorrect_answers":["ტყვია","კალა","თუთია"],"difficulty":"mixed","icon_slug":"science"},{"question_text":"რომელ ქვეყანაში მდებარეობს მაჩუ-პიჩუ?","correct_answer":"პერუ","incorrect_answers":["ბოლივია","ეკვადორი","კოლუმბია"],"difficulty":"mixed","icon_slug":"landmark"},{"question_text":"ვინ გამოიგონა ტელეფონი?","correct_answer":"ალექსანდერ გრეიამ ბელი","incorrect_answers":["თომას ედისონი","ნიკოლა ტესლა","გულიელმო მარკონი"],"difficulty":"mixed","icon_slug":"phone"},{"question_text":"რომელ სერიალშია პერსონაჟი უოლტერ უაითი?","correct_answer":"Breaking Bad","incorrect_answers":["Game of Thrones","The Wire","Lost"],"difficulty":"mixed","icon_slug":"tv"},{"question_text":"რომელი ფრინველია ყველაზე სწრაფი?","correct_answer":"ფსირტოს შევარდენი","incorrect_answers":["არწივი","ფინჩი","სტრიჟი"],"difficulty":"mixed","icon_slug":"bird"}]'::jsonb),

('a6f7b8c9-d0e1-4f2a-3b4c-5d6e7f8a9b0c', 'ვინ იცის მეტი?', 'სხვადასხვა', 5, '4_answers', true,
 'linear-gradient(135deg, #831843 0%, #7C2D12 25%, #115E59 50%, #9A3412 75%, #831843 100%)', 10, 31, 4,
 '[{"question_text":"რომელია მსოფლიოში ყველაზე მაღალი მთა?","correct_answer":"ევერესტი","incorrect_answers":["კ-2","კანჩენჯუნგა","მაკალუ"],"difficulty":"mixed","icon_slug":"mountain"},{"question_text":"რომელი სამზარეულო კერძია იაპონურ სამზარეულოში ყველაზე ცნობილი?","correct_answer":"სუში","incorrect_answers":["რამენი","ტემპურა","უდონი"],"difficulty":"mixed","icon_slug":"food"},{"question_text":"რომელ წელს დაეცა ბერლინის კედელი?","correct_answer":"1989","incorrect_answers":["1991","1987","1990"],"difficulty":"mixed","icon_slug":"wall"},{"question_text":"რომელ ფილმს აქვს ყველაზე მეტი ოსკარი?","correct_answer":"ტიტანიკი","incorrect_answers":["მბრძანებელი ბეჭდების","ბენ-ჰური","გოდფადერი"],"difficulty":"mixed","icon_slug":"movie"},{"question_text":"DNA-ის რომელი ფორმა ყველაზე გავრცელებულია?","correct_answer":"B-ფორმა","incorrect_answers":["A-ფორმა","Z-ფორმა","C-ფორმა"],"difficulty":"mixed","icon_slug":"dna"}]'::jsonb),

('b7a8c9d0-e1f2-4a3b-4c5d-6e7f8a9b0c1d', 'ინტელექტის ტესტი', 'სხვადასხვა', 5, '4_answers', true,
 'linear-gradient(135deg, #1E1B4B 0%, #3730A3 25%, #312E81 50%, #2E1065 75%, #1E1B4B 100%)', 17, 48, 8,
 '[{"question_text":"რომელი ქვეყნის დროშაზეა მაპლის ფოთოლი?","correct_answer":"კანადა","incorrect_answers":["ავსტრალია","ახალი ზელანდია","ირლანდია"],"difficulty":"mixed","icon_slug":"flag"},{"question_text":"რომელ პლანეტას ეწოდება წითელი პლანეტა?","correct_answer":"მარსი","incorrect_answers":["ვენერა","იუპიტერი","მერკური"],"difficulty":"mixed","icon_slug":"planet"},{"question_text":"რომელი სპორტსმენია ფეხბურთის ისტორიაში ყველაზე მეტი გოლის ავტორი?","correct_answer":"კრიშტიანუ რონალდუ","incorrect_answers":["ლეო მესი","პელე","მარადონა"],"difficulty":"mixed","icon_slug":"football"},{"question_text":"რომელი ვიტამინი წარმოიქმნება მზის სხივების ზემოქმედებით?","correct_answer":"D ვიტამინი","incorrect_answers":["C ვიტამინი","A ვიტამინი","B ვიტამინი"],"difficulty":"mixed","icon_slug":"sun"},{"question_text":"რომელ ქალაქშია მოთავსებული ეიფელის კოშკი?","correct_answer":"პარიზი","incorrect_answers":["ლონდონი","ბერლინი","რომი"],"difficulty":"mixed","icon_slug":"tower"}]'::jsonb),

('c8b9d0e1-f2a3-4b4c-5d6e-7f8a9b0c1d2e', 'ერუდიციის გამოწვევა', 'სხვადასხვა', 5, '4_answers', true,
 'linear-gradient(135deg, #0369A1 0%, #115E59 25%, #3F6212 50%, #0284C7 75%, #166534 100%)', 14, 39, 6,
 '[{"question_text":"რომელი ოკეანეა ყველაზე ღრმა?","correct_answer":"წყნარი ოკეანე","incorrect_answers":["ატლანტის ოკეანე","ინდოეთის ოკეანე","სამხრეთ ოკეანე"],"difficulty":"mixed","icon_slug":"ocean"},{"question_text":"რომელმა მხატვარმა დახატა მონა ლიზა?","correct_answer":"ლეონარდო და ვინჩი","incorrect_answers":["მიქელანჯელო","რაფაელი","რემბრანდტი"],"difficulty":"mixed","icon_slug":"art"},{"question_text":"რომელი მწერია ყველაზე სწრაფი?","correct_answer":"ჭიანჭველა","incorrect_answers":["პეპელა","ხოჭო","ფუტკარი"],"difficulty":"mixed","icon_slug":"insect"},{"question_text":"რომელ ქვეყანაში გამოიგონეს შოკოლადი?","correct_answer":"მექსიკა","incorrect_answers":["შვეიცარია","ბელგია","საფრანგეთი"],"difficulty":"mixed","icon_slug":"chocolate"},{"question_text":"რომელ წელს გაფრინდა პირველი ადამიანი კოსმოსში?","correct_answer":"1961","incorrect_answers":["1957","1965","1969"],"difficulty":"mixed","icon_slug":"rocket"}]'::jsonb);
