-- National categories for the non-Georgian locales: History, Cuisine,
-- Culture and Literature per language, the same treatment Georgian has.
--
-- Generated by scripts/national-categories/build-migration.py.
-- Regenerate rather than editing by hand. Idempotent: uuid5 ids and
-- ON CONFLICT DO NOTHING throughout.

BEGIN;

-- ══ german_history (de) ══
INSERT INTO public.categories (id, category_id, name, icon, color, type, is_active, total_levels, sort_order, language, is_language_specific)
VALUES ('042ed4d1-7433-5c19-9bdf-64d7a1df2d63', 'german_history', 'Deutsche Geschichte', '🏛️', 'from-amber-400 to-orange-500', 'classic', true, 1, 60, 'de', true)
ON CONFLICT (category_id) DO NOTHING;
INSERT INTO public.category_translations (category_id, language, name) VALUES
  ('042ed4d1-7433-5c19-9bdf-64d7a1df2d63', 'en', 'German History'),
  ('042ed4d1-7433-5c19-9bdf-64d7a1df2d63', 'ka', 'გერმანიის ისტორია'),
  ('042ed4d1-7433-5c19-9bdf-64d7a1df2d63', 'de', 'Deutsche Geschichte'),
  ('042ed4d1-7433-5c19-9bdf-64d7a1df2d63', 'es', 'Historia alemana'),
  ('042ed4d1-7433-5c19-9bdf-64d7a1df2d63', 'fr', 'Histoire allemande'),
  ('042ed4d1-7433-5c19-9bdf-64d7a1df2d63', 'it', 'Storia tedesca'),
  ('042ed4d1-7433-5c19-9bdf-64d7a1df2d63', 'pt', 'História alemã')
ON CONFLICT (category_id, language) DO NOTHING;

-- ══ german_cuisine (de) ══
INSERT INTO public.categories (id, category_id, name, icon, color, type, is_active, total_levels, sort_order, language, is_language_specific)
VALUES ('223b7bfc-ab60-5d48-bb24-7271a4089fdd', 'german_cuisine', 'Deutsche Küche', '🍲', 'from-red-400 to-rose-500', 'classic', true, 1, 65, 'de', true)
ON CONFLICT (category_id) DO NOTHING;
INSERT INTO public.category_translations (category_id, language, name) VALUES
  ('223b7bfc-ab60-5d48-bb24-7271a4089fdd', 'en', 'German Cuisine'),
  ('223b7bfc-ab60-5d48-bb24-7271a4089fdd', 'ka', 'გერმანიის სამზარეულო'),
  ('223b7bfc-ab60-5d48-bb24-7271a4089fdd', 'de', 'Deutsche Küche'),
  ('223b7bfc-ab60-5d48-bb24-7271a4089fdd', 'es', 'Cocina alemana'),
  ('223b7bfc-ab60-5d48-bb24-7271a4089fdd', 'fr', 'Cuisine allemande'),
  ('223b7bfc-ab60-5d48-bb24-7271a4089fdd', 'it', 'Cucina tedesca'),
  ('223b7bfc-ab60-5d48-bb24-7271a4089fdd', 'pt', 'Cozinha alemã')
ON CONFLICT (category_id, language) DO NOTHING;

-- ══ german_culture (de) ══
INSERT INTO public.categories (id, category_id, name, icon, color, type, is_active, total_levels, sort_order, language, is_language_specific)
VALUES ('db2f913e-485c-52f9-ad7d-e24a849f5ba0', 'german_culture', 'Deutsche Kultur', '🎭', 'from-purple-400 to-violet-500', 'classic', true, 1, 70, 'de', true)
ON CONFLICT (category_id) DO NOTHING;
INSERT INTO public.category_translations (category_id, language, name) VALUES
  ('db2f913e-485c-52f9-ad7d-e24a849f5ba0', 'en', 'German Culture'),
  ('db2f913e-485c-52f9-ad7d-e24a849f5ba0', 'ka', 'გერმანიის კულტურა'),
  ('db2f913e-485c-52f9-ad7d-e24a849f5ba0', 'de', 'Deutsche Kultur'),
  ('db2f913e-485c-52f9-ad7d-e24a849f5ba0', 'es', 'Cultura alemana'),
  ('db2f913e-485c-52f9-ad7d-e24a849f5ba0', 'fr', 'Culture allemande'),
  ('db2f913e-485c-52f9-ad7d-e24a849f5ba0', 'it', 'Cultura tedesca'),
  ('db2f913e-485c-52f9-ad7d-e24a849f5ba0', 'pt', 'Cultura alemã')
ON CONFLICT (category_id, language) DO NOTHING;

-- ══ german_literature (de) ══
INSERT INTO public.categories (id, category_id, name, icon, color, type, is_active, total_levels, sort_order, language, is_language_specific)
VALUES ('c34531f3-996f-51cb-96c9-7eb721458e67', 'german_literature', 'Deutsche Literatur', '📚', 'from-blue-400 to-indigo-500', 'classic', true, 1, 75, 'de', true)
ON CONFLICT (category_id) DO NOTHING;
INSERT INTO public.category_translations (category_id, language, name) VALUES
  ('c34531f3-996f-51cb-96c9-7eb721458e67', 'en', 'German Literature'),
  ('c34531f3-996f-51cb-96c9-7eb721458e67', 'ka', 'გერმანიის ლიტერატურა'),
  ('c34531f3-996f-51cb-96c9-7eb721458e67', 'de', 'Deutsche Literatur'),
  ('c34531f3-996f-51cb-96c9-7eb721458e67', 'es', 'Literatura alemana'),
  ('c34531f3-996f-51cb-96c9-7eb721458e67', 'fr', 'Littérature allemande'),
  ('c34531f3-996f-51cb-96c9-7eb721458e67', 'it', 'Letteratura tedesca'),
  ('c34531f3-996f-51cb-96c9-7eb721458e67', 'pt', 'Literatura alemã')
ON CONFLICT (category_id, language) DO NOTHING;

-- ══ spanish_history (es) ══
INSERT INTO public.categories (id, category_id, name, icon, color, type, is_active, total_levels, sort_order, language, is_language_specific)
VALUES ('3038a8cf-c7b5-5c97-afbc-bf41856b6dd0', 'spanish_history', 'Historia de España', '🏛️', 'from-amber-400 to-orange-500', 'classic', true, 1, 60, 'es', true)
ON CONFLICT (category_id) DO NOTHING;
INSERT INTO public.category_translations (category_id, language, name) VALUES
  ('3038a8cf-c7b5-5c97-afbc-bf41856b6dd0', 'en', 'Spanish History'),
  ('3038a8cf-c7b5-5c97-afbc-bf41856b6dd0', 'ka', 'ესპანეთის ისტორია'),
  ('3038a8cf-c7b5-5c97-afbc-bf41856b6dd0', 'de', 'Spanische Geschichte'),
  ('3038a8cf-c7b5-5c97-afbc-bf41856b6dd0', 'es', 'Historia de España'),
  ('3038a8cf-c7b5-5c97-afbc-bf41856b6dd0', 'fr', 'Histoire espagnole'),
  ('3038a8cf-c7b5-5c97-afbc-bf41856b6dd0', 'it', 'Storia spagnola'),
  ('3038a8cf-c7b5-5c97-afbc-bf41856b6dd0', 'pt', 'História espanhola')
ON CONFLICT (category_id, language) DO NOTHING;

-- ══ spanish_cuisine (es) ══
INSERT INTO public.categories (id, category_id, name, icon, color, type, is_active, total_levels, sort_order, language, is_language_specific)
VALUES ('437d26ab-6d73-5abc-8644-474254dbcff7', 'spanish_cuisine', 'Cocina española', '🍲', 'from-red-400 to-rose-500', 'classic', true, 1, 65, 'es', true)
ON CONFLICT (category_id) DO NOTHING;
INSERT INTO public.category_translations (category_id, language, name) VALUES
  ('437d26ab-6d73-5abc-8644-474254dbcff7', 'en', 'Spanish Cuisine'),
  ('437d26ab-6d73-5abc-8644-474254dbcff7', 'ka', 'ესპანეთის სამზარეულო'),
  ('437d26ab-6d73-5abc-8644-474254dbcff7', 'de', 'Spanische Küche'),
  ('437d26ab-6d73-5abc-8644-474254dbcff7', 'es', 'Cocina española'),
  ('437d26ab-6d73-5abc-8644-474254dbcff7', 'fr', 'Cuisine espagnole'),
  ('437d26ab-6d73-5abc-8644-474254dbcff7', 'it', 'Cucina spagnola'),
  ('437d26ab-6d73-5abc-8644-474254dbcff7', 'pt', 'Cozinha espanhola')
ON CONFLICT (category_id, language) DO NOTHING;

-- ══ spanish_culture (es) ══
INSERT INTO public.categories (id, category_id, name, icon, color, type, is_active, total_levels, sort_order, language, is_language_specific)
VALUES ('eb6093a2-a473-5b6c-a3b5-457ec8483906', 'spanish_culture', 'Cultura española', '🎭', 'from-purple-400 to-violet-500', 'classic', true, 1, 70, 'es', true)
ON CONFLICT (category_id) DO NOTHING;
INSERT INTO public.category_translations (category_id, language, name) VALUES
  ('eb6093a2-a473-5b6c-a3b5-457ec8483906', 'en', 'Spanish Culture'),
  ('eb6093a2-a473-5b6c-a3b5-457ec8483906', 'ka', 'ესპანეთის კულტურა'),
  ('eb6093a2-a473-5b6c-a3b5-457ec8483906', 'de', 'Spanische Kultur'),
  ('eb6093a2-a473-5b6c-a3b5-457ec8483906', 'es', 'Cultura española'),
  ('eb6093a2-a473-5b6c-a3b5-457ec8483906', 'fr', 'Culture espagnole'),
  ('eb6093a2-a473-5b6c-a3b5-457ec8483906', 'it', 'Cultura spagnola'),
  ('eb6093a2-a473-5b6c-a3b5-457ec8483906', 'pt', 'Cultura espanhola')
ON CONFLICT (category_id, language) DO NOTHING;

-- ══ spanish_literature (es) ══
INSERT INTO public.categories (id, category_id, name, icon, color, type, is_active, total_levels, sort_order, language, is_language_specific)
VALUES ('df520dc0-016d-5aac-bc0b-55bf76d63c27', 'spanish_literature', 'Literatura española', '📚', 'from-blue-400 to-indigo-500', 'classic', true, 1, 75, 'es', true)
ON CONFLICT (category_id) DO NOTHING;
INSERT INTO public.category_translations (category_id, language, name) VALUES
  ('df520dc0-016d-5aac-bc0b-55bf76d63c27', 'en', 'Spanish Literature'),
  ('df520dc0-016d-5aac-bc0b-55bf76d63c27', 'ka', 'ესპანეთის ლიტერატურა'),
  ('df520dc0-016d-5aac-bc0b-55bf76d63c27', 'de', 'Spanische Literatur'),
  ('df520dc0-016d-5aac-bc0b-55bf76d63c27', 'es', 'Literatura española'),
  ('df520dc0-016d-5aac-bc0b-55bf76d63c27', 'fr', 'Littérature espagnole'),
  ('df520dc0-016d-5aac-bc0b-55bf76d63c27', 'it', 'Letteratura spagnola'),
  ('df520dc0-016d-5aac-bc0b-55bf76d63c27', 'pt', 'Literatura espanhola')
ON CONFLICT (category_id, language) DO NOTHING;

-- ══ french_history (fr) ══
INSERT INTO public.categories (id, category_id, name, icon, color, type, is_active, total_levels, sort_order, language, is_language_specific)
VALUES ('1cd3683e-29cf-5980-a7a1-fa7c689770a3', 'french_history', 'Histoire de France', '🏛️', 'from-amber-400 to-orange-500', 'classic', true, 1, 60, 'fr', true)
ON CONFLICT (category_id) DO NOTHING;
INSERT INTO public.category_translations (category_id, language, name) VALUES
  ('1cd3683e-29cf-5980-a7a1-fa7c689770a3', 'en', 'French History'),
  ('1cd3683e-29cf-5980-a7a1-fa7c689770a3', 'ka', 'საფრანგეთის ისტორია'),
  ('1cd3683e-29cf-5980-a7a1-fa7c689770a3', 'de', 'Französische Geschichte'),
  ('1cd3683e-29cf-5980-a7a1-fa7c689770a3', 'es', 'Historia francesa'),
  ('1cd3683e-29cf-5980-a7a1-fa7c689770a3', 'fr', 'Histoire de France'),
  ('1cd3683e-29cf-5980-a7a1-fa7c689770a3', 'it', 'Storia francese'),
  ('1cd3683e-29cf-5980-a7a1-fa7c689770a3', 'pt', 'História francesa')
ON CONFLICT (category_id, language) DO NOTHING;

-- ══ french_cuisine (fr) ══
INSERT INTO public.categories (id, category_id, name, icon, color, type, is_active, total_levels, sort_order, language, is_language_specific)
VALUES ('0698afdb-0c70-57b3-a6ed-51acf4a83a1d', 'french_cuisine', 'Cuisine française', '🍲', 'from-red-400 to-rose-500', 'classic', true, 1, 65, 'fr', true)
ON CONFLICT (category_id) DO NOTHING;
INSERT INTO public.category_translations (category_id, language, name) VALUES
  ('0698afdb-0c70-57b3-a6ed-51acf4a83a1d', 'en', 'French Cuisine'),
  ('0698afdb-0c70-57b3-a6ed-51acf4a83a1d', 'ka', 'საფრანგეთის სამზარეულო'),
  ('0698afdb-0c70-57b3-a6ed-51acf4a83a1d', 'de', 'Französische Küche'),
  ('0698afdb-0c70-57b3-a6ed-51acf4a83a1d', 'es', 'Cocina francesa'),
  ('0698afdb-0c70-57b3-a6ed-51acf4a83a1d', 'fr', 'Cuisine française'),
  ('0698afdb-0c70-57b3-a6ed-51acf4a83a1d', 'it', 'Cucina francese'),
  ('0698afdb-0c70-57b3-a6ed-51acf4a83a1d', 'pt', 'Cozinha francesa')
ON CONFLICT (category_id, language) DO NOTHING;

-- ══ french_culture (fr) ══
INSERT INTO public.categories (id, category_id, name, icon, color, type, is_active, total_levels, sort_order, language, is_language_specific)
VALUES ('6ae77dc7-4861-53bd-a5ff-bac1fab3ac50', 'french_culture', 'Culture française', '🎭', 'from-purple-400 to-violet-500', 'classic', true, 1, 70, 'fr', true)
ON CONFLICT (category_id) DO NOTHING;
INSERT INTO public.category_translations (category_id, language, name) VALUES
  ('6ae77dc7-4861-53bd-a5ff-bac1fab3ac50', 'en', 'French Culture'),
  ('6ae77dc7-4861-53bd-a5ff-bac1fab3ac50', 'ka', 'საფრანგეთის კულტურა'),
  ('6ae77dc7-4861-53bd-a5ff-bac1fab3ac50', 'de', 'Französische Kultur'),
  ('6ae77dc7-4861-53bd-a5ff-bac1fab3ac50', 'es', 'Cultura francesa'),
  ('6ae77dc7-4861-53bd-a5ff-bac1fab3ac50', 'fr', 'Culture française'),
  ('6ae77dc7-4861-53bd-a5ff-bac1fab3ac50', 'it', 'Cultura francese'),
  ('6ae77dc7-4861-53bd-a5ff-bac1fab3ac50', 'pt', 'Cultura francesa')
ON CONFLICT (category_id, language) DO NOTHING;

-- ══ french_literature (fr) ══
INSERT INTO public.categories (id, category_id, name, icon, color, type, is_active, total_levels, sort_order, language, is_language_specific)
VALUES ('d4b751b4-9188-5bab-9238-45ed1b4e7e6b', 'french_literature', 'Littérature française', '📚', 'from-blue-400 to-indigo-500', 'classic', true, 1, 75, 'fr', true)
ON CONFLICT (category_id) DO NOTHING;
INSERT INTO public.category_translations (category_id, language, name) VALUES
  ('d4b751b4-9188-5bab-9238-45ed1b4e7e6b', 'en', 'French Literature'),
  ('d4b751b4-9188-5bab-9238-45ed1b4e7e6b', 'ka', 'საფრანგეთის ლიტერატურა'),
  ('d4b751b4-9188-5bab-9238-45ed1b4e7e6b', 'de', 'Französische Literatur'),
  ('d4b751b4-9188-5bab-9238-45ed1b4e7e6b', 'es', 'Literatura francesa'),
  ('d4b751b4-9188-5bab-9238-45ed1b4e7e6b', 'fr', 'Littérature française'),
  ('d4b751b4-9188-5bab-9238-45ed1b4e7e6b', 'it', 'Letteratura francese'),
  ('d4b751b4-9188-5bab-9238-45ed1b4e7e6b', 'pt', 'Literatura francesa')
ON CONFLICT (category_id, language) DO NOTHING;

-- ══ italian_history (it) ══
INSERT INTO public.categories (id, category_id, name, icon, color, type, is_active, total_levels, sort_order, language, is_language_specific)
VALUES ('dd1171f5-5372-5fe6-a02d-9a16c82e980e', 'italian_history', 'Storia d''Italia', '🏛️', 'from-amber-400 to-orange-500', 'classic', true, 1, 60, 'it', true)
ON CONFLICT (category_id) DO NOTHING;
INSERT INTO public.category_translations (category_id, language, name) VALUES
  ('dd1171f5-5372-5fe6-a02d-9a16c82e980e', 'en', 'Italian History'),
  ('dd1171f5-5372-5fe6-a02d-9a16c82e980e', 'ka', 'იტალიის ისტორია'),
  ('dd1171f5-5372-5fe6-a02d-9a16c82e980e', 'de', 'Italienische Geschichte'),
  ('dd1171f5-5372-5fe6-a02d-9a16c82e980e', 'es', 'Historia italiana'),
  ('dd1171f5-5372-5fe6-a02d-9a16c82e980e', 'fr', 'Histoire italienne'),
  ('dd1171f5-5372-5fe6-a02d-9a16c82e980e', 'it', 'Storia d''Italia'),
  ('dd1171f5-5372-5fe6-a02d-9a16c82e980e', 'pt', 'História italiana')
ON CONFLICT (category_id, language) DO NOTHING;

-- ══ italian_cuisine (it) ══
INSERT INTO public.categories (id, category_id, name, icon, color, type, is_active, total_levels, sort_order, language, is_language_specific)
VALUES ('9f97d9fa-d58f-5560-a5de-dfe61bacb512', 'italian_cuisine', 'Cucina italiana', '🍲', 'from-red-400 to-rose-500', 'classic', true, 1, 65, 'it', true)
ON CONFLICT (category_id) DO NOTHING;
INSERT INTO public.category_translations (category_id, language, name) VALUES
  ('9f97d9fa-d58f-5560-a5de-dfe61bacb512', 'en', 'Italian Cuisine'),
  ('9f97d9fa-d58f-5560-a5de-dfe61bacb512', 'ka', 'იტალიის სამზარეულო'),
  ('9f97d9fa-d58f-5560-a5de-dfe61bacb512', 'de', 'Italienische Küche'),
  ('9f97d9fa-d58f-5560-a5de-dfe61bacb512', 'es', 'Cocina italiana'),
  ('9f97d9fa-d58f-5560-a5de-dfe61bacb512', 'fr', 'Cuisine italienne'),
  ('9f97d9fa-d58f-5560-a5de-dfe61bacb512', 'it', 'Cucina italiana'),
  ('9f97d9fa-d58f-5560-a5de-dfe61bacb512', 'pt', 'Cozinha italiana')
ON CONFLICT (category_id, language) DO NOTHING;

-- ══ italian_culture (it) ══
INSERT INTO public.categories (id, category_id, name, icon, color, type, is_active, total_levels, sort_order, language, is_language_specific)
VALUES ('17f6e2fa-e1da-5f44-8018-0cd91cfa3cf2', 'italian_culture', 'Cultura italiana', '🎭', 'from-purple-400 to-violet-500', 'classic', true, 1, 70, 'it', true)
ON CONFLICT (category_id) DO NOTHING;
INSERT INTO public.category_translations (category_id, language, name) VALUES
  ('17f6e2fa-e1da-5f44-8018-0cd91cfa3cf2', 'en', 'Italian Culture'),
  ('17f6e2fa-e1da-5f44-8018-0cd91cfa3cf2', 'ka', 'იტალიის კულტურა'),
  ('17f6e2fa-e1da-5f44-8018-0cd91cfa3cf2', 'de', 'Italienische Kultur'),
  ('17f6e2fa-e1da-5f44-8018-0cd91cfa3cf2', 'es', 'Cultura italiana'),
  ('17f6e2fa-e1da-5f44-8018-0cd91cfa3cf2', 'fr', 'Culture italienne'),
  ('17f6e2fa-e1da-5f44-8018-0cd91cfa3cf2', 'it', 'Cultura italiana'),
  ('17f6e2fa-e1da-5f44-8018-0cd91cfa3cf2', 'pt', 'Cultura italiana')
ON CONFLICT (category_id, language) DO NOTHING;

-- ══ italian_literature (it) ══
INSERT INTO public.categories (id, category_id, name, icon, color, type, is_active, total_levels, sort_order, language, is_language_specific)
VALUES ('ba3b8eaf-466c-55f3-9973-ebbeedcf0d01', 'italian_literature', 'Letteratura italiana', '📚', 'from-blue-400 to-indigo-500', 'classic', true, 1, 75, 'it', true)
ON CONFLICT (category_id) DO NOTHING;
INSERT INTO public.category_translations (category_id, language, name) VALUES
  ('ba3b8eaf-466c-55f3-9973-ebbeedcf0d01', 'en', 'Italian Literature'),
  ('ba3b8eaf-466c-55f3-9973-ebbeedcf0d01', 'ka', 'იტალიის ლიტერატურა'),
  ('ba3b8eaf-466c-55f3-9973-ebbeedcf0d01', 'de', 'Italienische Literatur'),
  ('ba3b8eaf-466c-55f3-9973-ebbeedcf0d01', 'es', 'Literatura italiana'),
  ('ba3b8eaf-466c-55f3-9973-ebbeedcf0d01', 'fr', 'Littérature italienne'),
  ('ba3b8eaf-466c-55f3-9973-ebbeedcf0d01', 'it', 'Letteratura italiana'),
  ('ba3b8eaf-466c-55f3-9973-ebbeedcf0d01', 'pt', 'Literatura italiana')
ON CONFLICT (category_id, language) DO NOTHING;

-- ══ portuguese_history (pt) ══
INSERT INTO public.categories (id, category_id, name, icon, color, type, is_active, total_levels, sort_order, language, is_language_specific)
VALUES ('5d0262f1-c95a-51e2-bf55-437aa11e2a0d', 'portuguese_history', 'História Portuguesa', '🏛️', 'from-amber-400 to-orange-500', 'classic', true, 1, 60, 'pt', true)
ON CONFLICT (category_id) DO NOTHING;
INSERT INTO public.category_translations (category_id, language, name) VALUES
  ('5d0262f1-c95a-51e2-bf55-437aa11e2a0d', 'en', 'Portuguese History'),
  ('5d0262f1-c95a-51e2-bf55-437aa11e2a0d', 'ka', 'პორტუგალიის ისტორია'),
  ('5d0262f1-c95a-51e2-bf55-437aa11e2a0d', 'de', 'Portugiesische Geschichte'),
  ('5d0262f1-c95a-51e2-bf55-437aa11e2a0d', 'es', 'Historia portuguesa'),
  ('5d0262f1-c95a-51e2-bf55-437aa11e2a0d', 'fr', 'Histoire portugaise'),
  ('5d0262f1-c95a-51e2-bf55-437aa11e2a0d', 'it', 'Storia portoghese'),
  ('5d0262f1-c95a-51e2-bf55-437aa11e2a0d', 'pt', 'História Portuguesa')
ON CONFLICT (category_id, language) DO NOTHING;

-- ══ portuguese_cuisine (pt) ══
INSERT INTO public.categories (id, category_id, name, icon, color, type, is_active, total_levels, sort_order, language, is_language_specific)
VALUES ('1bb74074-be17-51d8-a96f-313d07f2d843', 'portuguese_cuisine', 'Cozinha Portuguesa', '🍲', 'from-red-400 to-rose-500', 'classic', true, 1, 65, 'pt', true)
ON CONFLICT (category_id) DO NOTHING;
INSERT INTO public.category_translations (category_id, language, name) VALUES
  ('1bb74074-be17-51d8-a96f-313d07f2d843', 'en', 'Portuguese Cuisine'),
  ('1bb74074-be17-51d8-a96f-313d07f2d843', 'ka', 'პორტუგალიის სამზარეულო'),
  ('1bb74074-be17-51d8-a96f-313d07f2d843', 'de', 'Portugiesische Küche'),
  ('1bb74074-be17-51d8-a96f-313d07f2d843', 'es', 'Cocina portuguesa'),
  ('1bb74074-be17-51d8-a96f-313d07f2d843', 'fr', 'Cuisine portugaise'),
  ('1bb74074-be17-51d8-a96f-313d07f2d843', 'it', 'Cucina portoghese'),
  ('1bb74074-be17-51d8-a96f-313d07f2d843', 'pt', 'Cozinha Portuguesa')
ON CONFLICT (category_id, language) DO NOTHING;

-- ══ portuguese_culture (pt) ══
INSERT INTO public.categories (id, category_id, name, icon, color, type, is_active, total_levels, sort_order, language, is_language_specific)
VALUES ('c597facc-3174-5195-922a-58d53831583f', 'portuguese_culture', 'Cultura Portuguesa', '🎭', 'from-purple-400 to-violet-500', 'classic', true, 1, 70, 'pt', true)
ON CONFLICT (category_id) DO NOTHING;
INSERT INTO public.category_translations (category_id, language, name) VALUES
  ('c597facc-3174-5195-922a-58d53831583f', 'en', 'Portuguese Culture'),
  ('c597facc-3174-5195-922a-58d53831583f', 'ka', 'პორტუგალიის კულტურა'),
  ('c597facc-3174-5195-922a-58d53831583f', 'de', 'Portugiesische Kultur'),
  ('c597facc-3174-5195-922a-58d53831583f', 'es', 'Cultura portuguesa'),
  ('c597facc-3174-5195-922a-58d53831583f', 'fr', 'Culture portugaise'),
  ('c597facc-3174-5195-922a-58d53831583f', 'it', 'Cultura portoghese'),
  ('c597facc-3174-5195-922a-58d53831583f', 'pt', 'Cultura Portuguesa')
ON CONFLICT (category_id, language) DO NOTHING;

-- ══ portuguese_literature (pt) ══
INSERT INTO public.categories (id, category_id, name, icon, color, type, is_active, total_levels, sort_order, language, is_language_specific)
VALUES ('ef3e583e-3282-5f14-8db3-9f31e5dcac39', 'portuguese_literature', 'Literatura Portuguesa', '📚', 'from-blue-400 to-indigo-500', 'classic', true, 1, 75, 'pt', true)
ON CONFLICT (category_id) DO NOTHING;
INSERT INTO public.category_translations (category_id, language, name) VALUES
  ('ef3e583e-3282-5f14-8db3-9f31e5dcac39', 'en', 'Portuguese Literature'),
  ('ef3e583e-3282-5f14-8db3-9f31e5dcac39', 'ka', 'პორტუგალიის ლიტერატურა'),
  ('ef3e583e-3282-5f14-8db3-9f31e5dcac39', 'de', 'Portugiesische Literatur'),
  ('ef3e583e-3282-5f14-8db3-9f31e5dcac39', 'es', 'Literatura portuguesa'),
  ('ef3e583e-3282-5f14-8db3-9f31e5dcac39', 'fr', 'Littérature portugaise'),
  ('ef3e583e-3282-5f14-8db3-9f31e5dcac39', 'it', 'Letteratura portoghese'),
  ('ef3e583e-3282-5f14-8db3-9f31e5dcac39', 'pt', 'Literatura Portuguesa')
ON CONFLICT (category_id, language) DO NOTHING;

-- Progress counter for the generation run. Counts only — safe for anon,
-- which is what lets the coordinating session watch the run complete.
CREATE OR REPLACE FUNCTION public.national_question_progress()
RETURNS TABLE(category_slug text, lang text, total bigint, live bigint)
LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$
  SELECT c.category_id, c.language, count(q.id),
         count(q.id) FILTER (WHERE q.in_production)
  FROM categories c
  LEFT JOIN questions q ON q.category_id = c.id AND q.is_active
  WHERE c.is_language_specific AND c.language <> 'ka'
  GROUP BY c.category_id, c.language ORDER BY c.category_id;
$$;
REVOKE ALL ON FUNCTION public.national_question_progress() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.national_question_progress() TO anon, authenticated, service_role;

COMMIT;
