import { supabase } from "./client";

/**
 * Call a database function that is not in the generated `types.ts` yet.
 *
 * The generated types are regenerated by Lovable, not by this repo, so a
 * function added in a migration is unknown to the client until that happens.
 * The usual workaround is `(supabase as any).rpc(...)`, which switches off
 * checking for the arguments AND the result.
 *
 * This keeps both: only the function-name lookup is cast away, while the
 * caller still declares what it expects back and gets it checked.
 */
export async function callRpc<TResult>(
  fn: string,
  args?: Record<string, unknown>,
): Promise<{ data: TResult | null; error: { message: string } | null }> {
  const client = supabase as unknown as {
    rpc: (
      name: string,
      params?: Record<string, unknown>,
    ) => Promise<{ data: TResult | null; error: { message: string } | null }>;
  };
  return client.rpc(fn, args);
}
