#!/usr/bin/env python3
"""Build the symbol-only logo bank migration (v2 of guess_logo).

Run:  python3 scripts/popular-image-categories/build-logo-v2-migration.py

The first logo bank was wordmarks — the image spelled the answer, so the
player read instead of guessed. This migration retires it and ships the
symbol-only bank from spec/guess_logo_v2.json:

  * every existing active guess_logo question is set is_active = false
    (not deleted: game history may reference the rows)
  * the v2 rows are inserted with uuid5 ids minted from their "s-" keys,
    which never collide with v1 keys, so re-running is a no-op

Validation is the same as the main generator, plus a guard that every key
carries the v2 "s-" prefix. The total_levels trigger recounts active rows
by itself.
"""

import importlib.util
import json
import pathlib
import sys
import uuid

HERE = pathlib.Path(__file__).parent
OUT = HERE.parent.parent / "supabase" / "migrations" / "20260822120000_guess_logo_symbols.sql"

spec = importlib.util.spec_from_file_location("bm", HERE / "build-migration.py")
bm = importlib.util.module_from_spec(spec)
spec.loader.exec_module(bm)

SLUG = "guess_logo"
CFG = bm.CATEGORIES[SLUG]
CAT_ID = uuid.uuid5(bm.NS, f"category/{SLUG}")


def main() -> None:
    entries = json.loads((HERE / "spec" / "guess_logo_v2.json").read_text())
    errs = []
    if len(entries) != 70:
        errs.append(f"expected 70 entries, got {len(entries)}")
    seen_keys, seen_answers = set(), set()
    for e in entries:
        if not str(e.get("key", "")).startswith("s-"):
            errs.append(f"{e.get('key')}: v2 keys must be prefixed 's-'")
        if e["key"] in seen_keys:
            errs.append(f"duplicate key {e['key']}")
        seen_keys.add(e["key"])
        a = e["answers"]["en"].strip().lower()
        if a in seen_answers:
            errs.append(f"duplicate en answer {a!r}")
        seen_answers.add(a)
        errs.extend(bm.validate_entry(SLUG, e))
    if errs:
        sys.exit("Validation failed:\n" + "\n".join(f"  - {x}" for x in errs))

    lines = []
    lines.append("-- guess_logo v2: symbol-only marks replace the wordmark bank.")
    lines.append("--")
    lines.append("-- Generated by scripts/popular-image-categories/build-logo-v2-migration.py")
    lines.append("-- from spec/guess_logo_v2.json. Regenerate rather than editing by hand.")
    lines.append("--")
    lines.append("-- The v1 rows spelled their own answers (wordmarks); they are retired,")
    lines.append("-- not deleted, because play history may reference them. Ids are uuid5")
    lines.append("-- of v2-prefixed keys, so applying this twice inserts nothing new.")
    lines.append("")
    lines.append("BEGIN;")
    lines.append("")
    # The retire statement must not touch the v2 rows themselves, or a
    # re-run would deactivate them and the conflict-skipped insert would
    # never bring them back. Excluding the v2 ids keeps the file idempotent.
    v2_ids = [
        str(uuid.uuid5(bm.NS, f"{SLUG}/{e['key']}/{lang}"))
        for e in entries
        for lang in bm.LANGS
    ]
    id_list = ",\n    ".join(f"'{i}'" for i in v2_ids)
    lines.append("-- Retire every currently-active logo question except the v2 rows,")
    lines.append("-- so re-running the file cannot deactivate its own bank.")
    lines.append(
        f"UPDATE public.questions SET is_active = false\n"
        f"WHERE category_id = '{CAT_ID}' AND is_active = true\n"
        f"  AND id NOT IN (\n    {id_list}\n  );"
    )
    lines.append("")
    lines.append("INSERT INTO public.questions (")
    lines.append("  id, category_id, language, question_text, correct_answer, incorrect_answers,")
    lines.append("  image_url, difficulty, level_number, is_active, in_production, translated_from")
    lines.append(") VALUES")
    entries_sorted = sorted(
        enumerate(entries), key=lambda p: (bm.DIFF_ORDER[p[1]["difficulty"]], p[0])
    )
    rows = []
    for level_pos, (_, e) in enumerate(entries_sorted):
        level = level_pos // bm.PER_LEVEL + 1
        en_id = uuid.uuid5(bm.NS, f"{SLUG}/{e['key']}/en")
        for lang in bm.LANGS:
            qid = uuid.uuid5(bm.NS, f"{SLUG}/{e['key']}/{lang}")
            stem = CFG["stems"][lang]
            ans = bm.lang_value(e["answers"], lang, e["answers"]["en"])
            wr = bm.lang_value(e["wrong"], lang, e["wrong"]["en"])
            translated_from = "NULL" if lang == "en" else f"'{en_id}'"
            rows.append(
                f"  ('{qid}', '{CAT_ID}', {bm.sq(lang)}, {bm.sq(stem)}, {bm.sq(ans)}, {bm.jarr(wr)}, "
                f"{bm.sq(e['image'])}, {bm.sq(e['difficulty'])}, {level}, true, true, {translated_from})"
            )
    lines.append(",\n".join(rows))
    lines.append("ON CONFLICT (id) DO NOTHING;")
    lines.append("")
    lines.append("COMMIT;")
    lines.append("")
    OUT.write_text("\n".join(lines))
    print(f"Wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
